### ISSUE TITLE
Problem getting Homebridge plugin for Philips Hue startet

### ISSUE THREAD

**Issue by somjo** [ebaauw/homebridge-hue#100]
Hi
This is my first plugin an installation og homebridge

{
	"platforms": {
		"platform": "Hue",
		"name": "hue",
		"users": {},
		"sensors": true,
		"excludeSensorTypes": [],
		"lights": true,
		"ct": true,
		"heartrate": 3,
		"timeout": 5,
		"parallelRequests": 10,
		"waitTimeResend": 300,
		"waitTimeSwitch": 100,
		"waitTimeUpdate": 20
	}
}

When running homebridge I get the following:
pi@raspberrypi:~ $ homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[4/20/2017, 11:22:50 PM] Loaded plugin: homebridge-hue
[4/20/2017, 11:22:50 PM] Registering platform 'homebridge-hue.Hue'
[4/20/2017, 11:22:50 PM] ---
/usr/local/lib/node_modules/homebridge/lib/server.js:202
  var username = config.bridge.username;
                              ^

TypeError: Cannot read property 'username' of undefined
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:202:31)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:52:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:134:18)
pi@raspberrypi:~ $

**Comment by ebaauw** [comment]
You need to specify a `bridge` section in config.json for homebridge itself.  See the homebridge README.  Also , `platforms` should contain an array of objects, not a single object.

**Comment by somjo** [comment]
Thx ebaauw That did the trick
