### ISSUE TITLE
New random error 

### ISSUE THREAD

**Issue by qsgithub1** [ebaauw/homebridge-hue#1110]
#### Issue
Please see attached error. HomeBridge rebooted due to power cut but now facing

[15/09/2022, 03:51:41] [homebridge-hue] This plugin is taking long time to load and preventing Homebridge from starting. See https://homebridge.io/w/JtMGR for more info.
[15/09/2022, 03:51:42] [Hue] Philips hue: TypeError: The "listener" argument must be of type function. Received an instance of Object
    at checkListener (node:events:266:3)
    at ClientRequest.once (node:events:647:3)
    at new ClientRequest (node:_http_client:228:10)
    at Object.request (node:https:357:10)
    at Object.request (/usr/local/lib/node_modules/homebridge-broadband/node_modules/http-proxy-agent/node_modules/agent-base/patch-core.js:25:22)
    at /usr/local/lib/node_modules/homebridge-hue/node_modules/homebridge-lib/lib/HttpClient.js:361:34
    at new Promise (<anonymous>)
    at HueClient.request (/usr/local/lib/node_modules/homebridge-hue/node_modules/homebridge-lib/lib/HttpClient.js:338:12)
    at HueClient.request (/usr/local/lib/node_modules/homebridge-hue/lib/HueClient.js:576:36)
    at HueClient.post (/usr/local/lib/node_modules/homebridge-hue/lib/HueClient.js:395:17)

#### Log Messages

```
```

**Comment by ebaauw** [comment]
`homebridge-broadband` is breaking `https`. See https://github.com/ebaauw/homebridge-hue/issues/629.
