### ISSUE TITLE
Recalling a scene from the Hue app throws error

### ISSUE THREAD

**Issue by CooperCGN** [ebaauw/homebridge-hue#1142]
#### Issue
as the title says recalling a scene from the hue app is causing homebridge-hue to throw the error mentioned below. The string "o5SLy7svRu6H3YF" seems to be the scene name as I am using those in some HomeKit automatons to recall those scenes. Other than that the plugin is working as expected.

#### Log Messages

```
[30/01/2023, 06:41:09] [Hue] Philips hue: event stream error: TypeError: Cannot read properties of undefined (reading 'o5SLy7svRu6H3YF')
    at EventStreamClient.<anonymous> (/var/lib/homebridge/node_modules/homebridge-hue/lib/HueBridge.js:1052:29)
    at EventStreamClient.emit (node:events:513:28)
    at EventStreamClient.parseUpdate (/var/lib/homebridge/node_modules/homebridge-hue/lib/EventStreamClient.js:280:16)
    at EventStreamClient.parseContainer (/var/lib/homebridge/node_modules/homebridge-hue/lib/EventStreamClient.js:198:16)
    at IncomingMessage.<anonymous> (/var/lib/homebridge/node_modules/homebridge-hue/lib/EventStreamClient.js:162:26)
    at IncomingMessage.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at IncomingMessage.Readable.push (node:internal/streams/readable:234:10)
    at HTTPParser.parserOnBody (node:_http_common:129:24)

```

#### Debug Files

[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/10532932/homebridge-hue.json.gz)

**Comment by ebaauw** [comment]
Looks like Homebridge Hue chokes on something the Hue bridge publishes on the event stream on scene recall.  I don't think I've seen scene recall events before.

Could you please run `ph -DDD -H x.x.x.x eventlog` and capture the raw data when recalling the scene?

**Comment by CooperCGN** [comment]
When I log into my Pi and try to run the command I get "-bash: ph: command not found". Where is it located? Maybe I need to run it directly from the directory. (I am using the official Homebridge image).

**Comment by ebaauw** [comment]
It should be installed with Homebrdige Hue.  Try `npx ph ...`, or locate it as `ph.js` in the `cli` directory of Homebridge Hue.

I see your bridge has a later firmware version than mine.  I guess they added new events in that version.

**Comment by CooperCGN** [comment]
Hope I did everything right and this helps

[eventlog.txt](https://github.com/ebaauw/homebridge-hue/files/10534196/eventlog.txt)

**Comment by ebaauw** [comment]
Thanks, I think I can work with that.  Definitely some new feature by the Hue bridge.

**Comment by CooperCGN** [comment]
Great, if you need any more info please let me know.

**Comment by CooperCGN** [comment]
Great to hear, waiting for the update then to test this.

**Comment by ebaauw** [comment]
In v0.13.52.

**Comment by CooperCGN** [comment]
Works as expected, guess this can be closed then.
