### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by kaskoo** [ebaauw/homebridge-hue#1197]
#### Issue

I have the following exception every 5min since I updated to the v0.14.3 release.

#### Log Messages

```[10/11/2024 20:35:53] [Hue] Hue Bridge: event stream error: TypeError: Cannot read properties of undefined (reading 'startsWith')
    at EventStreamClient._parseUpdate1 (file:///var/lib/homebridge/node_modules/homebridge-hue/node_modules/hb-hue-tools/lib/EventStreamClient.js:213:26)
    at EventStreamClient._parseContainer (file:///var/lib/homebridge/node_modules/homebridge-hue/node_modules/hb-hue-tools/lib/EventStreamClient.js:179:54)
    at IncomingMessage.<anonymous> (file:///var/lib/homebridge/node_modules/homebridge-hue/node_modules/hb-hue-tools/lib/EventStreamClient.js:143:26)
    at IncomingMessage.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at IncomingMessage.Readable.push (node:internal/streams/readable:392:5)
    at HTTPParser.parserOnBody (node:_http_common:129:24)
    at TLSSocket.socketOnData (node:_http_client:546:22)
    at TLSSocket.emit (node:events:518:28)
```

#### Debug Files

{
    "name": "Hue",
    "anyOn": true,
    "effects": true,
    "groups": true,
    "heartrate": 15,
    "lights": true,
    "nativeHomeKitLights": true,
    "nativeHomeKitSensors": true,
    "resource": true,
    "rules": false,
    "schedules": false,
    "sensors": false,
    "users": {
        "aa": "xx"
    },
    "_bridge": {
        "username": "00",
        "port": 48270
    },
    "platform": "Hue"
}

**Comment by ebaauw** [comment]
You didn't include the actual error message, just the stack trace.

**Comment by ebaauw** [comment]
Assuming it's indeed the error I suspect, v0.14.4 should solve this.

**Comment by kaskoo** [comment]
After a second look on config file, the hostname had disappeared from the config file. 
And the hostname of the hue bridge has changed with some 'fff' added in the middle of the hostname certificate. 

**Now with v0.14.4 has solved the problem with the hostname corrected. It is working.**

I only have a warning about a deprecated node function, but I think you are already aware of it : 
```[Hue] Loaded homebridge-hue v0.14.4 child bridge successfully
(node:3212567) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

_Just for information, I always have the drifting warning every (running home bridge on debian hosted in a ESXi, which is not overloaded). Appart of overloading the logs, it is a minor problem to me:_ 
```
[11/11/2024 13:01:59] [Hue] heartbeat 399, drift 3584
[11/11/2024 13:01:59] [Hue] heartbeat 400, drift 2586
[11/11/2024 13:01:59] [Hue] heartbeat 401, drift 1587
[11/11/2024 13:01:59] [Hue] heartbeat 402, drift 588
[11/11/2024 13:02:35] [Hue] heartbeat 435, drift 3584
[11/11/2024 13:02:35] [Hue] heartbeat 436, drift 2586
[11/11/2024 13:02:35] [Hue] heartbeat 437, drift 1587
[11/11/2024 13:02:35] [Hue] heartbeat 438, drift 589
[11/11/2024 13:03:11] [Hue] heartbeat 471, drift 3585
[11/11/2024 13:03:11] [Hue] heartbeat 472, drift 2587
[11/11/2024 13:03:11] [Hue] heartbeat 473, drift 1588
[11/11/2024 13:03:11] [Hue] heartbeat 474, drift 589
```

**Comment by ebaauw** [comment]
> heartbeat 399, drift 3584

This is a debug message that indicates that the heartbeat event didn't occur at the scheduled time, but 3.584 seconds late.  Typically this happens when NodeJS is doing some blocking processing (like synchronous I/O) for another plugin, or, indeed, when the system is overloaded.  Are you running Homebridge Hue in a separate child bridge?
