### ISSUE TITLE
Homebridge 0.4.28

### ISSUE THREAD

**Issue by Krocko** [ebaauw/homebridge-hue#163]
@ebaauw can you do something?

```
Sep 15 22:03:29 raspberrypi homebridge[2863]: [2017-9-15 22:03:29] ERROR LOADING PLUGIN homebridge-hue:
Sep 15 22:03:29 raspberrypi homebridge[2863]: [2017-9-15 22:03:29] Error: Plugin /usr/local/lib/node_modules/homebridge-hue requires a HomeBridge version of 0.4.27 which does not satisfy the current HomeBridge version of 0.4.28. You may need to upgrade your installation of HomeBridge.
Sep 15 22:03:29 raspberrypi homebridge[2863]: at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:56:11)
Sep 15 22:03:29 raspberrypi homebridge[2863]: at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:132:14)
Sep 15 22:03:29 raspberrypi homebridge[2863]: at Array.forEach (<anonymous>)
Sep 15 22:03:29 raspberrypi homebridge[2863]: at Server._loadPlugins (/usr/local/lib/node_modules/homebridge/lib/server.js:128:22)
Sep 15 22:03:29 raspberrypi homebridge[2863]: at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:51:24)
Sep 15 22:03:29 raspberrypi homebridge[2863]: at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
Sep 15 22:03:29 raspberrypi homebridge[2863]: at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Sep 15 22:03:29 raspberrypi homebridge[2863]: at Module._compile (module.js:624:30)
Sep 15 22:03:29 raspberrypi homebridge[2863]: at Object.Module._extensions..js (module.js:635:10)
Sep 15 22:03:29 raspberrypi homebridge[2863]: at Module.load (module.js:545:32)
```

**Comment by ebaauw** [comment]
homebridge-hue v0.5.31

**Comment by Krocko** [comment]
Problem solved. Thank you.
