### ISSUE TITLE
homebridge version issues

### ISSUE THREAD

**Issue by jaytay79** [ebaauw/homebridge-hue#210]
I'm having some issues with homebridge since updating homebridge-hue which look to be related to my version of homebridge.....

```
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[11/10/2017, 8:47:00 PM] ====================
[11/10/2017, 8:47:00 PM] ERROR LOADING PLUGIN homebridge-hue:
[11/10/2017, 8:47:00 PM] Error: Plugin /home/jim/.npm-global/lib/node_modules/homebridge-hue requires a HomeBridge version of ^0.4.31 which does not satisfy the current HomeBridge version of 0.4.28. You may need to upgrade your installation of HomeBridge.
    at Plugin.load (/usr/lib/node_modules/homebridge/lib/plugin.js:56:11)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:132:14)
    at Array.forEach (native)
    at Server._loadPlugins (/usr/lib/node_modules/homebridge/lib/server.js:128:22)
    at new Server (/usr/lib/node_modules/homebridge/lib/server.js:51:24)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3
[11/10/2017, 8:47:00 PM] ====================
/usr/lib/node_modules/homebridge/lib/api.js:122
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
      ^

Error: The requested platform 'Hue' was not registered by any plugin.
    at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:122:13)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:284:45)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:80:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3
```

However `npm list -g` says:

```
/home/jim/.npm-global/lib
├─┬ homebridge@0.4.31
│ ├─┬ chalk@1.1.3
│ │ ├── ansi-styles@2.2.1
│ │ ├── escape-string-regexp@1.0.5
│ │ ├─┬ has-ansi@2.0.0
│ │ │ └── ansi-regex@2.1.1
│ │ ├── strip-ansi@3.0.1
│ │ └── supports-color@2.0.0
│ ├─┬ commander@2.8.1
│ │ └── graceful-readlink@1.0.1
│ ├─┬ hap-nodejs@0.4.36
│ │ ├── buffer-shims@1.0.0
│ │ ├─┬ curve25519-n2@1.1.3
│ │ │ ├── bindings@1.2.1
│ │ │ └── nan@2.7.0
│ │ ├─┬ debug@2.6.9
│ │ │ └── ms@2.0.0
│ │ ├── decimal.js@7.3.0
│ │ ├── ed25519@0.0.4
│ │ ├── fast-srp-hap@1.0.1
│ │ ├── ip@1.1.5
│ │ ├─┬ mdns@2.3.3
│ │ │ └── nan@2.3.5
│ │ └─┬ node-persist@0.0.11
│ │   └─┬ mkdirp@0.5.1
│ │     └── minimist@0.0.8
│ ├─┬ node-persist@0.0.8
│ │ ├── mkdirp@0.3.5
│ │ └── q@1.1.2
│ ├── qrcode-terminal@0.11.0
│ └── semver@5.0.3
├─┬ homebridge-hue@0.5.43
│ ├─┬ deferred@0.7.8
│ │ ├── d@1.0.0
│ │ ├─┬ es5-ext@0.10.35
│ │ │ ├── es6-iterator@2.0.3
│ │ │ └── es6-symbol@3.1.1
│ │ ├── event-emitter@0.3.5
│ │ ├── next-tick@1.0.0
│ │ └── timers-ext@0.1.2
│ ├─┬ request@2.83.0
│ │ ├── aws-sign2@0.7.0
│ │ ├── aws4@1.6.0
│ │ ├── caseless@0.12.0
│ │ ├─┬ combined-stream@1.0.5
│ │ │ └── delayed-stream@1.0.0
│ │ ├── extend@3.0.1
│ │ ├── forever-agent@0.6.1
│ │ ├─┬ form-data@2.3.1
│ │ │ └── asynckit@0.4.0
│ │ ├─┬ har-validator@5.0.3
│ │ │ ├─┬ ajv@5.3.0
│ │ │ │ ├── co@4.6.0
│ │ │ │ ├── fast-deep-equal@1.0.0
│ │ │ │ ├── fast-json-stable-stringify@2.0.0
│ │ │ │ └── json-schema-traverse@0.3.1
│ │ │ └── har-schema@2.0.0
│ │ ├─┬ hawk@6.0.2
│ │ │ ├── boom@4.3.1
│ │ │ ├─┬ cryptiles@3.1.2
│ │ │ │ └── boom@5.2.0
│ │ │ ├── hoek@4.2.0
│ │ │ └── sntp@2.1.0
│ │ ├─┬ http-signature@1.2.0
│ │ │ ├── assert-plus@1.0.0
│ │ │ ├─┬ jsprim@1.4.1
│ │ │ │ ├── extsprintf@1.3.0
│ │ │ │ ├── json-schema@0.2.3
│ │ │ │ └─┬ verror@1.10.0
│ │ │ │   └── core-util-is@1.0.2
│ │ │ └─┬ sshpk@1.13.1
│ │ │   ├── asn1@0.2.3
│ │ │   ├── bcrypt-pbkdf@1.0.1
│ │ │   ├── dashdash@1.14.1
│ │ │   ├── ecc-jsbn@0.1.1
│ │ │   ├── getpass@0.1.7
│ │ │   ├── jsbn@0.1.1
│ │ │   └── tweetnacl@0.14.5
│ │ ├── is-typedarray@1.0.0
│ │ ├── isstream@0.1.2
│ │ ├── json-stringify-safe@5.0.1
│ │ ├─┬ mime-types@2.1.17
│ │ │ └── mime-db@1.30.0
│ │ ├── oauth-sign@0.8.2
│ │ ├── performance-now@2.1.0
│ │ ├── qs@6.5.1
│ │ ├── safe-buffer@5.1.1
│ │ ├── stringstream@0.0.5
│ │ ├─┬ tough-cookie@2.3.3
│ │ │ └── punycode@1.4.1
│ │ ├── tunnel-agent@0.6.0
│ │ └── uuid@3.1.0
│ ├── semver@5.4.1
│ └─┬ ws@3.3.1
│   ├── async-limiter@1.0.0
│   └── ultron@1.1.0
└─┬ homebridge-platform-ring-video-doorbell@0.5.0
  ├─┬ doorbot@3.0.1
  │ └─┬ debug@2.6.9
  │   └── ms@2.0.0
  ├── hap-nodejs-community-types@0.2.0-alpha0 (git+https://github.com/homespun/hap-nodejs-community-types.git#a6b7963cafc506bea73051d0d48b7f56ba9160a8)
  ├─┬ homespun-discovery@0.1.21
  │ ├── arp-a@0.5.1
  │ ├─┬ bonjour@3.5.0
  │ │ ├── array-flatten@2.1.1
  │ │ ├── deep-equal@1.0.1
  │ │ ├── dns-equal@1.0.0
  │ │ ├─┬ dns-txt@2.0.2
  │ │ │ └── buffer-indexof@1.1.1
  │ │ └── multicast-dns-service-types@1.1.0
  │ ├─┬ glob@7.1.2
  │ │ ├── fs.realpath@1.0.0
  │ │ ├─┬ inflight@1.0.6
  │ │ │ └── wrappy@1.0.2
  │ │ ├── inherits@2.0.3
  │ │ ├─┬ minimatch@3.0.4
  │ │ │ └─┬ brace-expansion@1.1.8
  │ │ │   ├── balanced-match@1.0.0
  │ │ │   └── concat-map@0.0.1
  │ │ ├── once@1.4.0
  │ │ └── path-is-absolute@1.0.1
  │ ├─┬ multicast-dns@6.1.1
  │ │ ├─┬ dns-packet@1.2.2
  │ │ │ ├── ip@1.1.5
  │ │ │ └── safe-buffer@5.1.1
  │ │ └── thunky@0.1.0
  │ ├─┬ pcap2@3.0.4
  │ │ ├── nan@2.7.0
  │ │ └── socketwatcher@0.3.0
  │ ├── pluralize@3.0.0
  │ ├── snmp-native@1.0.18
  │ ├── uuid@3.0.0
  │ └─┬ xml2js@0.2.8
  │   └── sax@0.5.8
  └── underscore@1.8.3

```

Am I missing something here? I can't see an older version of homebridge in that list. `npm list` doesn't have anything relevant to homebridge at all...

**Comment by computerwhizdd** [comment]
Looks like you just need to update homebridge itself. The log says you're using homebridge 0.4.28 and the newest version of homebridge-hue needs homebridge 0.4.31. Try running the following command in terminal: `sudo npm update -g homebridge`. If that doesn't work, you could also try: `sudo npm install -g homebridge` or `sudo npm install -g --unsafe-perm homebridge`. Hope that helps!

**Comment by jaytay79** [comment]
Sadly @computerwhizdd I have already tried all of those and as I put above, `npm list -g` shows `homebridge@0.4.31`! I've even tried uninstalling homebridge and reinstalling but the issue persists.

**Comment by computerwhizdd** [comment]
My bad, I misread that part. Sorry.

**Comment by ebaauw** [comment]
Odd, never seen this.  Are you sure you have only one installation of homebridge?

> /usr/lib/node_modules/homebridge/lib/api.js:122

> /home/jim/.npm-global/lib

**Comment by jaytay79** [comment]
@ebaauw AFAIK I only have one as I cannot track down a second install `npm list` doesn't show homebridge and it's only in `npm list -g`. I definitely haven't reinstalled homebridge for some time (at least until this issue started earlier). Having said all that it does look like there's a second older homebridge in there somewhere, I just need to try and track it down.....

**Comment by jaytay79** [comment]
Gah, found it. Somehow I have one homebridge in `/usr/lib/node_modules` and another in `/home/jim/.npm-global/lib/node_modules/` the former was 0.4.28 and must have been from an update where I mistakenly missed the -g flag! My issues must have only just arisen since homebridge-hue is now checking the version number of homebridge. Sorry to waste your time!
