### ISSUE TITLE
Problem with Osram Smart+ Flex LED

### ISSUE THREAD

**Issue by MikeDeltaHH** [ebaauw/homebridge-hue#237]
Hi!
the plugin brings a warning and the light isn´t show in homekit:

"Dez 25 22:27:59 homebridge homebridge[25285]: [2017-12-25 22:27:59] [Hue] Philips hue: /lights/20: warning: unknown light model {"state":{" on":false,"bri":254,"hue":4352,"sat":208,"effect":"none","xy":[0.4608,0.4107],"ct":370,"alert":"select","colormode":"ct","mode":"homeautoma tion","reachable":true},"swupdate":{"state":"notupdatable","lastinstall":null},"type":"Extended color light","name":"Licht Terrasse","model id":"LIGHTIFY Outdoor Flex RGBW","manufacturername":"OSRAM","capabilities":{"streaming":{"renderer":false,"proxy":false}},"uniqueid":"7c:b0 :3e:aa:00:a3:7d:e5-03","swversion":"V1.04.93"}"

Can you help?

Regards!
Mike

**Comment by ebaauw** [comment]
The warning is because homebridge-hue doesn't (yet) know this light.  That I can change.

But it should be exposed to HomeKit anyways.  If it isn't, something else is wrong.  Could you please post the output of `homebridge -D` (see **Troubleshooting** in the README)?

**Comment by MikeDeltaHH** [comment]
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2017-12-26 01:05:19] Loaded plugin: homebridge-fakebulb
[2017-12-26 01:05:19] Registering accessory 'homebridge-fakebulb.FakeBulb'
[2017-12-26 01:05:19] ---
[2017-12-26 01:05:20] Loaded plugin: homebridge-fritz
[2017-12-26 01:05:20] Registering platform 'homebridge-fritz.Fritz!Box'
[2017-12-26 01:05:20] ---
[2017-12-26 01:05:20] Loaded plugin: homebridge-harmonyhub
[2017-12-26 01:05:22] Registering platform 'homebridge-harmonyhub.HarmonyHub'
[2017-12-26 01:05:22] ---
[2017-12-26 01:05:22] Loaded plugin: homebridge-homematic
[2017-12-26 01:05:22] Registering platform 'homebridge-homematic.HomeMatic'
[2017-12-26 01:05:22] ---
[2017-12-26 01:05:22] Plugin /usr/local/lib/node_modules/homebridge-hue requires Node version of ^8.9.3 which does not satisfy the current Node version of v8.4.0. You may need to upgrade your installation of Node.
[2017-12-26 01:05:23] Loaded plugin: homebridge-hue
[2017-12-26 01:05:23] Registering platform 'homebridge-hue.Hue'
[2017-12-26 01:05:23] ---
[2017-12-26 01:05:24] Loaded plugin: homebridge-netatmo
[2017-12-26 01:05:24] Registering platform 'homebridge-netatmo.netatmo'
[2017-12-26 01:05:24] ---
[2017-12-26 01:05:24] Loaded plugin: homebridge-people
[2017-12-26 01:05:24] Registering platform 'homebridge-people.People'
[2017-12-26 01:05:24] Registering accessory 'homebridge-people.PeopleAccessory'
[2017-12-26 01:05:24] Registering accessory 'homebridge-people.PeopleAllAccessory'
[2017-12-26 01:05:24] ---
[2017-12-26 01:05:25] Loaded plugin: homebridge-sonos-schmittx
[2017-12-26 01:05:25] Registering accessory 'homebridge-sonos.Sonos'
[2017-12-26 01:05:25] ---
[2017-12-26 01:05:26] Loaded plugin: homebridge-synology
[2017-12-26 01:05:26] Registering accessory 'homebridge-synology.Synology'
[2017-12-26 01:05:26] ---
[2017-12-26 01:05:26] Loaded plugin: homebridge-wol
[2017-12-26 01:05:26] Registering accessory 'homebridge-wol.NetworkDevice'
[2017-12-26 01:05:26] ---
[2017-12-26 01:05:26] config.json (/home/pi/.homebridge/config.json) not found.
Load homebridge-harmonyhub.HarmonyHub
[2017-12-26 01:05:26] [homebridge-harmonyhub.HarmonyHub] Ignoring Harmony Platform setup because it is not configured
Setup Payload:
X-HM://0023ISYWYC43A
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:

Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ 031-45-154 │
    └────────────┘

/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:56
  dns_sd.DNSServiceRegister(self.serviceRef, flags, ifaceIdx, name,
         ^

Error: dns service error: name conflict
    at new Advertisement (/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:56:10)
    at Object.create [as createAdvertisement] (/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:64:10)
    at Advertiser.startAdvertising (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Advertiser.js:47:30)
    at Bridge.Accessory._onListening (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:655:20)
    at emitOne (events.js:115:13)
    at HAPServer.emit (events.js:210:7)
    at HAPServer._onListening (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:195:8)
    at emitOne (events.js:115:13)
    at EventedHTTPServer.emit (events.js:210:7)
    at EventedHTTPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:65:10)
    at emitNone (events.js:105:13)
    at Server.emit (events.js:207:7)
    at emitListeningNT (net.js:1349:10)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:611:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3

**Comment by ebaauw** [comment]
> [2017-12-26 01:05:26] config.json (/home/pi/.homebridge/config.json) not found.

This is not the same homebridge configuration as you used before.  I think you might be running homebridge as a service under a different username?

> /usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:56
dns_sd.DNSServiceRegister(self.serviceRef, flags, ifaceIdx, name,
^
Error: dns service error: name conflict
at new Advertisement 

I haven’t seen this error before.  It’s from homebridge itself, not from a plugin.  My guess is that the homebridge service is still running on a different port when you started homebridge manually?

Could you try and edit the service configuration file to add `-D` to the `ExecStart` line?  Typically it’s `/etc/systemd/system/homebridge.service`.

**Comment by MikeDeltaHH** [comment]
Hi!
Homebridge running as a service on the standard port. This error comes from the harmony plugin, because i have two harmony bridges. But the error with the light is gone after some hours - the osram flex is identified correctly in homekit and works very well. Thanks for your support and the good plugin!
