### ISSUE TITLE
Hue Hub v1.22 errors... important?

### ISSUE THREAD

**Issue by aguaman15** [ebaauw/homebridge-hue#257]
#### Issue

Hi Erik,

I've really been enjoying your Hue plugin. It's excellent work, man. Anyway, I recently updated my Hue hub's firmware to v1.22 (the sunset feature was too good to pass up). I understand that v1.21 is currently the preferred firmware version to work with the plugin, and I know you haven't had time to test v1.22 yet. I'm just wondering if I should be worried about these errors when I start up Homebridge:

#### Log Messages

```
[2018-1-8 17:12:47] [Hue] Philips hue: BSB002 bridge v1711151408, api v1.22.0
[2018-1-8 17:12:47] [Hue] Philips hue: TypeError: Cannot read property 'on' of undefined
    at HueBridge.exposeBridge (/usr/local/lib/node_modules/homebridge-hue/lib/HueBridge.js:218:5)
    at getConfig.then (/usr/local/lib/node_modules/homebridge-hue/lib/HueBridge.js:89:17)
    at Function.then (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/_ext.js:67:13)
    at Deferred._settle (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:97:26)
    at Deferred.resolve (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:142:15)
    at _request.then (/usr/local/lib/node_modules/homebridge-hue/lib/HueBridge.js:111:7)
    at Function.then (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/_ext.js:67:13)
    at Deferred._settle (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:97:26)
    at Deferred.resolve (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:142:15)
    at Request.request [as _callback] (/usr/local/lib/node_modules/homebridge-hue/lib/HueBridge.js:1023:14)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-hue/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-hue/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
[2018-1-8 17:12:47] [Hue] Philips hue: 0 accessories
[2018-1-8 17:12:47] [Hue] TypeError: Cannot read property 'config' of undefined
    at HuePlatform.dump (/usr/local/lib/node_modules/homebridge-hue/lib/HuePlatform.js:629:11)
    at request.then.catch.then.then (/usr/local/lib/node_modules/homebridge-hue/lib/HuePlatform.js:567:17)
    at Function.then (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/_ext.js:67:13)
    at Deferred._settle (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:97:26)
    at Deferred.resolve (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:142:15)
    at Function.<anonymous> (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/ext/promise/_array.js:34:4)
    at Deferred._settle (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:97:26)
    at Deferred.resolve (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:142:15)
    at DMap.processValue (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/ext/array/map.js:77:49)
    at Function.done (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/_ext.js:85:12)
    at Deferred._settle (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:97:26)
    at Deferred.resolve (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:142:15)
    at Function.then (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/_ext.js:72:4)
    at Deferred._settle (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:97:26)
    at Deferred.resolve (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:142:15)
    at Function.<anonymous> (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/ext/promise/catch.js:48:4)
```

Thanks for the advice in advance.

**Comment by ebaauw** [comment]
v1.22.0 should work (or there would be a warning message after the message with the bridge version).  Yes, you should worry, homebridge-hue throws this error while trying to setup your bridge, and doesn’t expose anything to homekit.  Could you please attact the dumpfile, if homebridge-hue created one?  See https://github.com/ebaauw/homebridge-hue#debug-dump-file.  If not, could you run homebridge -D and attact the logfile?  See https://github.com/ebaauw/homebridge-hue#debug-log-file.

**Comment by ebaauw** [comment]
The second `TypeError` is because homebridge-hue tries to dump the bridge state, which it doesn’t have, because of the first `TypeError`.

I don’t see how homebridge-hue could have caused the first `TypeError`.  It looks like #95.  Did you update homebridge, and/or install other plugins when upgrading the bridge firmware?

**Comment by aguaman15** [comment]
Sorry. Haven’t had a chance to reply until now. Yes, I updated node and non, homebridge, and hue plugins. Also iTunes plugin. I’m glad you closed this though, as my free time just vanished. I’ve disabled the Hue plugin for now and am just dealing with what I have. It’s not like I want it but i can work with it until I can get time to tackle it. Thank you so much for replying.
