### ISSUE TITLE
Downgrade to v0.5.60 don‘t work

### ISSUE THREAD

**Issue by Krocko** [ebaauw/homebridge-hue#258]
Hi Erik. How can i downgrade from v0.5.61 to v0.5.60?

I have installed homebridge 0.4.35 and have several problems. I downgraded Homebridge to 0.4.33 and got the following error in the Homebridge Log 

```
Jan  9 21:46:30 raspberrypi homebridge[13860]: /usr/local/lib/node_modules/homebridge/lib/api.js:122
Jan  9 21:46:30 raspberrypi homebridge[13860]: throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
Jan  9 21:46:30 raspberrypi homebridge[13860]: ^
Jan  9 21:46:30 raspberrypi homebridge[13860]: Error: The requested platform 'Hue' was not registered by any plugin.
Jan  9 21:46:30 raspberrypi homebridge[13860]: at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:122:13)
Jan  9 21:46:30 raspberrypi homebridge[13860]: at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:294:45)
Jan  9 21:46:30 raspberrypi homebridge[13860]: at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:85:36)
Jan  9 21:46:30 raspberrypi homebridge[13860]: at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
Jan  9 21:46:30 raspberrypi homebridge[13860]: at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Jan  9 21:46:30 raspberrypi homebridge[13860]: at Module._compile (module.js:643:30)
Jan  9 21:46:30 raspberrypi homebridge[13860]: at Object.Module._extensions..js (module.js:654:10)
Jan  9 21:46:30 raspberrypi homebridge[13860]: at Module.load (module.js:556:32)
Jan  9 21:46:30 raspberrypi homebridge[13860]: at tryModuleLoad (module.js:499:12)
Jan  9 21:46:30 raspberrypi homebridge[13860]: at Function.Module._load (module.js:491:3)
Jan  9 21:46:30 raspberrypi homebridge[13860]: at Function.Module.runMain (module.js:684:10)
Jan  9 21:46:30 raspberrypi homebridge[13860]: at startup (bootstrap_node.js:187:16)
Jan  9 21:46:30 raspberrypi homebridge[13860]: at bootstrap_node.js:608:3
Jan  9 21:46:30 raspberrypi systemd[1]: homebridge.service: main process exited, code=exited, status=1
```

If i install homebridge-hue@0.5.60 i got the following error

```
sudo npm install -g homebridge-hue@0.5.60
npm WARN deprecated homebridge-hue@0.5.60: lastest version v0.5.61
npm ERR! path /usr/local/lib/node_modules/homebridge-hue/node_modules/homebridge-hue-utils/lib/dc_eventlog.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/homebridge-hue/node_modules/homebridge-hue-utils/lib/dc_eventlog.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-01-09T20_44_56_000Z-debug.log
```

**Comment by SeydX** [comment]
I can confirm, i cant also downgrade to 0.5.60...

and if i downgrade homebridge to 0.4.33, the hue plugin dont start anymore after restart..

**Comment by ebaauw** [comment]
For downgrading: Could you try to `sudo npm uninstall -g homebridge-hue` before `sudo npm -g install homebridge-hue@0.5.60`?

I have no clue about the homebridge downgrade: it looks like homebridge doesn’t find the homebridge-hue plugin.  Will need to do some testing when I’m back home.

What problems are you experiencing with homebridge v0.4.35?

**Comment by to0b** [comment]
With homebridge@0.4.35, in my case, the Xiaomi sensors (Aqara Motion and aqara door/window contact) doesn‘t display the correct state in HomeKit after homebridge is running a few hours. Sometimes the state of the sensor is correctly displayed but they don‘t trigger linked automation rules. When I restart homebridge everything works fine for a while.

**Comment by Krocko** [comment]
I changed line 50 in your package.json to

`50         "homebridge": "^0.4.33",`

and v.0.5.61 works with homebridge 0.4.33

**Comment by ebaauw** [comment]
OK, back home.  Let's see:
```
$ sudo systemctl stop homebridge
$ npm -g list --depth=0
/usr/lib
├── homebridge@0.4.35
├── homebridge-hue@0.5.61
└── npm@5.6.0

$ sudo npm -g i homebridge@0.4.33 --unsafe-perm
/usr/bin/homebridge -> /usr/lib/node_modules/homebridge/bin/homebridge
+ homebridge@0.4.33
updated 2 packages in 5.481s
$ npm -g list --depth=0
/usr/lib
├── homebridge@0.4.33
├── homebridge-hue@0.5.61
└── npm@5.6.0

$ homebridge -D
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2018-1-10 19:36:08] ====================
[2018-1-10 19:36:08] ERROR LOADING PLUGIN homebridge-hue:
[2018-1-10 19:36:08] Error: Plugin /usr/lib/node_modules/homebridge-hue requires a HomeBridge version of ^0.4.35 which does not satisfy the current HomeBridge version of 0.4.33. You may need to upgrade your installation of HomeBridge.
    at Plugin.load (/usr/lib/node_modules/homebridge/lib/plugin.js:56:11)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:142:14)
    at Array.forEach (<anonymous>)
    at Server._loadPlugins (/usr/lib/node_modules/homebridge/lib/server.js:138:22)
    at new Server (/usr/lib/node_modules/homebridge/lib/server.js:56:24)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
[2018-1-10 19:36:08] ====================
[2018-1-10 19:36:08] No plugins found. See the README for information on installing plugins.
[2018-1-10 19:36:09] Loaded config.json with 0 accessories and 1 platforms.
[2018-1-10 19:36:09] ---
[2018-1-10 19:36:09] Loading 1 platforms...
/usr/lib/node_modules/homebridge/lib/api.js:122
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
      ^

Error: The requested platform 'Hue' was not registered by any plugin.
    at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:122:13)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:294:45)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
```
The error you posted is the result of:
```
[2018-1-10 19:36:08] ERROR LOADING PLUGIN homebridge-hue:
[2018-1-10 19:36:08] Error: Plugin /usr/lib/node_modules/homebridge-hue requires a HomeBridge version of ^0.4.35 which does not satisfy the current HomeBridge version of 0.4.33. You may need to upgrade your installation of HomeBridge.
```
My bad.  I thought they'd changed the check for the required homebridge version when loading plugins to a warning, instead of an error.  Indeed, @Krocko's "hack" to change the version in package.json is the right answer here.  I'll release a new version shortly, where the dependency is back to homebridge@0.4.33.

**Comment by ebaauw** [comment]
Next:
```
$ sudo npm -g install homebridge-hue@0.5.60
npm WARN deprecated homebridge-hue@0.5.60: lastest version v0.5.61
npm ERR! path /usr/lib/node_modules/homebridge-hue/node_modules/homebridge-hue-utils/lib/dc_eventlog.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/lib/node_modules/homebridge-hue/node_modules/homebridge-hue-utils/lib/dc_eventlog.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-01-10T18_49_30_737Z-debug.log
$ npm -g list --depth=0
/usr/lib
├── homebridge@0.4.33
└── npm@5.6.0

```
WTF?!  This installed find the other day.  Let's check the log:
```
22 silly pacote range manifest for homebridge-hue-utils@^0.1.2 fetched in 410ms
23 silly resolveWithNewModule homebridge-hue-utils@0.1.3 checking installable status
```
Oops, npm installs homebridge-hue-utils@0.1.3 where homebridge-hue@0.5.60 expects @0.1.2.  My bad, I changed the path of the cli files from `/lib` to `/cli` which is a breaking change, so I should have updated homebridge-hue-utils to v0.2.0.  Let me see if I can fix that.

Removed homebridge-hue@0.5.61 and homebridge-hue-utils@0.1.3 from the registry and fixed the `latest` tag.
```
$ sudo npm cache clear --force
npm WARN using --force I sure hope you know what you are doing.
```
So do I...
```
$ sudo npm -g install homebridge-hue
/usr/bin/dc_eventlog -> /usr/lib/node_modules/homebridge-hue/node_modules/homebridge-hue-utils/lib/dc_eventlog.js
/usr/bin/json -> /usr/lib/node_modules/homebridge-hue/node_modules/homebridge-hue-utils/lib/json.js
+ homebridge-hue@0.5.60
updated 1 package in 13.78s
```
We're back!

**Comment by grover** [comment]
Yeah sorry about introducing the bug in homebridge itself. If anyone is willing to provide some logs of the event traffic, write me in https://github.com/nfarina/homebridge/issues/1698

I'm already gathering logs from some users, but fail to understand the actual root cause of the problems. I'm about to post instructions in the linked issue.
