### ISSUE TITLE
Error Lumi Cube @ hue 0.8.2 deconz 2.05.09

### ISSUE THREAD

**Issue by mark82436** [ebaauw/homebridge-hue#302]
@ 0.8.2 are Fix the Tradfri CWS problem but i have a new Error for the Lumi Cube

Please can you Check it

Logfile:
[deCONZ] deCONZ-GW: error: /sensors/58: {"config":{"on":true,"reachable":true},"ep":3,"etag":"1da49b03492aab5c63c9e8b0a3dadf6b","manufacturername":"LUMI","mode":1,"modelid":"lumi.sensor_cube","name":"Lumi Cube","state":{"buttonevent":-1607,"lastupdated":"2018-02-26T17:23:03","temperature":2000,"voltage":3005},"type":"ZHASwitch","uniqueid":"00:15:8d:00:01:0d:f1:a9-03-000c"}
 Error: Cannot add a Characteristic with the same UUID as another Characteristic in this Service: E863F10A-079E-48FF-8F27-9C2605A29F52
    at Service.ServiceLabel.Service.addCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Service.js:80:13)
    at new HueSensor (/usr/local/lib/node_modules/homebridge-hue/lib/HueSensor.js:961:20)
    at HueAccessory.exposeSensorResource (/usr/local/lib/node_modules/homebridge-hue/lib/HueAccessory.js:233:20)
    at HueAccessory.exposeSensorResources (/usr/local/lib/node_modules/homebridge-hue/lib/HueAccessory.js:223:12)
    at HueAccessory.expose (/usr/local/lib/node_modules/homebridge-hue/lib/HueAccessory.js:122:8)
    at HueBridge.exposeResources (/usr/local/lib/node_modules/homebridge-hue/lib/HueBridge.js:433:49)
    at getConfig.then.then.then.then (/usr/local/lib/node_modules/homebridge-hue/lib/HueBridge.js:92:17)
    at Function.then (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/_ext.js:67:13)
    at Deferred._settle (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:97:26)
    at Deferred.resolve (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:142:15)
    at request.then (/usr/local/lib/node_modules/homebridge-hue/lib/HueBridge.js:318:11)
    at Function.then (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/_ext.js:67:13)
    at Deferred._settle (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:97:26)
    at Deferred.resolve (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:142:15)
    at Request.request [as _callback] (/usr/local/lib/node_modules/homebridge-hue/lib/HueBridge.js:1034:14)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-hue/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-hue/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-hue/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by ebaauw** [comment]
Can you please attach the debug log and the debug dump files, see https://github.com/ebaauw/homebridge-hue#troubleshooting?

**Comment by mark82436** [comment]
[homebridge.log.gz](https://github.com/ebaauw/homebridge-hue/files/1778316/homebridge.log.gz)

i hope it is right

**Comment by ebaauw** [comment]
Yeah that's right, thanks.  Good you also please attach `/var/homebridge/homebridge-hue.json.gz`?

**Comment by mark82436** [comment]
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/1778335/homebridge-hue.json.gz)

**Comment by ebaauw** [comment]
Thanks!  It's a bug alright.  It looks like homebridge-hue is still working?  I think the only effect is that you cannot use _Turn_ in HomeKit as the _Left_ and _Right_ buttons for the Cube are missing.  I'll fix it in the next version of homebridge-hue.

The bug actually happened in v0.8.1 already.  It's triggered by the new `state.voltage` attribute that deCONZ v2.05.09 creates for the Xioami sensors to report their battery voltage (actually in mV).  The attribute won't be visible in the REST API, until the first report is sent by the Cube.  The bug only appears when you restart homebridge after that.

**Comment by mark82436** [comment]
yes homebridge is running only error on the cube

**Comment by ebaauw** [comment]
Fixed in homebridge-hue v0.8.3 and/or deCONZ v2.05.10.
