### ISSUE TITLE
Can't see deCONZ groups: "TypeError: Cannot read property 'on' of undefined" 

### ISSUE THREAD

**Issue by s4y** [ebaauw/homebridge-hue#313]
#### Issue

deCONZ groups aren't visible in v0.8.6.

I just upgraded homebridge and homebridge-hue for the first time in a while, and I can't see any groups. (As always, thanks so much for your work on this plugin ✨!)

#### Log Messages

```
Mar 15 23:45:56 overkill homebridge[14620]: [3/15/2018, 11:45:56 PM] [Hue] deCONZ-GW: error: /groups/3: {"action":{"bri":254,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":true,"sat":127,"xy":[0,0]},"class":"Other","devicemembership":[],"etag":"a0038ed1233aeaf3651ba753f0dc756d","hidden":false,"id":"3","lights":["4"],"lightsequence":[],"multideviceids":[],"name":"Living Room","scenes":[],"state":{"all_on":true,"any_on":true,"bri":254,"colormode":"hs","ct":0,"effect":"none","hue":0,"sat":127,"xy":[0,0]},"type":"LightGroup"}
Mar 15 23:45:56 overkill homebridge[14620]:  TypeError: Cannot read property 'on' of undefined
Mar 15 23:45:56 overkill homebridge[14620]:     at new HueLight (/var/lib/homebridge/.node_modules/lib/node_modules/homebridge-hue/lib/HueLight.js:538:7)
Mar 15 23:45:56 overkill homebridge[14620]:     at HueBridge.exposeGroup (/var/lib/homebridge/.node_modules/lib/node_modules/homebridge-hue/lib/HueBridge.js:579:23)
Mar 15 23:45:56 overkill homebridge[14620]:     at HueBridge.exposeGroups (/var/lib/homebridge/.node_modules/lib/node_modules/homebridge-hue/lib/HueBridge.js:563:14)
Mar 15 23:45:56 overkill homebridge[14620]:     at HueBridge.exposeResources (/var/lib/homebridge/.node_modules/lib/node_modules/homebridge-hue/lib/HueBridge.js:409:8)
Mar 15 23:45:56 overkill homebridge[14620]:     at getConfig.then.then.then.then (/var/lib/homebridge/.node_modules/lib/node_modules/homebridge-hue/lib/HueBridge.js:95:17)
Mar 15 23:45:56 overkill homebridge[14620]:     at Function.then (/var/lib/homebridge/.node_modules/lib/node_modules/homebridge-hue/node_modules/deferred/_ext.js:67:13)
Mar 15 23:45:56 overkill homebridge[14620]:     at Deferred._settle (/var/lib/homebridge/.node_modules/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:97:26)
Mar 15 23:45:56 overkill homebridge[14620]:     at Deferred.resolve (/var/lib/homebridge/.node_modules/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:142:15)
Mar 15 23:45:56 overkill homebridge[14620]:     at request.then (/var/lib/homebridge/.node_modules/lib/node_modules/homebridge-hue/lib/HueBridge.js:298:11)
Mar 15 23:45:56 overkill homebridge[14620]:     at Function.then (/var/lib/homebridge/.node_modules/lib/node_modules/homebridge-hue/node_modules/deferred/_ext.js:67:13)
Mar 15 23:45:56 overkill homebridge[14620]:     at Deferred._settle (/var/lib/homebridge/.node_modules/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:97:26)
Mar 15 23:45:56 overkill homebridge[14620]:     at Deferred.resolve (/var/lib/homebridge/.node_modules/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:142:15)
Mar 15 23:45:56 overkill homebridge[14620]:     at Request.request [as _callback] (/var/lib/homebridge/.node_modules/lib/node_modules/homebridge-hue/lib/HueBridge.js:1048:14)
Mar 15 23:45:56 overkill homebridge[14620]:     at Request.self.callback (/var/lib/homebridge/.node_modules/lib/node_modules/homebridge-hue/node_modules/request/request.js:186:22)
Mar 15 23:45:56 overkill homebridge[14620]:     at Request.emit (events.js:180:13)
Mar 15 23:45:56 overkill homebridge[14620]:     at Request.<anonymous> (/var/lib/homebridge/.node_modules/lib/node_modules/homebridge-hue/node_modules/request/request.js:1163:10)
Mar 15 23:45:56 overkill homebridge[14620]:     at Request.emit (events.js:180:13)
Mar 15 23:45:56 overkill homebridge[14620]:     at IncomingMessage.<anonymous> (/var/lib/homebridge/.node_modules/lib/node_modules/homebridge-hue/node_modules/request/request.js:1085:12)
Mar 15 23:45:56 overkill homebridge[14620]:     at Object.onceWrapper (events.js:272:13)
Mar 15 23:45:56 overkill homebridge[14620]:     at IncomingMessage.emit (events.js:185:15)
Mar 15 23:45:56 overkill homebridge[14620]:     at endReadableNT (_stream_readable.js:1101:12)
Mar 15 23:45:56 overkill homebridge[14620]:     at process._tickCallback (internal/process/next_tick.js:114:19)
```

#### Debug Files
- [homebridge.log.gz](https://github.com/ebaauw/homebridge-hue/files/1821741/homebridge.log.gz)
- [homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/1821734/homebridge-hue.json.gz)

**Comment by ebaauw** [comment]
Could you please attact the full debug log file and the debug dump file?

**Comment by s4y** [comment]
Sure thing, sorry — added.

**Comment by ebaauw** [comment]
>  25 Mar 17 10:33:20 overkill homebridge[18694]: [3/17/2018, 10:33:20 AM] [Hue] homebridge-hue v0.5.71, node v9.8.0, homebridge v0.4.38

You're running v0.5.71, not v0.8.6.  I think this is the same issue as #279.

**Comment by s4y** [comment]
Thanks — that's bizarre! Running `npm update -g` didn't update it, but running `npm install -g homebridge-hue` did.

**Comment by ebaauw** [comment]
Yes, `npm -g update` doesn't always seem to work, see https://github.com/ebaauw/homebridge-hue#installation.  Maybe it's because the major version is still 0.  Just another `npm -g install homebridge-hue` always seems to do the trick, though.
