### ISSUE TITLE
Homebridge Problem

### ISSUE THREAD

**Issue by xbox2610** [ebaauw/homebridge-hue#335]
Hello everyone I'm trying to set up homebridge with Philips Hue + AqaraPlatform separately work together gives me an error that unfortunately I do not know what is due if you can help me Thanks.{
        "bridge": {
                "name": "Homebridge",
                "username": "CC:22:3D:E3:CE:30",
                "port": 51826,
                "pin": "031-45-154"
        },
        "platforms": [{
                        "platform": "Hue",
                        "host": "192.168.0.115",
                        "users": {
                                "001788FFFE22A7D7": "Mm67zqoXC67TiegQkRIZHgqKQTfpSKUDYi22saeT"

                        },
                        "lights": true,
                        "wallSwitch": false,
                        "groups": false,
                        "group0": false,
                        "rooms": false,
                        "schedules": false,
                        "rules": false,
                        "heartrate": 5,
                        "timeout": 5,
                        "resource": true,
                        "parallelRequests": 10,
                        "waitTimeResend": 300,
                        "waitTimeUpdate": 20
        },
        {
        "platforms": [{
                        "platform": "AqaraPlatform",
                        "sid": ["f0b429dd48cf"],
                        "password": ["8D9A7529A376437F"]

                        }]
                }
        ]
}
----------------------------------------------------------
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2018-4-28 23:15:25] Loaded plugin: homebridge-aqara
[2018-4-28 23:15:25] Registering platform 'homebridge-aqara.AqaraPlatform'
[2018-4-28 23:15:25] ---
[2018-4-28 23:15:26] Loaded plugin: homebridge-hue
[2018-4-28 23:15:26] Registering platform 'homebridge-hue.Hue'
[2018-4-28 23:15:26] ---
[2018-4-28 23:15:26] Loaded config.json with 0 accessories and 2 platforms.
[2018-4-28 23:15:26] ---
[2018-4-28 23:15:26] Loading 2 platforms...
[2018-4-28 23:15:26] [Hue] Initializing Hue platform...
[2018-4-28 23:15:26] [Hue] homebridge-hue v0.9.2, node v8.11.1, homebridge v0.4.38
/usr/lib/node_modules/homebridge/lib/api.js:108
  if (name.indexOf('.') == -1) {
           ^

TypeError: Cannot read property 'indexOf' of undefined
    at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:108:12)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:294:45)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by ebaauw** [comment]
You should specify the `”platforms”` key only once.  It should be a single array with two `”platform”` objects:
```
  ...
  “platforms”: [
    {
      “platform”: “Hue”,
      ...
    },
    {
      “platform”: “AqaraPlatform”,
      ...
    }
  ],
  ...
```

**Comment by xbox2610** [comment]
Thank you Mr Ebaauw now works, unfortunately I learn here and there.
Thanks again
Grazie
