### ISSUE TITLE
Aqara Cube - Cannot add a Service with the same UUID 

### ISSUE THREAD

**Issue by Idelean** [ebaauw/homebridge-hue#397]
#### Issue
Unable to run Homebridge after setting up an Aqara Cube in Deconz. 

Hope you can help me, had some trouble with the entire Homebridge update in addition to node and NPM and now I cannot do anything else. 

Homebridge-Hue still works if I remove the cube

#### Log Messages
```
[2018-11-17 14:44:25] [Hue] Error: Cannot add a Service with the same UUID '00000089-0000-1000-8000-0026BB765291' and subtype 'Right' as another Service in this Accessory.
    at Accessory.addService (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:151:15)
    at /usr/lib/node_modules/homebridge/lib/server.js:454:19
    at Array.forEach (<anonymous>)
    at Server._createAccessory (/usr/lib/node_modules/homebridge/lib/server.js:434:14)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:396:32)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
    at request.then.catch.then.then.then (/usr/lib/node_modules/homebridge-hue/lib/HuePlatform.js:306:5)
    at Function.then (/usr/lib/node_modules/homebridge-hue/node_modules/deferred/_ext.js:67:13)
    at Deferred._settle (/usr/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:97:26)
    at Deferred.resolve (/usr/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:142:15)
    at fs.writeFile (/usr/lib/node_modules/homebridge-hue/lib/HuePlatform.js:377:11)
    at FSReqWrap.oncomplete (fs.js:135:15)
```

[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/2592109/homebridge-hue.json.gz)
[homebridge.log.gz](https://github.com/ebaauw/homebridge-hue/files/2592110/homebridge.log.gz)

**Comment by ebaauw** [comment]
Somehow deCONZ created three REST API resources for the cube, `/sensors/11` for the _Multistate Input_ cluster on endpoint 02, `/sensors/12` for the _Analog Input_ cluster on endpoint 03, and, surprisingly, `/sensors/13` for the _Multistate Input_ cluster on endpoint 01.  homebridge-hue doesn't expect this, and wrongly tries to create the _Stateless Programmable Switch_ services for the _Right_ and _Left_ buttons twice.  I can fix that in homebridge-hue quite easily.

Looking at the deCONZ code, it will create a ZHASwitch `/sensors` resources for the cube, for each endpoint with a server _Multistate Input_ cluster.  I don't think this code has been touched for a long time.  Surprisingly, my `lumi.sensor_cube` also shows a _Multistate Input_ cluster on endpoint 01, but I don't have the corresponding resource.  I image the recent deCONZ improvements in reading the node descriptors now discover this cluster.  I paired my cube ages ago, before these changes.  I can also imagine some creepy bug in the deCONZ REST API, that somehow caused the cube's fingerprint to become corrupted.  I don't know how else to explain that the resources for endpoint 02 and 03 were created before the resource for endpoint 01.  @manup, do you have any ideas on this?  I would need to sniff the ZigBee traffic while pairing the cube to see if it really reports a _Multistate Input_ cluster for endpoint 01, but it's way easier to suppress the creation of the resource in deCONZ.

As a quick workaround, you can delete the resource from the `sensors` table in the deCONZ database (make sure to stop deCONZ first).  Deleting the resource through the API won't work.

**Comment by Idelean** [comment]
Hey there ! 

Thank you so much for the workaround offered and the reactivity. 

I am still looking after the cube's functionality in Homekit (experiencing HomeKit config issues) but in overall, after removing the third line on the data base, the issues with the service does not persist and I am able to use HomeBridge again. 

Thank you.
![screenshot 2018-11-18 at 14 58 39](https://user-images.githubusercontent.com/45125130/48796708-34ff6f00-ecf8-11e8-9d9f-3332fe515d9f.png)
