### ISSUE TITLE
Cannot find module 'es5-ext/object/assign'

### ISSUE THREAD

**Issue by microfx** [ebaauw/homebridge-hue#465]
Hey, 

getting this error when starting homebridge - any idea? I installed es5-ext additionally but still this error. The whole process is very confusing for me sadly.

homebridge 
[4/30/2019, 9:01:21 PM] config.json (/home/patch/.homebridge/config.json) not found.
[4/30/2019, 9:01:21 PM] Warning: skipping plugin found at '/usr/lib/node_modules/homebridge-hue' since we already loaded the same plugin from '/usr/local/lib/node_modules/homebridge-hue'.
[4/30/2019, 9:01:21 PM] ====================
[4/30/2019, 9:01:21 PM] ERROR LOADING PLUGIN homebridge-hue:
[4/30/2019, 9:01:21 PM] Error: Cannot find module 'es5-ext/object/assign'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/index.js:8:14)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
[4/30/2019, 9:01:21 PM] ====================
[4/30/2019, 9:01:21 PM] No plugins found. See the README for information on installing plugins.

**Comment by ebaauw** [comment]
> [4/30/2019, 9:01:21 PM] Warning: skipping plugin found at '/usr/lib/node_modules/homebridge-hue' since we already loaded the same plugin from '/usr/local/lib/node_modules/homebridge-hue'.

There’s something weird in your installation in that you seem to have homebridge-hue installed twice.  Probably because you installed different versions of NodeJS in a different way.  You might want to double check where you installed es5-ext.

> at Object. (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/index.js:8:14)

It seems to mess with the `deferred` package that homebridge-hue uses.

**Comment by ggzhangCN** [comment]
hey, have you ever fixed this bug? @microfx
