### ISSUE TITLE
Error after start

### ISSUE THREAD

**Issue by DocUltra** [ebaauw/homebridge-hue#484]
I got this error, after I started my docker

2/2019, 8:05:52 PM] ERROR LOADING PLUGIN homebridge-hue:                                                                                                                                                              
[6/12/2019, 8:05:52 PM] Error: Cannot find module 'homebridge-lib'                                                                                                                                                        
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)                                                                                                                                           
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)                                                                                                                                                      
    at Module.require (internal/modules/cjs/loader.js:690:17)                                                                                                                                                             
    at require (internal/modules/cjs/helpers.js:25:18)                                                                                                                                                                    
    at Object.<anonymous> (/homebridge/node_modules/homebridge-hue/lib/HuePlatform.js:22:23)                                                                                                                              
    at Module._compile (internal/modules/cjs/loader.js:776:30)                                                                                                                                                            
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)                                                                                                                                              
    at Module.load (internal/modules/cjs/loader.js:653:32)                                                                                                                                                                
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)                                                                                                                                                              
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by RienduPre** [comment]
I have the same issue

**Comment by ebaauw** [comment]
See https://github.com/ebaauw/homebridge-hue/releases
