### ISSUE TITLE
homebridge-hue does not recognized newest version of homebridge

### ISSUE THREAD

**Issue by blebbens** [ebaauw/homebridge-hue#488]
Hello,

Homebridge is not starting anymore:

`[2019-6-23 10:11:00] ERROR LOADING PLUGIN homebridge-hue:
[2019-6-23 10:11:00] Error: Plugin /usr/lib/node_modules/homebridge-hue requires a HomeBridge version of ^0.4.50 which does not satisfy the current HomeBridge version of 0.4.49. You may need to upgrade your installation of HomeBridge.
    at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:56:11)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:153:14)
    at Array.forEach (<anonymous>)
    at Server._loadPlugins (/usr/local/lib/node_modules/homebridge/lib/server.js:145:22)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:57:24)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:32:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)`

`[2019-6-23 10:11:00] ERROR LOADING PLUGIN homebridge-lib:
[2019-6-23 10:11:00] Error: Plugin /usr/lib/node_modules/homebridge-lib requires a HomeBridge version of ^0.4.50 which does not satisfy the current HomeBridge version of 0.4.49. You may need to upgrade your installation of HomeBridge.
    at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:56:11)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:153:14)
    at Array.forEach (<anonymous>)
    at Server._loadPlugins (/usr/local/lib/node_modules/homebridge/lib/server.js:145:22)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:57:24)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:32:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)`

`[2019-6-23 10:11:00] Error: The requested platform 'Hue' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:134:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)`

So, homebridge tells me "Got SIGTERM, shutting down Homebridge...".

I think, newest homebridge is already installed:
`/usr/bin/homebridge -> /usr/lib/node_modules/homebridge/bin/homebridge
+ homebridge@0.4.50
updated 1 package in 3.799s`

But, I noticed, the messages above are showing 2 different paths:
/usr/lib/ and /usr/local/lib

Why does homebridge-hue not recognize that newest version of homebridge is already installed and shuts down homebridge ?

**Comment by ebaauw** [comment]
Homebridge-hue doesn’t check what versions of homebridge are installed, it just receives the version from tye running homebridge.  Looks like you’re running an old version of homebridge from /usr/local/lib.

**Comment by blebbens** [comment]
That is what I quoted above, yes. But, as you can this above, 0.4.5 is installed... the newest version.
The quoted text shows, 0.4.5 is installed in /usr/lib... the error message of hue plugin is looking for homebridge at /usr/local/lib... which is different.

**Comment by ebaauw** [comment]
Again, homebridge-hue is _not_ looking for homebridge.  You're starting homebridge from /usr/local/lib, and that version fails to load homebridge-hue.
