### ISSUE TITLE
Attempting to register a platform which has already been registered

### ISSUE THREAD

**Issue by AndrejBodnar** [ebaauw/homebridge-hue#508]
[2019-8-4 10:43:59 PM] Loaded config.json with 0 accessories and 1 platforms.
[2019-8-4 10:43:59 PM] ---
[2019-8-4 10:44:02 PM] Loaded plugin: homebridge-homewizard-flamingo
[2019-8-4 10:44:02 PM] Registering platform 'homebridge-homewizard-lite.HomeWizard-Lite'
[2019-8-4 10:44:02 PM] ---
[2019-8-4 10:44:05 PM] Loaded plugin: homebridge-homewizard-lite
homebridge API version: 2.4
C:\Users\Erlaxxx\AppData\Roaming\npm\node_modules\homebridge\lib\api.js:150
    throw new Error("Attempting to register a platform '" + fullName + "' which has already been registered!");
    ^

Error: Attempting to register a platform 'homebridge-homewizard-lite.HomeWizard-Lite' which has already been registered!
    at API.registerPlatform (C:\Users\Erlaxxx\AppData\Roaming\npm\node_modules\homebridge\lib\api.js:150:11)
    at Plugin.module.exports [as initializer] (C:\Users\Erlaxxx\node_modules\homebridge-homewizard-lite\index.js:19:14)
    at Server.<anonymous> (C:\Users\Erlaxxx\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:171:14)
    at Array.forEach (<anonymous>)
    at Server._loadPlugins (C:\Users\Erlaxxx\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:145:22)
    at new Server (C:\Users\Erlaxxx\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:57:24)
    at module.exports (C:\Users\Erlaxxx\AppData\Roaming\npm\node_modules\homebridge\lib\cli.js:32:16)
    at Object.<anonymous> (C:\Users\Erlaxxx\AppData\Roaming\npm\node_modules\homebridge\bin\homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)

**Comment by AndrejBodnar** [comment]
can enybody solve this problem please?

**Comment by ebaauw** [comment]
This has nothing to do with homebridge-hue.

Look like there's a conflict between homebridge-homewizard-flamingo and homebridge-homewizard-lite: they both want to register with Homebridge under the same name.

**Comment by AndrejBodnar** [comment]
I need only flamingo. What is the solution? Delete the another one? Thanks
