### ISSUE TITLE
Cannot install homebridge-hue

### ISSUE THREAD

**Issue by Pilschat** [ebaauw/homebridge-hue#52]
I don't know what is the problem exactly, but i do see that the homebridge stops working when installing the homewizard-hue.

Homebridge did work, but never with hue. Normally i use homebridge-homewizard. But because after a while the homebridge cannot be seen on my iphone i wanted to find out what the problem could be. homebridge? homebridge-homewizard? 

So i did unnstall all plugins and only installed the homebridge-hue. But can't get it to work.
I have a version 1 philips bridge.

This is in the install:
npm install -g homebridge-hue
This in in the config:
{
    "bridge": {
        "name": "Homebridge is Working",
        "username": "CC:22:33:11:EE:88",
        "port": 51825,
        "pin": "012-34-567"
    },
    
  "platforms": [{
      "platform": "Hue",
      "name": "Hue"
    }

    ],

    "accessories": [

    ]
}

This is the log:
2017-01-19 10:09:16	stdout	    at Function.Module._load (module.js:424:3)
2017-01-18 20:09:16	stdout	    at tryModuleLoad (module.js:432:12)
2017-01-18 20:09:16	stdout	    at Module.load (module.js:473:32)
2017-01-18 20:09:16	stdout	    at Object.Module._extensions..js (module.js:565:10)
2017-01-18 20:09:16	stdout	    at Module._compile (module.js:556:32)
2017-01-18 20:09:16	stdout	    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
2017-01-18 20:09:16	stdout	    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
2017-01-18 20:09:16	stdout	    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:77:36)
2017-01-18 20:09:16	stdout	    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:281:45)
2017-01-18 20:09:16	stdout	    at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:118:13)
2017-01-18 20:09:16	stdout	Error: The requested platform 'Hue' was not registered by any plugin.
2017-01-18 20:09:16	stdout	
2017-01-18 20:09:16	stdout	      ^
2017-01-18 20:09:16	stdout	      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
2017-01-18 20:09:16	stdout	/usr/lib/node_modules/homebridge/lib/api.js:118
2017-01-18 20:09:16	stdout	[1/19/2017, 10:09:16 AM] Loading 1 platforms...
2017-01-18 20:09:16	stdout	[1/19/2017, 10:09:16 AM] ---
2017-01-18 20:09:16	stdout	[1/19/2017, 10:09:16 AM] Loaded config.json with 0 accessories and 1 platforms.
2017-01-18 20:09:16	stdout	[1/19/2017, 10:09:16 AM] [33mNo plugins found. See the README for information on installing plugins.[39m
2017-01-18 20:09:16	stdout	[1/19/2017, 10:09:16 AM] [1m[31m====================[39m[22m
2017-01-18 20:09:16	stdout	    at Module.load (module.js:473:32)[39m[22m
2017-01-18 20:09:16	stdout	    at Object.Module._extensions..js (module.js:565:10)
2017-01-18 20:09:16	stdout	    at Module._compile (module.js:556:32)
2017-01-18 20:09:16	stdout	    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
2017-01-18 20:09:16	stdout	    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:26:16)
2017-01-18 20:09:16	stdout	    at new Server (/usr/lib/node_modules/homebridge/lib/server.js:48:24)
2017-01-18 20:09:16	stdout	    at Server._loadPlugins (/usr/lib/node_modules/homebridge/lib/server.js:125:22)
2017-01-18 20:09:16	stdout	    at Array.forEach (native)
2017-01-18 20:09:16	stdout	    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:129:14)
2017-01-18 20:09:16	stdout	    at Plugin.load (/usr/lib/node_modules/homebridge/lib/plugin.js:56:11)
2017-01-18 20:09:16	stdout	[1/19/2017, 10:09:16 AM] [1m[31mError: Plugin /usr/lib/node_modules/homebridge-hue requires a HomeBridge version of ^0.4.16 which does not satisfy the current HomeBridge version of 0.4.6. You may need to upgrade your installation of HomeBridge.
2017-01-18 20:09:16	stdout	[1/19/2017, 10:09:16 AM] [1m[31mERROR LOADING PLUGIN homebridge-hue:[39m[22m
2017-01-18 20:09:16	stdout	[1/19/2017, 10:09:16 AM] [1m[31m====================[39m[22m
2017-01-18 20:09:15	stdout	*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
2017-01-18 20:09:15	stdout	*** WARNING *** Please fix your application to use the native API of Avahi!
2017-01-18 20:09:15	stdout	*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
2017-01-18 20:09:15	stdout	*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
2017-01-18 20:09:15	stdout	*** WARNING *** Please fix your application to use the native API of Avahi!
2017-01-18 20:09:15	stdout	*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
2017-01-18 20:09:14	stdout	Executing /root/.homebridge/install.sh.

**Comment by ebaauw** [comment]
> 2017-01-18 20:09:16	stdout	[1/19/2017, 10:09:16 AM] �[1m�[31mError: Plugin /usr/lib/node_modules/homebridge-hue requires a HomeBridge version of ^0.4.16 which does not satisfy the current HomeBridge version of 0.4.6. You may need to upgrade your installation of HomeBridge.

Try npm install -g homebridge to upgrade to the latest version.  Better check the version of nodejs while you're at it.

**Comment by Pilschat** [comment]
I installed Homebridge for the first time just 2 days ago, so i though i have the latest version.
But i Will try.

About nodejs, i have installed this All on my synology nas. I really have no idea where i can see or upgrade nodejs.

Any suggestions

Thanks

**Comment by ebaauw** [comment]
Not a clue, I'm afraid, as I don't have a Synology.  It looks like you're using a different install than mentioned in issue #38.  You might want to try that one.
