### ISSUE TITLE
deCONZ users

### ISSUE THREAD

**Issue by SSkull995** [ebaauw/homebridge-hue#540]
Hello! 
I would like to apologise for this issue, but I really cannot find a way to get the users ID out of my deCONZ. Can you help me please?

Last thing, I would like to have in the HomeKit app all the lights+accessories connected to deCONZ no matter the brand (Tradfri or Hue or else). Such a script should be fine? 

         {
      "platform": "Hue",
      "host": "127.0.0.1",
      "users": {
                "00212EFFFFxxxxxx": "xxxxxxxxxx"
      },
                "sensors": true,
                "lights": true,
                "nativeHomeKitLights":false,
                "nativeHomeKitSensors":false
        }
Note: I have both home bridge and deCONZ running on the same raspi 

Thanks for the help!

**Comment by SSkull995** [comment]
I got this message, trying to run homebridge after having installed the plugin:
[2019-10-7 12:59:29] ERROR LOADING PLUGIN homebridge-hue:
[2019-10-7 12:59:29] /usr/local/lib/node_modules/homebridge-hue/node_modules/ws/lib/websocket.js:347
      ...options
      ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-hue/node_modules/ws/index.js:3:19)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-hue/lib/HueBridge.js:19:19)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
[2019-10-7 12:59:29] ====================
..............
[2019-10-7 12:59:50] Error: The requested platform 'Hue' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:134:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

**Comment by ebaauw** [comment]
> I really cannot find a way to get the users ID out of my deCONZ

On the first startup, homebridge-hue will prompt you (in the log) to unlock the gateway (might actually not be needed if deCONZ and homebridge run on the same server).  It will then create a username and a message in the log what you need to put in config.json.

> Such a script should be fine?

The `NativeHomeKit...` settings are needed only for a gen-2 Hue bridge.  Setting `"sensors"` and `"lights"` to `true` should be enough.  You might want to filter out some CLIP sensors, depending on what app(s) you use to create deCONZ rules.

> [2019-10-7 12:59:29] /usr/local/lib/node_modules/homebridge-hue/node_modules/ws/lib/websocket.js:347
...options
^^^
SyntaxError: Unexpected token ...

I have no idea why this is happening here.  NodeJS seems to fail loading the `ws` module that homebridge-hue uses as a dependency.  What versions of `node` and `npm` are you on?  Are you sure you only have one installation of `node`?  Did you install homebridge and homebridge-hue in the same way (`sudo npm -g i ...`)?

**Comment by SSkull995** [comment]
Hi @ebaauw, thanks! So I managed to update my node (version 8 to version 10), because I kept trying via ws but nothing, now I have it decently made. 

For the ID, I put inside the user and password of my deCONZ gateway might it be fine?

For the son, I will modify it right away.

For the error, I noticed I have two npm but just one node, which kept failing updating. I am running homebridge right now, but I have a problem with a plugin that doesn't support node version higher than 10, amazing.

**Comment by SSkull995** [comment]
I will cancel everything and get a clean install of home bridge again, I am getting crazy. I will let you know, many thanks!

**Comment by SSkull995** [comment]
Hello! So I installed back everything, ffmpeg was a pain on h264 lib. So now everything works, but I get a connectionError from HUE (due to the IDs?). Thanks!

**Comment by ebaauw** [comment]
Unlock the gateway through the Phoscon or old web app, see https://github.com/ebaauw/homebridge-hue#installation

**Comment by SSkull995** [comment]
ok so I did that looking at another post that helped me. Now I have an issue in Homekit, the two accessories that start by themselves, so Daylight and Gateway, are shown as "incompatible". 
In the Homebridge log I get this:
"[Hue] Gateway: /sensors/1: warning: Daylight sensor not configured
[10/10/2019, 11:58:32 AM] [Hue] Gateway: error: /sensors/1: {"config":{"configured":false,"on":true,"sunriseoffset":30,"sunsetoffset":-30,"reachable":false},"etag":null,"manufacturername":"Philips","modelid":"PHDL00","name":"Daylight","state":{"dark":true,"daylight":null,"lastupdated":"none","status":null,"lightlevel":0},"swversion":"1.0","type":"Daylight","uniqueid":"00:21:2e:ff:ff:04:13:7e-01"}
 TypeError: Cannot read property 'period' of undefined
    at HueSensor.checkStatus (/usr/local/lib/node_modules/homebridge-hue/lib/HueSensor.js:1898:48)
    at new HueSensor (/usr/local/lib/node_modules/homebridge-hue/lib/HueSensor.js:1396:12)
    at HueAccessory.exposeSensorResource (/usr/local/lib/node_modules/homebridge-hue/lib/HueAccessory.js:297:20)
    at HueAccessory.exposeSensorResources (/usr/local/lib/node_modules/homebridge-hue/lib/HueAccessory.js:287:12)
    at HueAccessory.expose (/usr/local/lib/node_modules/homebridge-hue/lib/HueAccessory.js:123:8)
    at HueBridge.exposeResources (/usr/local/lib/node_modules/homebridge-hue/lib/HueBridge.js:515:49)
    at getConfig.then.then.then.then (/usr/local/lib/node_modules/homebridge-hue/lib/HueBridge.js:91:19)
    at Function.then (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/_ext.js:65:13)
    at Deferred._settle (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:93:26)
    at Deferred.resolve (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:138:15)
    at request.then (/usr/local/lib/node_modules/homebridge-hue/lib/HueBridge.js:305:11)
    at Function.then (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/_ext.js:65:13)
    at Deferred._settle (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:93:26)
    at Deferred.resolve (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:138:15)
    at Request.request [as _callback] (/usr/local/lib/node_modules/homebridge-hue/lib/HueBridge.js:1042:14)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-hue/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-hue/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-hue/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)" 


Further, I get the working to use the latest Deconz gateway version, but on my raspbee the newest version is already installed

**Comment by ebaauw** [comment]
The gateway accessory is needed by homebridge-hue.  You can change the heartrate and set transition time using a decent HomeKit app (like Eve).

You can prevent the Daylight sensor from being exposed using `excludeSensorTypes`, see https://github.com/ebaauw/homebridge-hue/wiki/Configuration.  If you expose it, it needs to be configured, by setting `config.lat` and `config.long` through the API.  Normally Phoscon would do this automatically.  Normally it’s exposed as a light sensor and supported by Apple’s Home app, but because of the TypeError it isn’t.  Looks like homebridge-hue isn’t handling the unconfigured sensor correctly...

What deCONZ version do you have installed and what version does homebridge-hue want?  What machine are you running deCONZ on?

**Comment by SSkull995** [comment]
Hi so I just successfully paired an IKEA switch to my Deconz, via the phoscon app, but it doesn’t appear on my HomeKit. The deCONZ gateway runs the latest rpi version, and on HomeKit it is stated “not supported” under the bridge icon. Might this help for the resolution of the problem? Thanks!

**Comment by ebaauw** [comment]
Did you restart homebridge after pairing the switch?  Note that you need a Home hub for the switch to work in HomeKit.

**Comment by SSkull995** [comment]
I got it working but I forgot to answer. I restarted homebridge and everything is fine now! For the lights, I have two of them but I cannot pair them, probably because I am trying to do the pairing when my bridge is in the living room and the light in the bedroom.  Should they be close (light+bulb)

Kind regards,
Giovanni

**Comment by ebaauw** [comment]
Regular pairing should work within 10m line-of-sight to the nearest router, but ceilings, walls, or metal luminairies might limit the reachability.  Make sure to reset the lights, open the network, and then power cycle the lights.

**Comment by SSkull995** [comment]
perfect! Thanks!
