### ISSUE TITLE
Bridge communication error

### ISSUE THREAD

**Issue by recom273** [ebaauw/homebridge-hue#542]
#### Issue

After multiple re-installs of DE's Deconz/Homebridge/Hue image im finally getting somewhere with my Raspbee shield.

However, when I fire up homebridge im greeted with this message.

I can access the shield through phoscon - I can add sensors - I can see the map being created in DeConz.

How can I complete this install?

I have been running homebridge for two years, but pulling my hair out for the past 6 months with this device, I would happily pay someone to set it up if anyone wants a little job? 
#### Log Messages

```
pi@phoscon:~ $ homebridge
[10/11/2019, 9:17:51 AM] Loaded config.json with 0 accessories and 1 platforms.
[10/11/2019, 9:17:51 AM] ---
[10/11/2019, 9:17:51 AM] Plugin /usr/lib/node_modules/homebridge-lib package.json does not contain the keyword 'homebridge-plugin'.
[10/11/2019, 9:17:54 AM] Loaded plugin: homebridge-hue
[10/11/2019, 9:17:54 AM] Registering platform 'homebridge-hue.Hue'
[10/11/2019, 9:17:54 AM] ---
[10/11/2019, 9:17:54 AM] Loading 1 platforms...
[10/11/2019, 9:17:54 AM] [Hue] Initializing Hue platform...
[10/11/2019, 9:17:54 AM] [Hue] homebridge-hue v0.11.37, node v10.16.3, homebridge v0.4.50
[10/11/2019, 9:17:55 AM] [Hue] warning: latest version: homebridge-hue v0.11.41
[10/11/2019, 9:17:55 AM] [Hue] 127.0.0.1: bridge request 1: get /config
[10/11/2019, 9:17:55 AM] [Hue] 127.0.0.1: bridge communication error ECONNREFUSED on 127.0.0.1
[10/11/2019, 9:18:10 AM] [Hue] 127.0.0.1: bridge request 2: get /config
[10/11/2019, 9:18:10 AM] [Hue] 127.0.0.1: bridge communication error ECONNREFUSED on 127.0.0.1
[10/11/2019, 10:01:11 AM] [Hue] 127.0.0.1: bridge request 3: get /config
[10/11/2019, 10:01:11 AM] [Hue] 127.0.0.1: bridge communication error ECONNREFUSED on 127.0.0.1
[10/11/2019, 10:01:26 AM] [Hue] 127.0.0.1: bridge request 4: get /config
[10/11/2019, 10:01:26 AM] [Hue] 127.0.0.1: bridge communication error ECONNREFUSED on 127.0.0.1
[10/11/2019, 10:01:41 AM] [Hue] 127.0.0.1: bridge request 5: get /config
[10/11/2019, 10:01:41 AM] [Hue] 127.0.0.1: bridge communication error ECONNREFUSED on 127.0.0.1
[10/11/2019, 10:01:56 AM] [Hue] 127.0.0.1: bridge request 6: get /config
[10/11/2019, 10:01:56 AM] [Hue] 127.0.0.1: bridge communication error ECONNREFUSED on 127.0.0.1
[10/11/2019, 10:02:11 AM] [Hue] 127.0.0.1: bridge request 7: get /config
[10/11/2019, 10:02:11 AM] [Hue] 127.0.0.1: bridge communication error ECONNREFUSED on 127.0.0.1
[10/11/2019, 10:02:26 AM] [Hue] 127.0.0.1: bridge request 8: get /config
[10/11/2019, 10:02:26 AM] [Hue] 127.0.0.1: bridge communication error ECONNREFUSED on 127.0.0.1
```

**Comment by ebaauw** [comment]
What port do you run deCONZ on?  If other than 80, you need to set `host` to `"127.0.0.1:`_port_`"`.

**Comment by recom273** [comment]
Where can I set or check the port?

/etc/config?

**Comment by ebaauw** [comment]
Best start Phoscon or the old web app and check the port in the browser address bar.  Otherwise check how you start deCONZ; typically the port is passed as a command-line parameter.

Alternatively, you could try the debug tools included in homebridge-hue: `ph discover -v` or `upnp`.

**Comment by recom273** [comment]
Ah, while looking for the port number I found a 'reset homebridge' button. This was the button I was looking for all along. 

Sorry.

This obviously reset homebridge and linked it to the shield

But I still haven't received the QR code that I would get on a successful launch - instead this error.

`pi@phoscon:~ $ homebridge
[10/11/2019, 2:12:41 PM] Loaded config.json with 0 accessories and 1 platforms.
[10/11/2019, 2:12:41 PM] ---
[10/11/2019, 2:12:41 PM] Plugin /usr/lib/node_modules/homebridge-lib package.json does not contain the keyword 'homebridge-plugin'.
[10/11/2019, 2:12:45 PM] Loaded plugin: homebridge-hue
[10/11/2019, 2:12:45 PM] Registering platform 'homebridge-hue.Hue'
[10/11/2019, 2:12:45 PM] ---
[10/11/2019, 2:12:45 PM] Loading 1 platforms...
[10/11/2019, 2:12:45 PM] [Hue] Initializing Hue platform...
[10/11/2019, 2:12:45 PM] [Hue] homebridge-hue v0.11.37, node v10.16.3, homebridge v0.4.50
[10/11/2019, 2:12:45 PM] [Hue] warning: latest version: homebridge-hue v0.11.41
[10/11/2019, 2:12:45 PM] [Hue] Phoscon-GW: dresden elektronik deCONZ gateway v2.5.69, api v1.16.0
[10/11/2019, 2:12:45 PM] [Hue] Phoscon-GW: warning: not using recommended deCONZ gateway version 2.5.67
[10/11/2019, 2:12:46 PM] [Hue] Phoscon-GW: 2 accessories
[10/11/2019, 2:12:46 PM] [Hue] masked debug info dumped to /home/pi/.homebridge/homebridge-hue.json.gz
[10/11/2019, 2:12:46 PM] [Hue] Initializing platform accessory 'Phoscon-GW'...
[10/11/2019, 2:12:46 PM] [Hue] Phoscon-GW: 3 services
[10/11/2019, 2:12:46 PM] [Hue] Initializing platform accessory 'Motion Sensor'...
[10/11/2019, 2:12:46 PM] [Hue] { Error: EACCES: permission denied, open '/home/pi/.homebridge/persist/AccessoryInfo.2EFFFF0405B1.json'
    at Object.openSync (fs.js:443:3)
    at Object.writeFileSync (fs.js:1194:35)
    at LocalStorage.persistKeySync (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/local-storage.js:476:16)
    at LocalStorage.setItemSync (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/local-storage.js:277:14)
    at Object.nodePersist.setItemSync (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/node-persist.js:99:29)
    at AccessoryInfo.save (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/model/AccessoryInfo.js:163:11)
    at Bridge.Accessory.publish (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:552:23)
    at Server._publish (/usr/lib/node_modules/homebridge/lib/server.js:132:16)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:421:14)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path:
   '/home/pi/.homebridge/persist/AccessoryInfo.2EFFFF0405B1.json' }
[10/11/2019, 2:12:48 PM] [Hue] Motion Sensor: set homekit light level from 51.9996 lux to 50.9918 lux
[10/11/2019, 2:14:45 PM] [Hue] Motion Sensor: set homekit motion from 1 to 0
[10/11/2019, 2:14:51 PM] [Hue] Motion Sensor: set homekit light level from 50.9918 lux to 51.9996 lux
[10/11/2019, 2:14:51 PM] [Hue] Motion Sensor: set homekit motion from 0 to 1
[10/11/2019, 2:14:56 PM] [Hue] Motion Sensor: set homekit light level from 51.9996 lux to 49.9919 lux
[10/11/2019, 2:15:01 PM] [Hue] Motion Sensor: set homekit light level from 49.9919 lux to 32.9989 lux`

When I checked the address bar of the browser, I didn't see a port number, as I would expect to see in any other browser based interface, what am I missing here?

This was from the old app
`192.168.0.118/edit_system.html?v=2.05.69`

`{
  "deconz4": {},
  "deconz6": {},
  "meethue": {},
  "meethueOld": {},
  "upnp": {
    "192.168.0.118": "00212EFFFF0405B1"
  }
}`

Thanks so much for your time. I am amazed that now I can see a sensor that I added to phoscon.

**Comment by ebaauw** [comment]
The EACCES error is not good, but it's not caused by homebridge-hue.  I think you previously ran homebridge as `root` (using `sudo` or as a service without specifying a user) and now as user `pi`.  The user running homebridge needs permissions to read and write the files in `~/.homebridge/persist` and in `~/.homebridge/accessories`.

**Comment by recom273** [comment]
Thanks

No. I had issues with installing deconz and then installing homebridge and visa versa .. they would always negate each other’s installation. 

So I used a pre-configured image from the Dresden electronik, now I can see how phoscon operates in hand with homebridge I will try a fresh install. 

I will post the issue to ‘homebridge’ and see if I can find a solution there, thanks again!
