### ISSUE TITLE
[Hue] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory

### ISSUE THREAD

**Issue by bubffm** [ebaauw/homebridge-hue#559]
I have upgrded to node 12.13.0 which went thru just fine., however I now get an error towards the end of the log wenn homebridge-hue has listed all the accessories as follows:

`[11/8/2019, 23:59:01] [Hue] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 4dbf54e4-c8d5-4d39-b4bd-8d3b87acbfde
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:268:13)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:416:24)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
    at /usr/local/lib/node_modules/homebridge-hue/lib/HuePlatform.js:282:5
    at Function.then (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/_ext.js:65:13)
    at Deferred._settle (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:93:26)
    at Deferred.resolve (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:138:15)
    at Function.<anonymous> (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/ext/promise/catch.js:29:4)
    at Deferred._settle (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:93:26)
    at Deferred.resolve (/usr/local/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:138:15)`

I deleted the accessories folder, rebooted the raspi, restarted homebridge a few times. Nothing seems to help. I'd appreciate any hints.

**Comment by ebaauw** [comment]
Please attach the full logfile, and, if homebridge-hue already created it, the debug dump file.  See https://github.com/ebaauw/homebridge-hue#debug-log-file and https://github.com/ebaauw/homebridge-hue#debug-dump-file.

**Comment by bubffm** [comment]
This morning after another reboot, the Error msg disappeared just as mystically as it showed up...
I had this before whenever I ran updates or backups and had to reboot homebridge.  In the past instances, the error disappeared swiftly after 30mins or so, yesterday evening it was ver persistant.

If I get this again, I'll send you the dump files. I assume they would be overwritten now after the reboot?

**Comment by ebaauw** [comment]
> I assume they would be overwritten now after the reboot?

Yes.

> [Hue] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 4dbf54e4-c8d5-4d39-b4bd-8d3b87acbfde at Bridge.Accessory.addBridgedAccessory 

Basically, this error means that homebridge-hue tries to expose two accessories through homebridge with the same UUID.  As homebridge-hue still uses the (old) static accessories model, clearing `~/.homebridge/accessories/cachedAccessories` won't do anything.  homebridge-hue bases the UUID on the ZigBee mac address, for ZigBee devices, and on the bridge id and resource id for non-ZigBee objects (groups, CLIP sensors, multi-light resources).

Afaik, this cannot lead to duplicate UUIDs.  The only scenario I know of, is when you have multiple bridges and/or gateways, and move a ZigBee device from one gateway to another, without deleting the resource on the old gateway.

**Comment by bubffm** [comment]
mm, I really only have one Raspbee modul from Dresden which exposes my Zigbee accessories. No idea...  I keep observing this one. Many thanks for having a look.

**Comment by bubffm** [comment]
I have the same issue again after a short power cut ove rhere.    Attached the 
[homebridge.log.zip](https://github.com/ebaauw/homebridge-hue/files/3830804/homebridge.log.zip)

I cant find the debug-dump-file in the homebridge directory.....

**Comment by ebaauw** [comment]
> I cant find the debug-dump-file in the homebridge directory.....

See the log:
```
Nov 11 11:09:54 raspberrypi homebridge[3055]: [11/11/2019, 11:09:54] [Hue] masked debug info dumped to /var/homebridge/homebridge-hue.json.gz
```
If it isn't there, double-check the permissions for the directory.  It should be writeable by the user running homebridge.

Homebridge-hue seems to find the deCONZ gateway twice; the error occurs when exposing the gateway for the second time:
```
Nov 11 11:09:53 raspberrypi homebridge[3055]: [11/11/2019, 11:09:53] [Hue] RaspBee: dresden elektronik deCONZ gateway v2.5.67, api v1.16.0
Nov 11 11:09:53 raspberrypi homebridge[3055]: [11/11/2019, 11:09:53] [Hue] RaspBee: warning: not using recommended deCONZ gateway version 2.5.70
Nov 11 11:09:53 raspberrypi homebridge[3055]: [11/11/2019, 11:09:53] [Hue] RaspBee: dresden elektronik deCONZ gateway v2.5.67, api v1.16.0
Nov 11 11:09:53 raspberrypi homebridge[3055]: [11/11/2019, 11:09:53] [Hue] RaspBee: warning: not using recommended deCONZ gateway version 2.5.70
Nov 11 11:09:54 raspberrypi homebridge[3055]: [11/11/2019, 11:09:54] [Hue] RaspBee: 16 accessories
Nov 11 11:09:54 raspberrypi homebridge[3055]: [11/11/2019, 11:09:54] [Hue] RaspBee: 16 accessories
Nov 11 11:09:54 raspberrypi homebridge[3055]: [11/11/2019, 11:09:54] [Hue] masked debug info dumped to /var/homebridge/homebridge-hue.json.gz
Nov 11 11:09:54 raspberrypi homebridge[3055]: [11/11/2019, 11:09:54] [Hue] Initializing platform accessory 'RaspBee'...
Nov 11 11:09:54 raspberrypi homebridge[3055]: [11/11/2019, 11:09:54] [Hue] RaspBee: 2 services
Nov 11 11:09:54 raspberrypi homebridge[3055]: [11/11/2019, 11:09:54] [Hue] Initializing platform accessory 'Außenleuchte'...
Nov 11 11:09:54 raspberrypi homebridge[3055]: [11/11/2019, 11:09:54] [Hue] Initializing platform accessory 'Innr2'...
Nov 11 11:09:54 raspberrypi homebridge[3055]: [11/11/2019, 11:09:54] [Hue] Initializing platform accessory 'Innr Steckdose'...
Nov 11 11:09:54 raspberrypi homebridge[3055]: [11/11/2019, 11:09:54] [Hue] Initializing platform accessory 'Innr3'...
Nov 11 11:09:54 raspberrypi homebridge[3055]: [11/11/2019, 11:09:54] [Hue] Initializing platform accessory 'Bodenleuchte'...
Nov 11 11:09:54 raspberrypi homebridge[3055]: [11/11/2019, 11:09:54] [Hue] Initializing platform accessory 'Fenster Gäste-WC'...
Nov 11 11:09:54 raspberrypi homebridge[3055]: [11/11/2019, 11:09:54] [Hue] Initializing platform accessory 'Gäste-WC'...
Nov 11 11:09:54 raspberrypi homebridge[3055]: [11/11/2019, 11:09:54] [Hue] Initializing platform accessory 'Schalter 1'...
Nov 11 11:09:54 raspberrypi homebridge[3055]: [11/11/2019, 11:09:54] [Hue] Initializing platform accessory 'Bewegung'...
Nov 11 11:09:54 raspberrypi homebridge[3055]: [11/11/2019, 11:09:54] [Hue] Initializing platform accessory 'Eisschrank'...
Nov 11 11:09:54 raspberrypi homebridge[3055]: [11/11/2019, 11:09:54] [Hue] Initializing platform accessory 'Seitenfenster'...
Nov 11 11:09:54 raspberrypi homebridge[3055]: [11/11/2019, 11:09:54] [Hue] Initializing platform accessory 'Kühlschrank'...
Nov 11 11:09:54 raspberrypi homebridge[3055]: [11/11/2019, 11:09:54] [Hue] Initializing platform accessory 'Terrassentür'...
Nov 11 11:09:54 raspberrypi homebridge[3055]: [11/11/2019, 11:09:54] [Hue] Initializing platform accessory 'Esstischfenster'...
Nov 11 11:09:54 raspberrypi homebridge[3055]: [11/11/2019, 11:09:54] [Hue] Initializing platform accessory 'Terrassentür SZ'...
Nov 11 11:09:54 raspberrypi homebridge[3055]: [11/11/2019, 11:09:54] [Hue] Initializing platform accessory 'RaspBee'...
Nov 11 11:09:54 raspberrypi homebridge[3055]: [11/11/2019, 11:09:54] [Hue] RaspBee: 2 services
Nov 11 11:09:54 raspberrypi homebridge[3055]: [11/11/2019, 11:09:54] [Hue] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 4dbf54e4-c8d5-4d39-b4bd-8d3b87acbfde
```
I haven't seen this before.  Did you specify the gateway twice in config.json?

**Comment by bubffm** [comment]
Not as far as I can tell. This is the relevant part of config:

`
{
            "platform": "Hue",
            "users": {
                "00xxxxxxxxxx3CD25": "5xxxxxxxx14"
            },
            "sensors": true,
            "excludeSensorTypes": [
                "ZHAHumidity",
                "ZHAPressure",
                "ZHAPower",
                "ZHAConsumption",
                "Daylight"
            ],
            "lights": true
        },
`

**Comment by ebaauw** [comment]
What’s the output of `ph discover -v`?

**Comment by bubffm** [comment]
This is what I get:

`{
  "deconz4": {},
  "deconz4Old": {},
  "deconz6Old": {},
  "meethue": {},
  "meethueOld": {},
  "upnp": {
    "192.168.2.41": "00212EFFFF03CD25"
  }
}
`

**Comment by ebaauw** [comment]
I don't know what's causing this.  I really need the log file when running `homebridge -D` and the dump file to analyse.

**Comment by bubffm** [comment]
OK, looked again and finally found that dump file

[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/3835739/homebridge-hue.json.gz)

And here the homebridge -D  output:

`[11/12/2019, 11:57:23] config.json (/home/pi/.homebridge/config.json) not found.
[11/12/2019, 11:57:23] Plugin /usr/local/lib/node_modules/homebridge-lib package.json does not contain the keyword 'homebridge-plugin'.
[11/12/2019, 11:57:23] Loaded plugin: homebridge-automation-switches
[11/12/2019, 11:57:23] Registering platform 'homebridge-switches.AutomationSwitches'
[11/12/2019, 11:57:23] ---
[11/12/2019, 11:57:23] Loaded plugin: homebridge-cmdtrigger
[11/12/2019, 11:57:23] Registering accessory 'homebridge-cmdtrigger.CmdTrigger'
[11/12/2019, 11:57:23] ---
[11/12/2019, 11:57:23] Loaded plugin: homebridge-config-ui-x
[11/12/2019, 11:57:23] Registering platform 'homebridge-config-ui-x.config'
[11/12/2019, 11:57:23] ---
[11/12/2019, 11:57:23] Plugin /usr/local/lib/node_modules/homebridge-fritz-platform requires Node version of ^10.15.3 which does not satisfy the current Node version of v12.13.0. You may need to upgrade your installation of Node.
[11/12/2019, 11:57:23] Loaded plugin: homebridge-fritz-platform
[11/12/2019, 11:57:24] Registering platform 'homebridge-fritz-platform.FritzPlatform'
[11/12/2019, 11:57:24] ---
[11/12/2019, 11:57:26] Loaded plugin: homebridge-hue
[11/12/2019, 11:57:26] Registering platform 'homebridge-hue.Hue'
[11/12/2019, 11:57:26] ---
[11/12/2019, 11:57:26] Loaded plugin: homebridge-people
[11/12/2019, 11:57:26] Registering platform 'homebridge-people.People'
[11/12/2019, 11:57:26] Registering accessory 'homebridge-people.PeopleAccessory'
[11/12/2019, 11:57:26] Registering accessory 'homebridge-people.PeopleAllAccessory'
[11/12/2019, 11:57:26] ---
[11/12/2019, 11:57:27] Loaded plugin: homebridge-synology
[11/12/2019, 11:57:27] Registering accessory 'homebridge-synology.Synology'
[11/12/2019, 11:57:27] ---
[11/12/2019, 11:57:27] Loaded plugin: homebridge-telegram
[11/12/2019, 11:57:27] Registering platform 'homebridge-telegram.Telegram'
[11/12/2019, 11:57:27] ---
[11/12/2019, 11:57:28] Loaded plugin: homebridge-weather-plus
[11/12/2019, 11:57:29] Registering platform 'homebridge-weather-plus.WeatherPlus'
[11/12/2019, 11:57:29] ---
[11/12/2019, 11:57:30] Loaded plugin: homebridge-zway
[11/12/2019, 11:57:30] Registering accessory 'homebridge-zway.ZWayServer'
[11/12/2019, 11:57:30] Registering platform 'homebridge-zway.ZWayServer'
[11/12/2019, 11:57:30] ---
Load homebridge-switches.AutomationSwitches
[11/12/2019, 11:57:30] [homebridge-switches.AutomationSwitches] AutomationSwitchesPlatform Plugin Loaded - Version 3.2.1
Load homebridge-fritz-platform.FritzPlatform
Load homebridge-telegram.Telegram
[11/12/2019, 11:57:30] [homebridge-telegram.Telegram] TelegramPlatform Plugin Loaded
Setup Payload:
X-HM://0023ISYWY03JM
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:

                   
[11/12/2019, 11:57:30] Homebridge is running on port 34745.
[11/12/2019, 11:57:31] Error: Service name is already in use on the network
    at Registry._onProbeComplete (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Registry.js:106:27)
    at Prober.done (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Prober.js:67:10)
    at Prober.onMDNSresponse (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Prober.js:61:102)
    at EventEmitter.emit (events.js:210:5)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/multicast-dns/index.js:49:43)
    at Socket.emit (events.js:210:5)
    at UDP.onMessage [as onmessage] (dgram.js:861:8)
[11/12/2019, 11:57:31] Got SIGTERM, shutting down Homebridge...`

**Comment by ebaauw** [comment]
> [11/12/2019, 11:57:31] Error: Service name is already in use on the network

Looks like you're trying to start homebridge twice?

> I looked again and finally found that dump file

The dump looks normal: only one gateway found.

**Comment by bubffm** [comment]
Sorry, I think I had homebridge still running thru the ui-x interface....

As its currently running ok, I will probably have to wait for the next issue and send you the dumb file then.

**Comment by bdya** [comment]
Всем привет. У меня была подобная ошибка.

`[11/15/2019, 18:55:11] [Hue] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 33f3879b-9a17-4954-b20b-7179e3982ad9
    at Bridge.Accessory.addBridgedAccessory (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:268:13)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:416:24)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
    at /usr/lib/node_modules/homebridge-hue/lib/HuePlatform.js:282:5
    at Function.then (/usr/lib/node_modules/homebridge-hue/node_modules/deferred/_ext.js:65:13)
    at Deferred._settle (/usr/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:93:26)
    at Deferred.resolve (/usr/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:138:15)
    at Function.<anonymous> (/usr/lib/node_modules/homebridge-hue/node_modules/deferred/ext/promise/catch.js:29:4)
    at Deferred._settle (/usr/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:93:26)
    at Deferred.resolve (/usr/lib/node_modules/homebridge-hue/node_modules/deferred/deferred.js:138:15)`

Мой ConBee II имел одинаковое название с homebridge. После того как я переименовал ConBee все заработало. Надеюсь это поможет кому-то.

**Comment by bubffm** [comment]
I am getting the above infamous error message again.

I hope I ctched it this time in the attacvhed log:
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/3886991/homebridge-hue.json.gz)

**Comment by bubffm** [comment]
It happened again. I posted log.

Burkhard

Am Fr., 22. Nov. 2019 um 01:25 Uhr schrieb Erik Baauw <
notifications@github.com>:

**Comment by ebaauw** [comment]
Both gateways expose the same Xioami vibration sensor:  `/sensors/23`, Bewegung, on RaspBee and `/sensors/12`, Schlüsselbox, on KellerBee.  homebridge-hue bases the accessory UUID on the ZigBee mac address, so indeed, it tries to expose the same accessory UUID twice.

Looking at `lastupdated`, both gateways recently received data from the sensor.  Did you just reset it and pair it to KellBee, without removing it from RaspBee?

**Comment by bubffm** [comment]
i deleted it from RaspBee but it semes to have taken ages ti recignize that
it has been removed form one...

omebridge then started. But now I am getting a different Error with a THIRD
Phoscon Gateway showing up on an IP that is not part of my usual IP setup
atz all (192.168.1.112)... Now homebridge does not start because of this
"phantom" gateway.

Am Mo., 25. Nov. 2019 um 22:35 Uhr schrieb Erik Baauw <
notifications@github.com>:

**Comment by ebaauw** [comment]
> i deleted the double sensor from RaspBee yesterday but it seems to have taken ages to recognize that it has been removed from that one...

Make sure to delete it thru the REST API, so the resource gets deleted.   Just deleting the node in the GUI will leave the resource.

> But now I am getting a different Error with a THIRD Phoscon Gateway showing up on an IP that is not part of my usual IP setup at all (192.168.1.112)

Your ISP is sharing “your” public IP address with others, causing the Hue bridge discovery to find your (Internet) neighbour’s bridge.

> Can I restrict the search to predefined IP's

Setting `hosts` in config.json disables the search altogether, see https://github.com/ebaauw/homebridge-hue/wiki/Configuration.

**Comment by bubffm** [comment]
`Setting hosts in config.json disables the search altogether, see `https://github.com/ebaauw/homebridge-hue/wiki/Configuration.`

This saved me. Many thanks!   I will remember deleting resources via API the next time. For now, its no longer causing issues.
