### ISSUE TITLE
Error on dockerized Homebridge

### ISSUE THREAD

**Issue by henkhb** [ebaauw/homebridge-hue#625]
The new version is not working on my docker version of Homebridge (Synology).
Going back to last version solves the issue.

[2/20/2020, 10:21:49 PM] Error: The requested platform 'Hue' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:134:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)

**Comment by thumax** [comment]
Please check you log for "ERROR LOADING PLUGIN …"

This might be the same as #624.

**Comment by ebaauw** [comment]
Probably the same issue.  Could you try v0.11.55?

**Comment by henkhb** [comment]
Fixed. Thanks.
