### ISSUE TITLE
Sudden issue: events.once not a function

### ISSUE THREAD

**Issue by zeve-zz** [ebaauw/homebridge-hue#626]
Using: homebridge-hue v0.11.55
Via: homebridge-config-ui-x
firmware: 1935144040

No changes to my configuration in months..
Suddenly home bridge was failing, took a look at the logs and this is what I'm seeing relevant to Hue (other plugins working)

[2/20/2020, 10:41:44 PM] [Hue] npm registry: events.once is not a function
[2/20/2020, 10:41:44 PM] [Hue] searching bridges and gateways
[2/20/2020, 10:41:44 PM] [Hue] events.once is not a function
[2/20/2020, 10:41:44 PM] [Hue] TypeError: (intermediate value) is not iterable
    at HuePlatform.accessories (/homebridge/node_modules/homebridge-hue/lib/HuePlatform.js:303:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

-----

hue section of config:

        {
            "name": "Hue",
            "users": {
                "x": "x"
            },
            "excludeSensorTypes": [
                "Daylight",
                "CLIP",
                "Geofence",
                "ZLLPresence",
                "ZLLLightLevel",
                "ZLLTemperature",
                "ZLLSwitch"
            ],
            "lights": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "nupnp": true,
            "resource": true,
            "sensors": true,
            "platform": "Hue"
        },

**Comment by ebaauw** [comment]
You're running an old version of node, which doesn't support `events.once()`.

**Comment by zeve-zz** [comment]
what version of this plugin started using events.once?

I fear if I update my node my whole pi is going to become completely
unreliable.

**Comment by ebaauw** [comment]
v0.11.55, published today.  I develop and test against the latest LTS version of node, see https://nodejs.org/en/about/releases.  I would strongly recommend to keep node current, because of the security patches.

According to the documentation, `events.once()` was introduced v11.13.0 and v10.16.0, see https://nodejs.org/dist/latest-v12.x/docs/api/events.html#events_events_once_emitter_name.

**Comment by zeve-zz** [comment]
I updated node
node -v and nodejs -v returns 13.9.0

still seeing this in log

[2/20/2020, 11:09:17 PM] [Hue] npm registry: events.once is not a function
[2/20/2020, 11:09:17 PM] [Hue] searching bridges and gateways
[2/20/2020, 11:09:17 PM] [Hue] events.once is not a function
[2/20/2020, 11:09:17 PM] [Hue] TypeError: (intermediate value) is not iterable
    at HuePlatform.accessories (/homebridge/node_modules/homebridge-hue/lib/HuePlatform.js:303:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
[2/20/2020, 11:09:17 PM] [cmdSwitch2] Amazon Camera is off.
:393) [DEP0025] DeprecationWarning: sys is deprecated. Use util instead.
[2/20/2020, 11:09:17 PM] [Hue] npm registry: events.once is not a function
[2/20/2020, 11:09:17 PM] [Hue] searching bridges and gateways
[2/20/2020, 11:09:17 PM] [Hue] events.once is not a function
[2/20/2020, 11:09:17 PM] [Hue] TypeError: (intermediate value) is not iterable
    at HuePlatform.accessories (/homebridge/node_modules/homebridge-hue/lib/HuePlatform.js:303:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

**Comment by ebaauw** [comment]
Is that the version you use to run homebridge?  What does the line in the log with the homebridge-hue, node, and homebridge versions look like?

```
[Hue] homebridge-hue v0.11.55, node v12.16.1, homebridge v0.4.50
```

**Comment by zeve-zz** [comment]
[2/20/2020, 10:55:20 PM] [Hue] homebridge-hue v0.11.55, node v10.15.3, homebridge v0.4.50

any idea where I set where node is used for home bridge?

**Comment by ebaauw** [comment]
No.  That really depends on how you installed node, npm, and homebridge.

**Comment by iRonin** [comment]
Nodejs version is frequently an issue after HUE plugin update :( 
I just hit upgrade and run into the same issue…
