### ISSUE TITLE
Trådfri Bulbs Gone.

### ISSUE THREAD

**Issue by Bogdis** [ebaauw/homebridge-hue#643]
Hello,
Just upgraded to latest version and all my ikea trådfri bulbs disappeared :( 

This is the error i get in homebridge any help is appreciated 

[2020-3-1 18:39:42] [Hue] npm registry: "listener" argument must be a function
[2020-3-1 18:39:42] [Hue] searching bridges and gateways
[2020-3-1 18:39:42] [Hue] events.once is not a function
[2020-3-1 18:39:42] [Hue] TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at HuePlatform.accessories (/usr/lib/node_modules/homebridge-hue/lib/HuePlatform.js:336:1)
    at <anonymous>
    at runMicrotasksCallback (internal/process/next_tick.js:122:5)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
    at Function.Module.runMain (module.js:696:11)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

**Comment by Bogdis** [comment]
Fixed by updating node.js
