### ISSUE TITLE
Conflict between Homebridge-Wink (and Wink3) vs Homebridge-hue

### ISSUE THREAD

**Issue by jmaugerdumais** [ebaauw/homebridge-hue#658]
#### Issue
Hello ! 
Since a few days, I have a conflict between whatever Wink plugin I'm using and Homebridge-hue.

Here's the log message below. Let me know if I can do something else.

Thanks !
#### Log Messages

```
[2020-3-14 13:34:17] [Hue] Philips hue 2.0: bridge request 1: get /
[2020-3-14 13:34:17] [Hue] Philips hue 2.0: bridge communication error: TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function. Received an instance of Object
    at checkListener (events.js:109:11)
    at ClientRequest.once (events.js:431:3)
    at new ClientRequest (_http_client.js:194:10)
    at Object.request (https.js:314:10)
    at Object.<anonymous> (C:\Users\julie\AppData\Roaming\npm\node_modules\homebridge-wink-schmittx\node_modules\agent-base\patch-core.js:25:22)
    at Object.request (C:\Users\julie\AppData\Roaming\npm\node_modules\homebridge-wink-schmittx\node_modules\socks-proxy-agent\node_modules\agent-base\patch-core.js:23:20)
    at HttpClient.request (C:\Users\julie\AppData\Roaming\npm\node_modules\homebridge-hue\node_modules\homebridge-lib\lib\HttpClient.js:226:32)
    at HueClient._request (C:\Users\julie\AppData\Roaming\npm\node_modules\homebridge-hue\lib\HueClient.js:351:41)
    at HueBridge.request (C:\Users\julie\AppData\Roaming\npm\node_modules\homebridge-hue\lib\HueBridge.js:1109:43)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async HueBridge.getFullState (C:\Users\julie\AppData\Roaming\npm\node_modules\homebridge-hue\lib\HueBridge.js:316:17)
    at async HueBridge.accessories (C:\Users\julie\AppData\Roaming\npm\node_modules\homebridge-hue\lib\HueBridge.js:93:19)
    at async Promise.all (index 0)
    at async HuePlatform.accessories (C:\Users\julie\AppData\Roaming\npm\node_modules\homebridge-hue\lib\HuePlatform.js:310:29)
```

**Comment by ebaauw** [comment]
See #652.
