### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]

### ISSUE THREAD

**Issue by monza258** [ebaauw/homebridge-hue#660]
Hey, I have created a new instanz with Hue Plugin to use it with deCONZ and Raspbee. I get some errors in hue log. 

I can't find any problems. Is there a bug?

```
Mär 15 10:53:49 raspberrypi2 homebridge[12747]: [2020-3-15 10:53:49] Loaded config.json with 0 accessories and 1 platforms.
Mär 15 10:53:49 raspberrypi2 homebridge[12747]: [2020-3-15 10:53:49] ---
Mär 15 10:53:49 raspberrypi2 homebridge[12747]: [2020-3-15 10:53:49] Plugin /usr/local/lib/node_modules/homebridge-lib package.json does not contain the keyword 'homebridge-plugin'.
Mär 15 10:53:49 raspberrypi2 homebridge[12747]: [2020-3-15 10:53:49] Plugin /usr/local/lib/node_modules/homebridge-hue requires Node version of ^12.16.1 which does not satisfy the current Node version of v9.4.0. You may need to upgrade your installation of Node.
Mär 15 10:53:53 raspberrypi2 homebridge[12747]: [2020-3-15 10:53:53] Loaded plugin: homebridge-hue
Mär 15 10:53:53 raspberrypi2 homebridge[12747]: [2020-3-15 10:53:53] Registering platform 'homebridge-hue.Hue'
Mär 15 10:53:53 raspberrypi2 homebridge[12747]: [2020-3-15 10:53:53] ---
Mär 15 10:53:53 raspberrypi2 homebridge[12747]: [2020-3-15 10:53:53] Loading 1 platforms...
Mär 15 10:53:53 raspberrypi2 homebridge[12747]: [2020-3-15 10:53:53] [deCONZ] Initializing Hue platform...
Mär 15 10:53:53 raspberrypi2 homebridge[12747]: [2020-3-15 10:53:53] [deCONZ] homebridge-hue v0.11.58, node v9.4.0, homebridge v0.4.50
Mär 15 10:53:53 raspberrypi2 homebridge[12747]: [2020-3-15 10:53:53] [deCONZ] warning: not using recommended node version v12.16.1 LTS
Mär 15 10:53:53 raspberrypi2 homebridge[12747]: [2020-3-15 10:53:53] Loading 0 accessories...
Mär 15 10:53:53 raspberrypi2 homebridge[12747]: [2020-3-15 10:53:53] [deCONZ] npm registry: TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type Function
Mär 15 10:53:53 raspberrypi2 homebridge[12747]:     at ClientRequest.once (events.js:270:11)
Mär 15 10:53:53 raspberrypi2 homebridge[12747]:     at new ClientRequest (_http_client.js:164:10)
Mär 15 10:53:53 raspberrypi2 homebridge[12747]:     at Object.request (http.js:38:10)
Mär 15 10:53:53 raspberrypi2 homebridge[12747]:     at HttpClient.request (/usr/local/lib/node_modules/homebridge-hue/node_modules/homebridge-lib/lib/HttpClient.js:226:32)
Mär 15 10:53:53 raspberrypi2 homebridge[12747]:     at HttpClient.get (/usr/local/lib/node_modules/homebridge-hue/node_modules/homebridge-lib/lib/HttpClient.js:136:17)
Mär 15 10:53:53 raspberrypi2 homebridge[12747]:     at HuePlatform.accessories (/usr/local/lib/node_modules/homebridge-hue/lib/HuePlatform.js:279:38)
Mär 15 10:53:53 raspberrypi2 homebridge[12747]:     at Server._loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:403:20)
Mär 15 10:53:53 raspberrypi2 homebridge[12747]:     at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:341:16)
Mär 15 10:53:53 raspberrypi2 homebridge[12747]:     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
Mär 15 10:53:53 raspberrypi2 homebridge[12747]:     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
Mär 15 10:53:53 raspberrypi2 homebridge[12747]: [2020-3-15 10:53:53] [deCONZ] 192.***.***.31: TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type Function
Mär 15 10:53:53 raspberrypi2 homebridge[12747]:     at ClientRequest.once (events.js:270:11)
Mär 15 10:53:53 raspberrypi2 homebridge[12747]:     at new ClientRequest (_http_client.js:164:10)
Mär 15 10:53:53 raspberrypi2 homebridge[12747]:     at Object.request (http.js:38:10)
```

Here my Config:
```
{
 "bridge": {
 "name": "Homebridge-deconz",
 "username": "AA:22:5D:F3:CE:33",
 "port": 53835,
 "pin": "031-45-160",
 "manufacturer": "@Paul Schmidt",
 "model": "Homebridge",
 "serialNumber": "0.4.33"
},
    "plugins": [
        "homebridge-hue"
    ],

 "accessories": [
 ],

 "platforms": [ {
      "platform": "Hue",
        "name": "deCONZ",
        "forceHttp": true,
        "host": "192.168.0.31",
      "users": {
        "": ""
      },
      "sensors": true,
      "nativeHomeKitSensors": false,
      "excludeSensorTypes": ["CLIPPresence", "Geofence"],
      "lights": true
    }
 ]
}
```

**Comment by ebaauw** [comment]
```
Mär 15 10:53:49 raspberrypi2 homebridge[12747]: [2020-3-15 10:53:49] Plugin /usr/local/lib/node_modules/homebridge-hue requires Node version of ^12.16.1 which does not satisfy the current Node version of v9.4.0. You may need to upgrade your installation of Node.
Mär 15 10:53:53 raspberrypi2 homebridge[12747]: [2020-3-15 10:53:53] [deCONZ] homebridge-hue v0.11.58, node v9.4.0, homebridge v0.4.50
Mär 15 10:53:53 raspberrypi2 homebridge[12747]: [2020-3-15 10:53:53] [deCONZ] warning: not using recommended node version v12.16.1 LTS
```
That's an old, no longer supported version of NodeJS (see https://nodejs.org/en/about/releases/).  Not sure if that's causing this issue (I only test agains 
the latest LTS release), but I would strongly recommend at least to use a current version.

```
Mär 15 10:53:53 raspberrypi2 homebridge[12747]: [2020-3-15 10:53:53] [deCONZ] npm registry: TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type Function
```
I've seen that error before, see #652.  Something is breaking https (which homebridge-hue is using as of v0.11.55.  As a workaround, you might try setting `"forceHttp": true` in config.json.

It doesn't look like you're using any other plugins?  In that case, I think the issue is caused by the old NodeJS version.

**Comment by monza258** [comment]
Thank you, its done. New Node version have fix it.

**Comment by roboterm** [comment]
I have this problem too. 
Still running v0.11.52 to keep my homebridge running. 
Should I open a new issue?

**Comment by ebaauw** [comment]
If it's the same problem, you'll get the same answer: upgrade NodeJS, or try `"forceHttp": true` as workaround.  If it's another plugin breaking `https`, remove that other plugin, or run Homebridge Hue in a different Homebridge instance.  See #652.

**Comment by roboterm** [comment]
I already tried to update my NodeJS since I’m running v9.9.0 but it breaks other plugins like homebridge-bluetooth because it was compiled against that version 😒
