### ISSUE TITLE
Homebridge-Hue support for Homebridge 1.0.0

### ISSUE THREAD

**Issue by jostrasser** [ebaauw/homebridge-hue#676]
Hi,

I got troubles after upgrading to Homebridge 1.0.0, looks like HB-HUE does not support HB 1.0.0:

[4/27/2020, 7:18:34 AM] ERROR LOADING PLUGIN homebridge-hue:
[4/27/2020, 7:18:34 AM] Error: Plugin /usr/lib/node_modules/homebridge-hue requires a HomeBridge version of ~0.4.53 which does not satisfy the current HomeBridge version of 1.0.0. You may need to upgrade your installation of HomeBridge.
    at Plugin.load (/usr/lib/node_modules/homebridge/src/plugin.ts:144:13)
    at /usr/lib/node_modules/homebridge/src/pluginManager.ts:119:16
    at Map.forEach (<anonymous>)
    at PluginManager.initializeInstalledPlugins (/usr/lib/node_modules/homebridge/src/pluginManager.ts:117:18)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:148:24)
    at cli (/usr/lib/node_modules/homebridge/src/cli.ts:74:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
[4/27/2020, 7:18:34 AM] ====================

Thanks JO!

**Comment by ebaauw** [comment]
Upgrade to homebridge-hue v0.11.63, see https://github.com/ebaauw/homebridge-hue/releases.

**Comment by Nastras** [comment]
Good morning @ebaauw,

i was about to report the same problem but then saw your answer and after the update it works again. Thanks a lot!

I have this message at two other plugins homebridge-tado-platform and homebridge-fritz-platform. Can you tell me if the problem can be fixed by me in the config.json or must there be an update from the plugin developer?

**Comment by jostrasser** [comment]
Oh, sorry, I´ve missed that ;)
Works like a charm. Thanks!

**Comment by Nastras** [comment]
Problem is solved by changing the package.json to "homebridge": "^1.0.0",

**Comment by ebaauw** [comment]
> I have this message at two other plugins homebridge-tado-platform and homebridge-fritz-platform. Can you tell me if the problem can be fixed by me in the config.json or must there be an update from the plugin developer?

I'm sorry, I don't know these plugins.

> Problem is solved by changing the package.json to "homebridge": "^1.0.0"

Maybe, maybe not.  Suppressing a version check doesn't resolve any underlying incompatibilities. There are several changes in Homebridge v1.0.0, that might require changes in the plugins.

**Comment by Nastras** [comment]
Thanks for your fast feedback. It's at least a solution until the plugin has received an update ;-)
