### ISSUE TITLE
since update Homebridge to 1.0.0 i get this "Error: The requested platform 'Hue' was not registered by any plugin."

### ISSUE THREAD

**Issue by testpaul999** [ebaauw/homebridge-hue#677]
[2020-4-27 7:47:04] Error loading platform requested in your config.json at position 2
[2020-4-27 7:47:04] Error: The requested platform 'Hue' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:223:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:361:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:348:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:151:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:74:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
homebridge.service: Succeeded.

**Comment by timwegenerDE** [comment]
Same here.
![5A94DABC-5419-416F-A088-55D44F27A2F1](https://user-images.githubusercontent.com/56134910/80338959-f27f8180-885d-11ea-8f9b-a57a96ee39b8.jpeg)

**Comment by ebaauw** [comment]
See #676

**Comment by MickeH81** [comment]
I got this error again after updating to Node.js to version 12.16.3
