### ISSUE TITLE
 [Hue] undefined: TypeError: bridgeid: missing string value

### ISSUE THREAD

**Issue by h0mesmart** [ebaauw/homebridge-hue#680]
#### Issue

Unable to start homebridge services due to Hue plugin error :  undefined: TypeError: bridgeid: missing string value

#### Log Messages

```
[Homebridge] [4/27/2020, 11:14:36 PM] [Hue] undefined: TypeError: bridgeid: missing string value
    at newTypeError (/home/hoobs/.hoobs/node_modules/homebridge-lib/lib/OptionParser.js:42:52)
    at Function.toString (/home/hoobs/.hoobs/node_modules/homebridge-lib/lib/OptionParser.js:298:13)
    at Object._callbacks.<computed> [as bridgeid] (/home/hoobs/.hoobs/node_modules/homebridge-lib/lib/OptionParser.js:781:40)
    at OptionParser.parse (/home/hoobs/.hoobs/node_modules/homebridge-lib/lib/OptionParser.js:808:29)
    at new HueClient (/home/hoobs/.hoobs/node_modules/@hoobs/hue/lib/HueClient.js:41:18)
    at HueBridge.request (/home/hoobs/.hoobs/node_modules/@hoobs/hue/lib/HueBridge.js:1105:22)
    at HueBridge.getFullState (/home/hoobs/.hoobs/node_modules/@hoobs/hue/lib/HueBridge.js:314:28)
    at HueBridge.accessories (/home/hoobs/.hoobs/node_modules/@hoobs/hue/lib/HueBridge.js:93:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 1)
    at async HuePlatform.accessories (/home/hoobs/.hoobs/node_modules/@hoobs/hue/lib/HuePlatform.js:288:29)
[Homebridge] [4/27/2020, 11:14:36 PM] [Hue] undefined: 1 accessories
[Homebridge] [4/27/2020, 11:14:36 PM] [Hue] Philips hue: Philips BSB002 bridge v1938052050, api v1.37.0
[Homebridge] [4/27/2020, 11:14:36 PM] [Hue] Philips hue: 9 accessories
[Homebridge] [4/27/2020, 11:14:36 PM] [Hue] masked debug info dumped to /home/hoobs/.hoobs/etc/homebridge-hue.json.gz
[Homebridge] [4/27/2020, 11:14:36 PM] [Hue] Initializing platform accessory "Philips hue"...
[Homebridge] [4/27/2020, 11:14:36 PM] [Hue] Philips hue: 2 services
[Homebridge] [4/27/2020, 11:14:36 PM] [Hue] Initializing platform accessory "Près de la télé"...
[Homebridge] [4/27/2020, 11:14:36 PM] [Hue] Initializing platform accessory "Près du canapé"...
[Homebridge] [4/27/2020, 11:14:36 PM] [Hue] Initializing platform accessory "La Bande LED TV"...
[Homebridge] [4/27/2020, 11:14:36 PM] [Hue] Initializing platform accessory "Plafonnier"...
[Homebridge] [4/27/2020, 11:14:36 PM] [Hue] Initializing platform accessory "le ruban LED"...
[Homebridge] [4/27/2020, 11:14:36 PM] [Hue] Initializing platform accessory "Spot 2"...
[Homebridge] [4/27/2020, 11:14:36 PM] [Hue] Initializing platform accessory "Spot 1"...
[Homebridge] [4/27/2020, 11:14:36 PM] [Hue] Initializing platform accessory "Spot 3"...
[Homebridge] [4/27/2020, 11:14:36 PM] [Hue] Initializing platform accessory "undefined"...
[Homebridge] [4/27/2020, 11:14:36 PM] [Hue] undefined: 2 services
[Homebridge] [4/27/2020, 11:14:36 PM] [Hue] homebridge: error: Accessories must be created with a non-empty displayName.


```

#### Debug Files

[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/4541648/homebridge-hue.json.gz)

**Comment by ebaauw** [comment]
You're running a hoobs-modified version of Homebridge Hue.  Please contact hoobs support for issues with this version.

**Comment by h0mesmart** [comment]
Ok thanks. I got it working. I have to add the port number of the phoscon GW
