### ISSUE TITLE
Error in Initializing Plugin

### ISSUE THREAD

**Issue by petkoe** [ebaauw/homebridge-hue#692]
Hi,

i have a ConBee 2 and updated everything to the newest version (HB 1.0.4 etc.) 

At startup I now get the following error:

[ConBee2] npm registry: TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function. Received an instance of Object
    at checkListener (events.js:108:11)
    at ClientRequest.once (events.js:430:3)
    at new ClientRequest (_http_client.js:194:10)
    at Object.request (https.js:314:10)
    at Object.request (/usr/lib/node_modules/homebridge-fritz-platform/node_modules/http-proxy-agent/node_modules/agent-base/patch-core.js:25:22)
    at HttpClient.request (/usr/lib/node_modules/homebridge-hue/node_modules/homebridge-lib/lib/HttpClient.js:226:32)
    at HttpClient.get (/usr/lib/node_modules/homebridge-hue/node_modules/homebridge-lib/lib/HttpClient.js:136:17)
    at HuePlatform.accessories (/usr/lib/node_modules/homebridge-hue/lib/HuePlatform.js:279:38)
    at /usr/lib/node_modules/homebridge/src/server.ts:414:24
    at new Promise (<anonymous>)

My Config for the HUE is

{
            "name": "ConBee2",
            "anyOn": true,
            "forceCt": true,
            "groups": false,
            "group0": true,
            "heartrate": 5,
            "hosts": [
                "pi.local:8090"
            ],
            "lights": true,
            "lowBattery": 25,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "nupnp": true,
            "resource": false,
            "rooms": false,
            "rules": false,
            "schedules": false,
            "sensors": true,
            "timeout": 5,
            "users": {
                "xx": "xx"
            },
            "platform": "Hue"
        },

xx are the correct strings. The devices are visible and working correct. 

Kind regards

Peter

**Comment by ebaauw** [comment]
See #629.

**Comment by petkoe** [comment]
Thank you. I did a search before but din not find it.
