### ISSUE TITLE
Unable to connect: bridge communication error

### ISSUE THREAD

**Issue by schmidtflo** [ebaauw/homebridge-hue#704]
#### Issue
Hey, I had set up my homebridge + homebridge-hue successfully around two weeks ago. Somehow, the bridge is not able to connect to the Hue bridge anymore. For me, it seems like an API change, which is causing an error in the JS.

I've already checked, I'm using the latest versions of all libraries, and using the Synology package.

#### Log Messages

```
[5/23/2020, 2:41:10 PM] [Hue] Philips hue: Philips BSB002 bridge v1938112040, api v1.38.0
[5/23/2020, 2:41:10 PM] [Hue] Philips hue: warning: not using recommended Hue bridge api version 1.37.0
[5/23/2020, 2:41:10 PM] [Hue] Philips hue: bridge request 1: get /
[5/23/2020, 2:41:10 PM] [Hue] Philips hue: bridge communication error: TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function. Received an instance of Object
    at checkListener (events.js:108:11)
    at ClientRequest.once (events.js:430:3)
    at new ClientRequest (_http_client.js:194:10)
    at Object.request (https.js:314:10)
    at Object.request (/homebridge/node_modules/homebridge-fritz-platform/node_modules/http-proxy-agent/node_modules/agent-base/patch-core.js:25:22)
    at HttpClient.request (/homebridge/node_modules/homebridge-hue/node_modules/homebridge-lib/lib/HttpClient.js:226:32)
    at HueClient._request (/homebridge/node_modules/homebridge-hue/lib/HueClient.js:348:41)
    at HueBridge.request (/homebridge/node_modules/homebridge-hue/lib/HueBridge.js:1121:43)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at HueBridge.getFullState (/homebridge/node_modules/homebridge-hue/lib/HueBridge.js:314:17)
[5/23/2020, 2:41:10 PM] [Hue] Philips hue: 
[5/23/2020, 2:41:10 PM] [Hue] Philips hue: 1 accessories
[5/23/2020, 2:41:10 PM] [Hue] masked debug info dumped to /homebridge/homebridge-hue.json.gz
[5/23/2020, 2:41:10 PM] Initializing platform accessory 'Philips hue'...
[5/23/2020, 2:41:10 PM] [Hue] Philips hue: 2 services
```

#### Debug Files
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/4671775/homebridge-hue.json.gz)

**Comment by ebaauw** [comment]
`homebridge-fritz-platform` is breaking `https`.  See #629.
