### ISSUE TITLE
The requested platform 'ZigBeePlatform' was not registered by any plugin.

### ISSUE THREAD

**Issue by kevinmaccloud** [ebaauw/homebridge-hue#791]
#### Issue

Homebridge won't start at all.

I saw the other post where it was advise to update hombridge-lib, which I did but no fix. 

#### Log Messages

```

pi@raspberrypi:~ $ homebridge
[25/10/2020, 00:21:17] Loaded config.json with 1 accessories and 4 platforms.
[25/10/2020, 00:21:17] ---
[25/10/2020, 00:21:19] Plugin /usr/local/lib/node_modules/homebridge-lib package.json does not contain the keyword 'homebridge-plugin'.
[25/10/2020, 00:21:19] Loaded plugin: homebridge-config-ui-x@4.30.0
[25/10/2020, 00:21:19] Registering platform 'homebridge-config-ui-x.config'
[25/10/2020, 00:21:19] ---
[25/10/2020, 00:21:19] The plugin "homebridge-hue" requires Node version of ^12.19.0 which does not satisfy the current Node version of v15.0.1. You may need to upgrade your installation of Node.
[25/10/2020, 00:21:22] Loaded plugin: homebridge-hue@0.11.77
[25/10/2020, 00:21:22] Registering platform 'homebridge-hue.Hue'
[25/10/2020, 00:21:22] ---
[25/10/2020, 00:21:22] Loaded plugin: homebridge-lightify@0.0.10
[25/10/2020, 00:21:22] Registering platform 'homebridge-lightify.Lightify'
[25/10/2020, 00:21:22] ---
[25/10/2020, 00:21:23] Loaded plugin: homebridge-mi-aqara-fakegato@0.8.6
[25/10/2020, 00:21:23] Registering platform 'homebridge-mi-aqara-fakegato.MiAqaraPlatform'
[25/10/2020, 00:21:23] ---
[25/10/2020, 00:21:23] Loaded plugin: homebridge-philipstv-enhanced@0.1.1
[25/10/2020, 00:21:23] Registering accessory 'homebridge-philipstv-enhanced.PhilipsTV'
[25/10/2020, 00:21:23] ---
[25/10/2020, 00:21:24] Loaded plugin: homebridge-ps4-waker-platform@1.3.0
[25/10/2020, 00:21:24] Registering platform 'homebridge-ps4-waker-platform.PS4WakerPlatform'
[25/10/2020, 00:21:24] ---
[25/10/2020, 00:21:24] Loading 4 platforms...
[25/10/2020, 00:21:24] [Config] Initializing config platform...
[25/10/2020, 00:21:24] [Config] Spawning homebridge-config-ui-x with PID 13727
[25/10/2020, 00:21:24] [PlayStation 4] Initializing PS4WakerPlatform platform...
[25/10/2020, 00:21:24] [deConz] Initializing Hue platform...
[25/10/2020, 00:21:24] [deConz] config.json: warning: forceCt: ignoring unknown key
[25/10/2020, 00:21:24] [deConz] homebridge-hue v0.11.77, node v15.0.1, homebridge v1.1.2
[25/10/2020, 00:21:24] [deConz] warning: not using recommended node version v12.19.0 LTS
[25/10/2020, 00:21:24] Error loading platform requested in your config.json at position 4
[25/10/2020, 00:21:24] Error: The requested platform 'ZigBeePlatform' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:224:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:387:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:374:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:153:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
    at Module.load (node:internal/modules/cjs/loader:948:32)
[25/10/2020, 00:21:24] Got SIGTERM, shutting down Homebridge...
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/lib/unixTerminal.js
- /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/lib/index.js
- /usr/local/lib/node_modules/homebridge-config-ui-x/dist/main.js
- /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/fork.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:900:15)
    at Function.Module._load (node:internal/modules/cjs/loader:745:27)
    at Module.require (node:internal/modules/cjs/loader:972:19)
    at require (node:internal/modules/cjs/helpers:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/lib/unixTerminal.js:30:15)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
    at Module.load (node:internal/modules/cjs/loader:948:32)
    at Function.Module._load (node:internal/modules/cjs/loader:789:14)
    at Module.require (node:internal/modules/cjs/loader:972:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/lib/unixTerminal.js',
    '/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/lib/index.js',
    '/usr/local/lib/node_modules/homebridge-config-ui-x/dist/main.js',
    '/usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/fork.js'
  ]
}
[25/10/2020, 00:21:25] [deConz] Phoscon-GW: dresden elektronik deCONZ gateway v2.5.84, api v1.16.0
[25/10/2020, 00:21:25] [Config] Error: The module '/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/build/Release/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 88. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
[25/10/2020, 00:21:25] [Config] [node-pty] Node.js v15.0.1
[25/10/2020, 00:21:25] [Config] [node-pty] Failed to load node-pty module
[25/10/2020, 00:21:25] [Config] [node-pty] This could be because the installation of this plugin did not complete successfully or you may have recently upgraded Node.js to a new major version.
[25/10/2020, 00:21:25] [Config] [node-pty] Follow the steps below to resolve this issue.
[25/10/2020, 00:21:25] [Config] [node-pty] Trying to rebuild automatically...
[25/10/2020, 00:21:25] [deConz] Phoscon-GW: 10 accessories
[25/10/2020, 00:21:25] [deConz] masked debug info dumped to /home/pi/.homebridge/homebridge-hue.json.gz
[25/10/2020, 00:21:25] Initializing platform accessory 'Phoscon-GW'...
[25/10/2020, 00:21:25] [deConz] Phoscon-GW: 2 services
[25/10/2020, 00:21:25] Initializing platform accessory 'Daylight'...
[25/10/2020, 00:21:25] Initializing platform accessory 'Motion Sensor'...
[25/10/2020, 00:21:25] Initializing platform accessory 'Vibration Sensor'...
[25/10/2020, 00:21:25] Initializing platform accessory 'Vibration Sensor (2)'...
[25/10/2020, 00:21:25] Initializing platform accessory 'Hypercube'...
[25/10/2020, 00:21:25] Initializing platform accessory 'Presence 9'...
[25/10/2020, 00:21:25] Initializing platform accessory 'Living room sensor'...
[25/10/2020, 00:21:25] Initializing platform accessory 'Motion Sensor (4)'...
[25/10/2020, 00:21:25] Initializing platform accessory 'Tesseract'...
[25/10/2020, 00:21:29] [deConz] goodbye
pi@raspberrypi:~ $ [25/10/2020, 00:21:56] [Config] [node-pty] Module rebuilt successfully (maybe) - if you are still encountering errors follow the steps below.
[25/10/2020, 00:21:56] [Config] [node-pty] From the terminal run these commands (exact commands may vary):

[25/10/2020, 00:21:56] [Config] cd /usr/local/lib/node_modules/homebridge-config-ui-x
[25/10/2020, 00:21:56] [Config] sudo npm rebuild --unsafe-perm

^C
```

**Comment by ebaauw** [comment]
This has nothing to do with Homebridge Hue.

> [25/10/2020, 00:21:24] Error: The requested platform 'ZigBeePlatform' was not registered by any plugin. 

You use a platform plugin in your config.json that isn’t installed

> [25/10/2020, 00:21:25] [Config] Error: The module '/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/build/Release/pty.node'
was compiled against a different Node.js version

You need to re-install package with C/C++ extension after upgrading the major version of NodeJS.
