### ISSUE TITLE
20.11.2020, 11:59:50 Error: Service name is already in use on the network

### ISSUE THREAD

**Issue by marvelousmo** [ebaauw/homebridge-hue#822]
#### Issue
Running HOOBS 3.2.10 without issues. Installed homebridge-hue plugin as described, added user as described. But after the homebridge-hue plugin starts homebridge crashes. When I deinstall the homebridge-hue plugin everything works normal again. Another user had the same problem but didn't provide an solution 
"I now know why the error occurred. Apparently I am not allowed to leave the deConz Gateway on the default name."
https://github.com/hoobs-org/HOOBS/issues/682 

#### Log Messages

```
20.11.2020, 11:59:50 Error: Service name is already in use on the network
    at Registry._onProbeComplete (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bonjour-hap/lib/Registry.js:106:27)
    at Prober.done (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bonjour-hap/lib/Prober.js:67:10)
    at Prober.onMDNSresponse (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bonjour-hap/lib/Prober.js:61:102)
    at EventEmitter.emit (events.js:315:20)
    at Socket.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/multicast-dns/index.js:49:43)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage [as onmessage] (dgram.js:919:8)
20.11.2020, 11:59:50 Got SIGTERM, shutting down Bridge...
```

**Comment by marvelousmo** [comment]
BTW, I just want to expose some lights that doesn't show up in homekit. I am using a Huebrige V2

**Comment by ebaauw** [comment]
As you can see from the stack trace, Homebridge Hue plays no part in this error.  Please contact HOOBS support for issues with HOOBS.
