### ISSUE TITLE
Gledopto 2m LED Strip and old bulbs throwing errors when using adaptive lighting

### ISSUE THREAD

**Issue by vmiraboronat** [ebaauw/homebridge-hue#831]
#### Issue
After updating to 0.12.2 (and now 0.12.3) and accessing lights that theoretically support Homekit Adaptive lighting, homebridge throws errors on the console, but it does not crash. The problem is that it keeps showing those errors from time to time even if adaptive lighting is not selected.

#### Log Messages
Errors seen are like these
```
[23/11/2020 9:07:41] [PhilipsHue] Flor Nenas: cannot compute transition control: TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at Function.from (buffer.js:333:9)
    at tlvFromHexString (/usr/lib/node_modules/homebridge-hue/lib/AdaptiveLighting.js:159:37)
    at AdaptiveLighting._generateControl (/usr/lib/node_modules/homebridge-hue/lib/AdaptiveLighting.js:195:9)
    at AdaptiveLighting.generateControl (/usr/lib/node_modules/homebridge-hue/lib/AdaptiveLighting.js:212:17)
    at HueLight.getTransitionControl (/usr/lib/node_modules/homebridge-hue/lib/HueLight.js:1774:29)
    at _Characteristics.<computed>.emit (events.js:315:20)
    at _Characteristics.<computed>.EventEmitter.emit (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at _Characteristics.<computed>.Characteristic._this.getValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:489:12)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1217:22
    at Array.forEach (<anonymous>)
```
Then, after enabling debug mode, relevant logs are:
for ```homekit transition control set to```:
```
[24/11/2020 7:45:23] [PhilipsHue] Flor Nenas: set homekit transition control to "ASQBAQ0CHAEQxPM9qWPJTA+LiWw2oz7vngII67hYMZIAAAADAbg="
[24/11/2020 7:45:23] [PhilipsHue] Flor Nenas: set homekit transition control to {"colorTemperature":{"iid":13,"transitionParameters":{"2.1.2.1":"C4F33DA963C94C0F8B896C36A33EEF9E","startTime":"2020-11-24T06:45:23.307Z"},"runtime":184}}
[24/11/2020 7:45:23] [PhilipsHue] Flor Nenas: set homekit transition control to "ASQBAQ0CHAEQxPM9qWPJTA+LiWw2oz7vngII67hYMZIAAAADAcM="
[24/11/2020 7:45:23] [PhilipsHue] Flor Nenas: set homekit transition control to {"colorTemperature":{"iid":13,"transitionParameters":{"2.1.2.1":"C4F33DA963C94C0F8B896C36A33EEF9E","startTime":"2020-11-24T06:45:23.307Z"},"runtime":195}}
[24/11/2020 7:45:23] [PhilipsHue] Flor Nenas: homekit transition control set to "Av8B/wEBDQImARDE8z2pY8lMD4uJbDajPu+eAgiVuVgxkgAAAAMIc9glI1nZPR0DAQEF/wEPAQT1SZ+/AgTkuMJDAwEAAAABEgEEZmamvwIEAIDAQwMEyGENAAAAARIBBGELtr8CBHKcu0MDBEB3GwAAAAESAQRERMS/AgSrqrdDAwRAdxsAAAABEgEEzczMvwIEAAC0QwMEQHcbAAAAARIBBD/p078CBBzHsUMDBEB3GwAAAAESAQRswda/AgSOY7BDAwRAdxsAAAABEgEEgy3YvwIEx3GvQwMEQHcbAAAAARIBBIMt2L8CBMfxrkMDBEB3GwAAAAEYAQRswda/AgQC/47jAf+uQwMEQHcbAAQEgO42AAAAARIBBIMt2L8CBMfxrkMDBEB3GwAAAAEYAQQ/6dO/AgQF/xxHr0MDBEB3GwAEBIDuNgAAAAESAQTkOM6/AgQ5DrBDAwRAdxsAAAABEgEEchzHvwIEHMexQwMEQHcbAAAAARIBBLy7u78CBFVVs0MDBEB3GwAAAAESAQQGW7C/AgSOY7ZDAwRAdxsAAAABEgEEUPqkvwIEx/G5QwMEQHcbAAAAARIBBN7dnb8CBKsqv0MDBEB3GwAAAAESAQT1SZ+/AgTkuMZDAwRAdxsAAAABEgEEfdKnvwIEOQ7QQwMEQHcbAAAAARIBBKVPugL/vwIEHAH/x9tDAwRAdxsAAAABEgEEERHRvwIEq6rnQwMEQHcbAAAAARIBBKuq6r8CBKuq80MDBEAF/3cbAAAAARIBBAAAAMACBAAA/kMDBEB3GwAAAAESAQRbsAXAAgTkOAJEAwRAdxsAAAABEgEEIiICwAIEVRUCRAMEQHcbAAAAARIBBNIn/b8CBMfxAUQDBEB3GwAAAAESAQQGW/C/AgTH8QBEAwRAdxsAAAABEgEE2ILtvwIEjqMBRAMEQHcbAAAAARgBBH3S578CBBwHAEQDBEB3GwAEBIDLpAAAAAESAQQLtuC/AgQcx/tDAwRAdxsAAAABEgEEVVXVvwIEAtlVVfVDAwQB0UB3GwAAAAESAQSf9Mm/AgSOY+5DAwRAdxsAAAABEgEE0ie9vwIEjmPnQwMEQHcbAAAAARIFkQEE2IKtvwIEHMffQwMEQHcbAAAAARIBBPVJn78CBOS42EMDBEB3GwAAAAESAQQ/6ZO/AgQcx9FDAwRAdxsAAAABEgEEERGRvwIEq6rLQwMEQHcbAAAAARIBBIMtmL8CBMfxxUMDBEB3GwAAAAESAQT1SZ+/AgTkuMJDAwR4FQ4AAgELAwwBBAoAAAACBGQAAAAGAmDqCATAJwkA"
[24/11/2020 7:45:23] [PhilipsHue] Flor Nenas: homekit transition control set to {"colorTemperature":{"iid":13,"transitionParameters":{"2.1.2.1":"C4F33DA963C94C0F8B896C36A33EEF9E","startTime":"2020-11-24T06:45:23.477Z","2.1.2.3":"73D8252359D93D1D"},"runtime":1,"curve":{"entries":[{"adjustmentFactor":-1.244444489479065,"mired":389.4444580078125,"offset":0},{"adjustmentFactor":-1.2999999523162842,"mired":385,"offset":877000},{"adjustmentFactor":-1.4222222566604614,"mired":375.22222900390625,"offset":1800000},{"adjustmentFactor":-1.5333333015441895,"mired":367.3333435058594,"offset":1800000},{"adjustmentFactor":-1.600000023841858,"mired":360,"offset":1800000},{"adjustmentFactor":-1.6555556058883667,"mired":355.5555419921875,"offset":1800000},{"adjustmentFactor":-1.6777777671813965,"mired":352.77777099609375,"offset":1800000},{"adjustmentFactor":-1.6888889074325562,"mired":350.8888854980469,"offset":1800000},{"adjustmentFactor":-1.6888889074325562,"mired":349.8888854980469,"offset":1800000},{"adjustmentFactor":-1.6777777671813965,"mired":349.77777099609375,"offset":1800000,"duration":3600000},{"adjustmentFactor":-1.6888889074325562,"mired":349.8888854980469,"offset":1800000},{"adjustmentFactor":-1.6555556058883667,"mired":350.5555419921875,"offset":1800000,"duration":3600000},{"adjustmentFactor":-1.6111111640930176,"mired":352.1111145019531,"offset":1800000},{"adjustmentFactor":-1.5555555820465088,"mired":355.5555419921875,"offset":1800000},{"adjustmentFactor":-1.4666666984558105,"mired":358.6666564941406,"offset":1800000},{"adjustmentFactor":-1.3777778148651123,"mired":364.77777099609375,"offset":1800000},{"adjustmentFactor":-1.288888931274414,"mired":371.8888854980469,"offset":1800000},{"adjustmentFactor":-1.2333333492279053,"mired":382.3333435058594,"offset":1800000},{"adjustmentFactor":-1.244444489479065,"mired":397.4444580078125,"offset":1800000},{"adjustmentFactor":-1.3111110925674438,"mired":416.1111145019531,"offset":1800000},{"adjustmentFactor":-1.4555555582046509,"mired":439.5555419921875,"offset":1800000},{"adjustmentFactor":-1.6333333253860474,"mired":463.3333435058594,"offset":1800000},{"adjustmentFactor":-1.8333333730697632,"mired":487.3333435058594,"offset":1800000},{"adjustmentFactor":-2,"mired":508,"offset":1800000},{"adjustmentFactor":-2.0888888835906982,"mired":520.888916015625,"offset":1800000},{"adjustmentFactor":-2.0333333015441895,"mired":520.3333129882812,"offset":1800000},{"adjustmentFactor":-1.9777777194976807,"mired":519.7777709960938,"offset":1800000},{"adjustmentFactor":-1.8777778148651123,"mired":515.7777709960938,"offset":1800000},{"adjustmentFactor":-1.855555534362793,"mired":518.5555419921875,"offset":1800000},{"adjustmentFactor":-1.8111110925674438,"mired":512.111083984375,"offset":1800000,"duration":10800000},{"adjustmentFactor":-1.755555510520935,"mired":503.5555419921875,"offset":1800000},{"adjustmentFactor":-1.6666666269302368,"mired":490.6666564941406,"offset":1800000},{"adjustmentFactor":-1.5777777433395386,"mired":476.77777099609375,"offset":1800000},{"adjustmentFactor":-1.4777777194976807,"mired":462.77777099609375,"offset":1800000},{"adjustmentFactor":-1.355555534362793,"mired":447.5555419921875,"offset":1800000},{"adjustmentFactor":-1.244444489479065,"mired":433.4444580078125,"offset":1800000},{"adjustmentFactor":-1.1555556058883667,"mired":419.5555419921875,"offset":1800000},{"adjustmentFactor":-1.1333333253860474,"mired":407.3333435058594,"offset":1800000},{"adjustmentFactor":-1.1888889074325562,"mired":395.8888854980469,"offset":1800000},{"adjustmentFactor":-1.244444489479065,"mired":389.4444580078125,"offset":923000}],"adjustmentIid":11,"adjustmentRange":{"min":10,"max":100}},"updateInterval":60000,"notifyIntervalThreshold":600000}}
[24/11/2020 7:45:23] [PhilipsHue] Flor Nenas: set homekit transition control to "AjABLgEBDQImARDE8z2pY8lMD4uJbDajPu+eAgiVuVgxkgAAAAMIc9glI1nZPR0DAVI="
[24/11/2020 7:45:23] [PhilipsHue] Flor Nenas: set homekit transition control to {"colorTemperature":{"iid":13,"transitionParameters":{"2.1.2.1":"C4F33DA963C94C0F8B896C36A33EEF9E","startTime":"2020-11-24T06:45:23.477Z","2.1.2.3":"73D8252359D93D1D"},"runtime":82}}
[24/11/2020 7:45:23] [PhilipsHue] Flor Nenas: set homekit active transition count to 1
```
And for ```set homekit supported transition configuration to```:
```
[24/11/2020 7:44:50] [PhilipsHue] Flor Nenas: set homekit supported transition configuration to AQYBAQsCAQEAAAEGAQENAgEC
[24/11/2020 7:44:50] [PhilipsHue] Flor Nenas: set homekit supported transition configuration to {"configuration":[{"iid":11,"characteristic":1},{"iid":13,"characteristic":2}]}
```
That's for the light called 'Flor Nenas', which is an old cheap zigbee bulb connected via deconz.
Another one showing similar or same errors is a Gledopto 2m lightstrip RGB+CCT with a mini zigbee controller (powered via usb). Same errors stated above but for the gledopto are show here:

```
[24/11/2020 7:45:35] [PhilipsHue] Tira Gledopto 2m: homekit transition control set to "Av8B/wEBFQIcARDE8z2pY8lMD4uJbDajPu+eAgij6VgxkgAAAAMBAQX/AQ8BBPVJn78CBOS4wkMDAQAAAAESAQRmZqa/AgQAgMBDAwToMg0AAAABEgEEYQu2vwIEcpy7QwMEQHcbAAAAARIBBERExL8CBKuqt0MDBEB3GwAAAAESAQTNzMy/AgQAALRDAwRAdxsAAAABEgEEP+nTvwIEHMexQwMEQHcbAAAAARIBBGzB1r8CBI5jsEMDBEB3GwAAAAESAQSDLdi/AgTHca9DAwRAdxsAAAABEgEEgy3YvwIEx/GuQwMEQHcbAAAAARIBBIMt2L8CBMfxrkMDBEB3GwAC/wAAAf8BEgEEgy3YvwIEx/GuQwMEQHcbAAAAARIBBGzB1r8CBI7jrkMDBAX/QHcbAAAAARIBBIMt2L8CBMfxrkMDBEB3GwAAAAESAQSDLdi/AgTH8a5DAwRAdxsAAAABEgEEgy3YvwIEx/GuQwMEQHcbAAAAARIBBD/p078CBBxHr0MDBEB3GwAAAAESAQTkOM6/AgQ5DrBDAwRAdxsAAAABEgEEchzHvwIEHMexQwMEQHcbAAAAARIBBLy7u78CBFVVs0MDBEB3GwAAAAESAQQGW7C/AgSOY7ZDAwRAdxsAAAABEgEEUPqkvwIEx/G5QwMEQHcbAAAAARIBBN7dnQL/vwIEqwH/Kr9DAwRAdxsAAAABEgEE9UmfvwIE5LjGQwMEQHcbAAAAARIBBH3SpwX/vwIEOQ7QQwMEQHcbAAAAARIBBKVPur8CBBzH20MDBEB3GwAAAAESAQQREdG/AgSrqudDAwRAdxsAAAABEgEEq6rqvwIEq6rzQwMEQHcbAAAAARIBBAAAAMACBAAA/kMDBEB3GwAAAAESAQQiIgLAAgRV1QBEAwRAdxsAAAABEgEE0if9vwIEx7EARAMEQHcbAAAAARIBBGEL9r8CBDmOAEQDBEB3GwAAAAESAQTYgu2/AgSOYwBEAwRAdxsAAAABEgEEZmbmvwIEAEAARAMEAv9AdxsAAAAB/wESAQRmZua/AgQAQABEAwRAdxsAAAABDwEEZmbmvwIEAEAARAMBAAAAAQX/EgEEZmbmvwIEAEAARAMEQFSJAAAAARIBBH3S578CBBwHAEQDBEB3GwAAAAESAQQLtuC/AgQcx/tDAwRAdxsAAAABEgEEVVXVvwIEVVX1QwMEQHcbAAAAARIBBJ/0yb8CBI5j7kMDBEB3GwAAAAESAQTSJ72/AgSOY+dDAwRAdxsAAAABEgEE2IKtvwIEHMffQwMEQHcbAAAAARIBBPVJn78CBOS42EMDBEB3GwAAAAESAQQ/6ZO/AgQcx9FDAwRAdxsAAAABEgEEERECWZG/AgSrqstDAU8DBEB3GwAAAAESAQSDLZi/AgTH8cVDAwRAdxsAAAABEgEE9UmfvwIE5LjCQwUXAwRYRA4AAgELAwwBBAoAAAACBGQAAAAGAmDqCATAJwkA"
[24/11/2020 7:45:35] [PhilipsHue] Tira Gledopto 2m: homekit transition control set to {"colorTemperature":{"iid":21,"transitionParameters":{"2.1.2.1":"C4F33DA963C94C0F8B896C36A33EEF9E","startTime":"2020-11-24T06:45:35.779Z"},"runtime":1,"curve":{"entries":[{"adjustmentFactor":-1.244444489479065,"mired":389.4444580078125,"offset":0},{"adjustmentFactor":-1.2999999523162842,"mired":385,"offset":865000},{"adjustmentFactor":-1.4222222566604614,"mired":375.22222900390625,"offset":1800000},{"adjustmentFactor":-1.5333333015441895,"mired":367.3333435058594,"offset":1800000},{"adjustmentFactor":-1.600000023841858,"mired":360,"offset":1800000},{"adjustmentFactor":-1.6555556058883667,"mired":355.5555419921875,"offset":1800000},{"adjustmentFactor":-1.6777777671813965,"mired":352.77777099609375,"offset":1800000},{"adjustmentFactor":-1.6888889074325562,"mired":350.8888854980469,"offset":1800000},{"adjustmentFactor":-1.6888889074325562,"mired":349.8888854980469,"offset":1800000},{"adjustmentFactor":-1.6888889074325562,"mired":349.8888854980469,"offset":1800000},{"adjustmentFactor":-1.6888889074325562,"mired":349.8888854980469,"offset":1800000},{"adjustmentFactor":-1.6777777671813965,"mired":349.77777099609375,"offset":1800000},{"adjustmentFactor":-1.6888889074325562,"mired":349.8888854980469,"offset":1800000},{"adjustmentFactor":-1.6888889074325562,"mired":349.8888854980469,"offset":1800000},{"adjustmentFactor":-1.6888889074325562,"mired":349.8888854980469,"offset":1800000},{"adjustmentFactor":-1.6555556058883667,"mired":350.5555419921875,"offset":1800000},{"adjustmentFactor":-1.6111111640930176,"mired":352.1111145019531,"offset":1800000},{"adjustmentFactor":-1.5555555820465088,"mired":355.5555419921875,"offset":1800000},{"adjustmentFactor":-1.4666666984558105,"mired":358.6666564941406,"offset":1800000},{"adjustmentFactor":-1.3777778148651123,"mired":364.77777099609375,"offset":1800000},{"adjustmentFactor":-1.288888931274414,"mired":371.8888854980469,"offset":1800000},{"adjustmentFactor":-1.2333333492279053,"mired":382.3333435058594,"offset":1800000},{"adjustmentFactor":-1.244444489479065,"mired":397.4444580078125,"offset":1800000},{"adjustmentFactor":-1.3111110925674438,"mired":416.1111145019531,"offset":1800000},{"adjustmentFactor":-1.4555555582046509,"mired":439.5555419921875,"offset":1800000},{"adjustmentFactor":-1.6333333253860474,"mired":463.3333435058594,"offset":1800000},{"adjustmentFactor":-1.8333333730697632,"mired":487.3333435058594,"offset":1800000},{"adjustmentFactor":-2,"mired":508,"offset":1800000},{"adjustmentFactor":-2.0333333015441895,"mired":515.3333129882812,"offset":1800000},{"adjustmentFactor":-1.9777777194976807,"mired":514.7777709960938,"offset":1800000},{"adjustmentFactor":-1.9222222566604614,"mired":514.2222290039062,"offset":1800000},{"adjustmentFactor":-1.855555534362793,"mired":513.5555419921875,"offset":1800000},{"adjustmentFactor":-1.7999999523162842,"mired":513,"offset":1800000},{"adjustmentFactor":-1.7999999523162842,"mired":513,"offset":1800000},{"adjustmentFactor":-1.7999999523162842,"mired":513,"offset":0},{"adjustmentFactor":-1.7999999523162842,"mired":513,"offset":9000000},{"adjustmentFactor":-1.8111110925674438,"mired":512.111083984375,"offset":1800000},{"adjustmentFactor":-1.755555510520935,"mired":503.5555419921875,"offset":1800000},{"adjustmentFactor":-1.6666666269302368,"mired":490.6666564941406,"offset":1800000},{"adjustmentFactor":-1.5777777433395386,"mired":476.77777099609375,"offset":1800000},{"adjustmentFactor":-1.4777777194976807,"mired":462.77777099609375,"offset":1800000},{"adjustmentFactor":-1.355555534362793,"mired":447.5555419921875,"offset":1800000},{"adjustmentFactor":-1.244444489479065,"mired":433.4444580078125,"offset":1800000},{"adjustmentFactor":-1.1555556058883667,"mired":419.5555419921875,"offset":1800000},{"adjustmentFactor":-1.1333333253860474,"mired":407.3333435058594,"offset":1800000},{"adjustmentFactor":-1.1888889074325562,"mired":395.8888854980469,"offset":1800000},{"adjustmentFactor":-1.244444489479065,"mired":389.4444580078125,"offset":935000}],"adjustmentIid":11,"adjustmentRange":{"min":10,"max":100}},"updateInterval":60000,"notifyIntervalThreshold":600000}}
[24/11/2020 7:45:35] [PhilipsHue] Tira Gledopto 2m: set homekit transition control to "AiYBJAEBFQIcARDE8z2pY8lMD4uJbDajPu+eAgij6VgxkgAAAAMBYQ=="
[24/11/2020 7:45:35] [PhilipsHue] Tira Gledopto 2m: set homekit transition control to {"colorTemperature":{"iid":21,"transitionParameters":{"2.1.2.1":"C4F33DA963C94C0F8B896C36A33EEF9E","startTime":"2020-11-24T06:45:35.779Z"},"runtime":97}}
[24/11/2020 7:45:35] [PhilipsHue] Tira Gledopto 2m: set homekit active transition count to 1
[24/11/2020 7:45:35] [PhilipsHue] Tira Gledopto 2m: set homekit transition control to "ASQBARUCHAEQxPM9qWPJTA+LiWw2oz7vngIIo+lYMZIAAAADAYU="
[24/11/2020 7:45:35] [PhilipsHue] Tira Gledopto 2m: set homekit transition control to {"colorTemperature":{"iid":21,"transitionParameters":{"2.1.2.1":"C4F33DA963C94C0F8B896C36A33EEF9E","startTime":"2020-11-24T06:45:35.779Z"},"runtime":133}}
[24/11/2020 7:45:35] [PhilipsHue] Tira Gledopto 2m: set homekit transition control to "ASQBARUCHAEQxPM9qWPJTA+LiWw2oz7vngIIo+lYMZIAAAADAYs="
[24/11/2020 7:45:35] [PhilipsHue] Tira Gledopto 2m: set homekit transition control to {"colorTemperature":{"iid":21,"transitionParameters":{"2.1.2.1":"C4F33DA963C94C0F8B896C36A33EEF9E","startTime":"2020-11-24T06:45:35.779Z"},"runtime":139}}
```

```
[24/11/2020 7:44:50] [PhilipsHue] Tira Gledopto 2m: set homekit supported transition configuration to AQYBAQsCAQEAAAEGAQEVAgEC
[24/11/2020 7:44:50] [PhilipsHue] Tira Gledopto 2m: set homekit supported transition configuration to {"configuration":[{"iid":11,"characteristic":1},{"iid":21,"characteristic":2}]}
```
Attached is the debug file for homebridge.

[homebridge.log.zip](https://github.com/ebaauw/homebridge-hue/files/5588089/homebridge.log.zip)

**Comment by ebaauw** [comment]
I only see errors from before you restarted Homebridge, still running Homebridge Hue v0.12.2.  After restart, running Homebridge Hue v0.12.3, I no longer see errors, and the log suggests that adaptive lighting seems to be working.

**Comment by vmiraboronat** [comment]
You're totally right. And indeed the error messages have disappeared since the 0.12.3 upgrade. I'll just close this.

Thanks Eric!

**Comment by Nude2life** [comment]
how to upgrade from v0.12.26  to v0.12.3?
