### ISSUE TITLE
Error-Code

### ISSUE THREAD

**Issue by paulxw** [ebaauw/homebridge-hue#835]
#### Issue

could you pls help me? Maybe in German 🥺
Downwards you see my log messages

#### Log Messages

```
27.11.2020, 21:48:39 Error: listen EADDRINUSE: address already in use :::51826
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1449:7)
    at EventedHTTPServer._this.listen (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/util/eventedhttp.js:100:30)
    at HAPServer._this.listen (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/HAPServer.js:201:31)
    at Bridge.Accessory._this.publish (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:575:27)
    at Server.publishBridge (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:193:21)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:162:53
    at async Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:162:9)
27.11.2020, 21:48:39 Got SIGTERM, shutting down Bridge...
```

**Comment by ebaauw** [comment]
This error has nothing to with Homebridge Hue.  You're probably already running Homebridge and try to start it a second time.  Please contact HOOBS support for issues with HOOBS.
