### ISSUE TITLE
Assertion error

### ISSUE THREAD

**Issue by Marcus235** [ebaauw/homebridge-hue#839]
#### Issue
Since the last update Homebridge won't start with resource lights ticked in config. It concerns my zigbee dimmer connected trough Hue Homebridge

#### Log Messages

```
[11/30/2020, 15:35:56] [Hue] Philips hue: Signify Netherlands B.V. BSB002 bridge v1941132070, api v1.41.0
[11/30/2020, 15:35:57] [Hue] Philips hue: /sensors/1: warning: Daylight sensor not configured
[11/30/2020, 15:35:57] [Hue] Philips hue: 3 accessories
[11/30/2020, 15:35:57] [Hue] masked debug info dumped to /var/lib/homebridge/homebridge-hue.json.gz
[11/30/2020, 15:35:57] Initializing platform accessory 'Philips hue'...
[11/30/2020, 15:35:57] [Hue] Philips hue: 2 services
[11/30/2020, 15:35:57] Initializing platform accessory ''...
[11/30/2020, 15:35:59] [Hue] homebridge: error: AssertionError [ERR_ASSERTION]: Accessories must be created with a non-empty displayName.
    at new Accessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:235:11)
    at Server.createHAPAccessory (/usr/local/lib/node_modules/homebridge/src/server.ts:469:25)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:433:34
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:423:21
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:10:18
    at HuePlatform.accessories (/usr/local/lib/node_modules/homebridge-hue/lib/HuePlatform.js:332:5)
[11/30/2020, 15:35:59] [Hue] heartbeat 0, drift 814
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/5616581/homebridge-hue.json.gz)
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/5616585/homebridge-hue.json.gz)

```

**Comment by ebaauw** [comment]
Homebridge Hue tries to expose a resource whose `name` is empty.  You should be good to go after you set the sensor name from the Hue app.

Did you run one of the early v0.12.x beta versions?  Some if them allowed setting an empty service name from Eve, which was then synchronised to the Hue bridge.  That should no longer happen in latest version, though.

**Comment by Marcus235** [comment]
Thanks. 

Somehow the name of the device went blank in Hue app. It works now. 

Met vriendelijke groet, kind regards,

Marcus Bitterling
