### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]

### ISSUE THREAD

**Issue by EinMalik** [ebaauw/homebridge-hue#891]
#### Issue

Since the update to v0.12.14 I am getting an error in homebridge log:
#### Log Messages

[Hue] TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function. Received an instance of Object
    at checkListener (events.js:112:11)
    at ClientRequest.once (events.js:435:3)
    at new ClientRequest (_http_client.js:202:10)
    at Object.request (https.js:313:10)
    at Object.request (/usr/local/lib/node_modules/homebridge-website-to-camera/node_modules/agent-base/patch-core.js:25:22)
    at /usr/local/lib/node_modules/homebridge-hue/node_modules/homebridge-lib/lib/HttpClient.js:341:34
    at new Promise (<anonymous>)
    at HttpClient.request (/usr/local/lib/node_modules/homebridge-hue/node_modules/homebridge-lib/lib/HttpClient.js:318:12)
    at HttpClient.get (/usr/local/lib/node_modules/homebridge-hue/node_modules/homebridge-lib/lib/HttpClient.js:259:17)
    at HuePlatform.accessories (/usr/local/lib/node_modules/homebridge-hue/lib/HuePlatform.js:392:40)

**Comment by ebaauw** [comment]
The `agent-base` module in `homebridge-website-to-camera` breaks (“patches”) the `https` module of NodeJS.  Remove that plugin (or run it in a different Homebridge instance).  See #629.

**Comment by EinMalik** [comment]
ok thanks!!
