### ISSUE TITLE
Plugin breaks after Pi Hole installation

### ISSUE THREAD

**Issue by philharmonie** [ebaauw/homebridge-hue#894]
#### Issue
I installed Pi Hole on the default ports, set the deconz ports from 8080 to 90 and after that the Homebridge-hue gives me the following log:

#### Log Messages

```
[14.1.2021, 08:44:04] [Hue] undefined: TypeError: config: not an object
    at newTypeError (/usr/local/lib/node_modules/homebridge-hue/node_modules/homebridge-lib/lib/OptionParser.js:35:52)
    at Function.toObject (/usr/local/lib/node_modules/homebridge-hue/node_modules/homebridge-lib/lib/OptionParser.js:432:13)
    at Object._callbacks.<computed> [as config] (/usr/local/lib/node_modules/homebridge-hue/node_modules/homebridge-lib/lib/OptionParser.js:756:40)
    at OptionParser.parse (/usr/local/lib/node_modules/homebridge-hue/node_modules/homebridge-lib/lib/OptionParser.js:818:29)
    at new HueClient (/usr/local/lib/node_modules/homebridge-hue/lib/HueClient.js:170:8)
    at HueBridge.exposeBridge (/usr/local/lib/node_modules/homebridge-hue/lib/HueBridge.js:231:20)
    at HueBridge.accessories (/usr/local/lib/node_modules/homebridge-hue/lib/HueBridge.js:85:16)
    at HueBridge.accessories (/usr/local/lib/node_modules/homebridge-hue/lib/HueBridge.js:94:19)
    at async Promise.all (index 0)
    at HuePlatform.accessories (/usr/local/lib/node_modules/homebridge-hue/lib/HuePlatform.js:340:29) - retrying in 15s
```

**Comment by ebaauw** [comment]
Make sure Homebridge Hue uses the new port.  It’s now connecting to pihole instead of to deconz

**Comment by philharmonie** [comment]
The issue was with the port 80 auf Pi Hole - Previously there has been the Hue emulator web interface - I switched it to port 100 to get Pi Hole running. After setting it back to 80 and moving pi hole to 100 it is working again. Now I'm left with
```
Jan 14 13:19:00 raspberrypi sudo[3638]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/kill -9 1485
Jan 14 13:19:00 raspberrypi sudo[3638]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jan 14 13:19:00 raspberrypi sudo[3638]: pam_unix(sudo:session): session closed for user root
```

**Comment by ebaauw** [comment]
Those are regular syslog messages when `sudo` is used, unrelated to Homebridge Hue.

**Comment by ebaauw** [comment]
v0.12.15 does better checking for Hue bridge / deCONZ gateway and no longer throws the `TypeError`, see also #888.
