### ISSUE TITLE
Question/Issue

### ISSUE THREAD

**Issue by GerLan** [ebaauw/homebridge-hue#904]
Hi,
I use conbee/deconz V2.09.00 and homebridgue Hue 0.12.17
I have bought a Mueller Licht LED Panel 404046 (https://www.mueller-licht.de/produktinformationen/artikel/404046/)
It is a package of a Zigbee RGB Panel and a Zigbee Remote. 
LED panel pops up in Deconz and I can control it in the Phoscon web app.
But in HomeKit Homeapp it is only an "unsupported device" in Eve App and HomeBridge accessories it does not show up at all.
Is it possible to use it in HomeBridge/HomeKit?
What information do you need?

BTW Remote is fine in HomeBridge/HomeKit.

thanks
Gerd

**Comment by ebaauw** [comment]
I need to know how deCONZ exposes the LED panel.  Can you please attach the debug dump file?

**Comment by GerLan** [comment]
Hi Erik,
attached the Dump.
Yes it's the Tint remote with colour wheel and it's working fine! :)

thanks,
Gerd


[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/5834840/homebridge-hue.json.gz)

**Comment by ebaauw** [comment]
From what I can tell from the dump file, Homebridge Hue should expose the light just fine.  Are you sure you restarted Homebridge after pairing the panel?  Could post a screenshot of the settings for the _Not Supported_ tile in Home?

**Comment by GerLan** [comment]
Hi,
Of course restarted Homebridge several times. 

This is the screenshot of the led panel
![image](https://user-images.githubusercontent.com/15939348/105088640-72a8df80-5a9c-11eb-85ec-e6a1fcba894d.jpeg)

And maybe a hint the phoscon gateway itself is "unsupported" in HomeKit too. But all the devices I registered are working fine. 

This is e.g. the Müller Remote
![image](https://user-images.githubusercontent.com/15939348/105088976-d3381c80-5a9c-11eb-954e-2a169b6bbb78.jpeg)

And the gateway
![image](https://user-images.githubusercontent.com/15939348/105089040-ec40cd80-5a9c-11eb-8609-89742b02d3f9.jpeg)

Thanks for looking into this issue!

Gerd

**Comment by GerLan** [comment]
One addition

I just tested for the first time the hue essential app in my environment. 

In this App the light is working fine...

😳

**Comment by ebaauw** [comment]
Please capture and attach a debug log file.  I need to see the debug messages, when Homebridge starts.

**Comment by GerLan** [comment]
Hi Erik,
because the Log is long I only added the Conbee Detection of this particular lamp:

`[1/21/2021, 12:49:59 PM] [Conbee/Zigbee] Phoscon-GW: EC1BBDFFFEDCB1FE: MLI RGB-CCT "Gerd Deckenlampe"
[1/21/2021, 12:49:59 PM] [Conbee/Zigbee] Phoscon-GW: /lights/6: Extended color light "Gerd Deckenlampe"
[1/21/2021, 12:49:59 PM] [Conbee/Zigbee] Phoscon-GW: /lights/6: config: {"on":true,"bri":true,"ct":true,"xy":true,"speed":false,"colorLoop":true,"colorLoopSpeed":true,"lastBoot":true,"lastSeen":true,"resetTimeout":500,"waitTimeUpdate":20,"minCt":155,"maxCt":550,"gamut":{"r":[0.68,0.31],"g":[0.11,0.82],"b":[0.13,0.04]},"unknown":false,"effects":["Sunset","Party","Worklight","Campfire","Romance","Nightlight"]}
[1/21/2021, 12:49:59 PM] [Conbee/Zigbee] Phoscon-GW: error: /lights/6: {"colorcapabilities":25,"ctmax":550,"ctmin":155,"etag":"ac6806f7e198ef90e25950fb8de2107e","hascolor":true,"lastannounced":null,"lastseen":"2021-01-21T11:49Z","manufacturername":"MLI","modelid":"RGB-CCT","name":"Gerd Deckenlampe","state":{"alert":"none","bri":54,"colormode":"ct","ct":370,"effect":null,"hue":22189,"on":false,"reachable":true,"sat":253,"xy":[0.1808,0.7266]},"swversion":"2.5.3_r47","type":"Extended color light","uniqueid":"ec:1b:bd:ff:fe:dc:b1:fe-01"}
TypeError: Cannot read property '0' of null
    at HueLight.checkEffect (/usr/lib/node_modules/homebridge-hue/lib/HueLight.js:1124:20)
    at new HueLight (/usr/lib/node_modules/homebridge-hue/lib/HueLight.js:504:12)
    at HueAccessory.exposeLightResource (/usr/lib/node_modules/homebridge-hue/lib/HueAccessory.js:235:19)
    at HueAccessory.exposeLightResources (/usr/lib/node_modules/homebridge-hue/lib/HueAccessory.js:225:12)
    at HueAccessory.expose (/usr/lib/node_modules/homebridge-hue/lib/HueAccessory.js:123:8)
    at HueBridge.exposeResources (/usr/lib/node_modules/homebridge-hue/lib/HueBridge.js:583:49)
    at HueBridge.accessories (/usr/lib/node_modules/homebridge-hue/lib/HueBridge.js:116:16)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
    at HuePlatform.accessories (/usr/lib/node_modules/homebridge-hue/lib/HuePlatform.js:345:29)
`

**Comment by GerLan** [comment]
and complete log:

[homebridge.log.txt.zip](https://github.com/ebaauw/homebridge-hue/files/5849134/homebridge.log.txt.zip)

**Comment by ebaauw** [comment]
Thanks.  Homebridge Hue chokes because `state.effect` has value `null` instead of `"none"`.  I fixed that in https://github.com/dresden-elektronik/deconz-rest-plugin/pull/4048, but that is only included in v2.9.1.  If you do a `ph put /lights/6/state '{"effect": "none"}` and then restart Homebridge, the light should be exposed.

Does the panel actually support the special effects ("scenes") of the other Tint lights (activated through the scene keys on the remote).

**Comment by GerLan** [comment]
Hi Erik, 
Thanks for help 👍
I will test it tomorrow. 

Yes the panel supports the scenes via the remote.

**Comment by GerLan** [comment]
I did the update to deconz 2.9.1 and EVERYTHING is running fine now :), even the Scenes are working through HomeKit!. You can put the Müller Tint Light into the compatibility list!

many thanks, for this and all of your other homebridge plugins!
