### ISSUE TITLE
deconz integration does not work

### ISSUE THREAD

**Issue by Schmello** [ebaauw/homebridge-hue#918]
I run Homebridge and Deconz in a Docker.
I installed the Homebridge Hue plugin and entered the IP and port.
In deconz I activated Connect App and then restarted the Homebridge Server.
The Homebridge Protocol says the following. This repeats itself over and over again.
```
[1/29/2021, 5:23:08 PM] [Hue] homebridge-hue is taking a long time to load and preventing Homebridge from starting.
[1/29/2021, 5:23:29 PM] [Hue] homebridge-hue is taking a long time to load and preventing Homebridge from starting.
[1/29/2021, 5:23:49 PM] [Hue] homebridge-hue is taking a long time to load and preventing Homebridge from starting.
[1/29/2021, 5:23:49 PM] [Hue] Phoscon-GW: TypeError: Cannot read property 'config' of undefined
    at HueBridge.exposeBridge (/homebridge/node_modules/homebridge-hue/lib/HueBridge.js:188:56)
    at HueBridge.accessories (/homebridge/node_modules/homebridge-hue/lib/HueBridge.js:113:5)
    at async Promise.all (index 0)
    at HuePlatform.accessories (/homebridge/node_modules/homebridge-hue/lib/HuePlatform.js:352:29) - retrying in 15s
[1/29/2021, 5:24:04 PM] [Hue] Phoscon-GW: RaspBee/ConBee not yet initialised - wait 1 minute
[1/29/2021, 5:24:09 PM] [Hue] homebridge-hue is taking a long time to load and preventing Homebridge from starting.
[1/29/2021, 5:24:29 PM] [Hue] homebridge-hue is taking a long time to load and preventing Homebridge from starting.
[1/29/2021, 5:24:49 PM] [Hue] homebridge-hue is taking a long time to load and preventing Homebridge from starting.
[1/29/2021, 5:25:04 PM] [Hue] Phoscon-GW: TypeError: Cannot read property 'config' of undefined
    at HueBridge.exposeBridge (/homebridge/node_modules/homebridge-hue/lib/HueBridge.js:188:56)
    at HueBridge.accessories (/homebridge/node_modules/homebridge-hue/lib/HueBridge.js:113:5)
    at async Promise.all (index 0)
    at HuePlatform.accessories (/homebridge/node_modules/homebridge-hue/lib/HuePlatform.js:352:29) - retrying in 15s
[1/29/2021, 5:25:09 PM] [Hue] homebridge-hue is taking a long time to load and preventing Homebridge from starting.
[1/29/2021, 5:25:19 PM] [Hue] Phoscon-GW: RaspBee/ConBee not yet initialised - wait 1 minute
[1/29/2021, 5:25:29 PM] [Hue] homebridge-hue is taking a long time to load and preventing Homebridge from starting.
[1/29/2021, 5:25:49 PM] [Hue] homebridge-hue is taking a long time to load and preventing Homebridge from starting.

```
Here is the self-made config
```
{
            "name": "Hue",
            "anyOn": true,
            "effects": true,
            "hosts": [
                "192.168.10.10:8282"
            ],
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "resource": true,
            "platform": "Hue"
        }
```

**Comment by ebaauw** [comment]
That’s a bug allright.  The corresponding code is only hit when deCONZ reports a `bridgeid` off all `0`s.  Because of the `TypeError`, Homebridge Hue doesn’t re-read the `bridge` and is stuck in a loop.  If you just restart Homebridge (without restarting deCONZ!), it’ll probably works, since deCONZ would have initialised by now.

**Comment by Schmello** [comment]
Even if I restart Homebridge Hue several times, the problem remains.
No user and password for the config are shown in the log.

Where can I get the user and password for deconz from?

**Comment by ebaauw** [comment]
v0.12.21 gets rid of the TypeError.

deCONZ needs to report a valid bridge ID before Homebridge Hue continues to create the API key and log the `bridgeid`/`username` to include in config.json.

**Comment by Schmello** [comment]
I'm really not very familiar with the topic :) Thank you for your answers.
But what can I do now? Do I have to wait for a fix for the Deconz software?

**Comment by ebaauw** [comment]
Yeah, you can put any valid API key in config.json, but Homebridge Hue needs deCONZ to report a valid bridgeid.  Not sure why/when it doesn’t.  Better ask on their Discord or GitHub repo.
