### ISSUE TITLE
Unable to launch homebridge after adding -hue

### ISSUE THREAD

**Issue by macbisho** [ebaauw/homebridge-hue#93]
I've been running homebridge for a few months with the plugin-wemo system and it's been great...

I've added a Hue Bridge v2 square and a couple of lightstrips via HomeKit... however I want to bring a Hue Dimmer switch and eventually a motion detector in.

I've installed homebridge-hue, updated my config.json 

```
{
	"bridge": {
		"name": "TakeItToTheBridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "xxx-xx-254"
	},

	"platforms": [{
		"platform": "BelkinWeMo",
		"name": "WeMo Platform",
		"noMotionTimer": 60,
		"ignoredDevices": []
	}, {
		"platforms": [{
			"platform": "Hue",
			"name": "Hue",
			"users": {
				"001788FFFExxxxxx": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
				"001788FFFEyyyyyy": "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"
			},
			"sensors": true,
			"excludeSensorTypes": ["Daylight", "CLIP", "Geofence"],
			"lights": true,
			"ct": true
		}]
	}]
}

```
```
And when I run homebridge it fails to launch:
[4/12/2017, 7:02:01 AM] Loaded plugin: homebridge-hue
[4/12/2017, 7:02:01 AM] Registering platform 'homebridge-hue.Hue'
[4/12/2017, 7:02:01 AM] ---
[4/12/2017, 7:02:01 AM] Loaded plugin: homebridge-platform-wemo
[4/12/2017, 7:02:01 AM] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
[4/12/2017, 7:02:01 AM] ---
[4/12/2017, 7:02:01 AM] Loaded config.json with 0 accessories and 2 platforms.
[4/12/2017, 7:02:01 AM] ---
[4/12/2017, 7:02:01 AM] Loading 2 platforms...
[4/12/2017, 7:02:01 AM] [WeMo Platform] Initializing BelkinWeMo platform...
/usr/local/lib/node_modules/homebridge/lib/api.js:108
  if (name.indexOf('.') == -1) {
          ^

TypeError: Cannot read property 'indexOf' of undefined
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:108:11)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:284:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:80:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

I'm completely stuck - I've removed homebridge-hue and reconfigured my config.json file back for wemo and it's working again.

Any help would be great!

Ps. thanks for doing so much brilliant work - reading through this, I'm amazed at how much you've done!

**Comment by ebaauw** [comment]
I've never seen this error, but I think it might be caused by an error in your config.json.  It shouldn't have a nested `platforms` array, just a single array with two objects:

```json
{
	"bridge": {
		"name": "TakeItToTheBridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "xxx-xx-254"
	},
	"platforms": [{
		"platform": "BelkinWeMo",
		"name": "WeMo Platform",
		"noMotionTimer": 60,
		"ignoredDevices": []
	}, {
		"platform": "Hue",
		"name": "Hue",
		"users": {
			"001788FFFExxxxxx": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
			"001788FFFEyyyyyy": "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"
		},
		"sensors": true,
		"excludeSensorTypes": ["Daylight", "CLIP", "Geofence"],
		"lights": true,
		"ct": true
	}]
}
```

**Comment by macbisho** [comment]
I now have a working homebridge-hue & homebridge-platform-wemo.

I'm utterly in your debt. Thank you so much for this!

Is there a way I can contribute to keep this amazing development going?

**Comment by Darbos** [comment]
Hey, I have been ebaau help a lot of folks out here.  I hope you see this:)  I am trying to setup home bridge with hue and I am having the same issue that I see a lot of people talk about but I haven't been able to resolve it with what I found.  I keep getting the was not registered with any plugin error.

Any help would be GREATLY apprecited 

My config.json
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

    "accessories": [
        {
            "accessory": "WeMo",
            "name": "Coffee Maker"
        }
    ],

    "platforms": [
      {
            "platform": "PhillipsHue",
            "name": "Hue",
            "host": "192.168.86.56",
            "users": {
              "001788FFFE4C543A": "m2d8FBHGXwlQigSuRV3c4YGTRbBMYnctk7ysmXM4"
            },
            "sensors": true,
            "excludeSensorTypes": ["CLIP", "Geofence", "Daylight"],
            "lowBattery": 25,
            "lights": false,
            "philipsLights": false,
            "ct": false,
            "wallSwitch": false,
            "groups": false,
            "group0": false,
            "rooms": false,
            "schedules": false,
            "rules": false,
            "heartrate": 2,
            "timeout": 2,
            "parallelRequests": 10,
            "waitTimeResend": 300,
            "waitTimeSwitch": 100,
            "waitTimeUpdate": 20
          }
        ]
}

And this is the error:
homebridge
[6/29/2017, 10:06:45 PM] Loaded plugin: homebridge-hue
[6/29/2017, 10:06:45 PM] Registering platform 'homebridge-hue.Hue'
[6/29/2017, 10:06:45 PM] ---
[6/29/2017, 10:06:45 PM] Loaded config.json with 1 accessories and 1 platforms.
[6/29/2017, 10:06:45 PM] ---
[6/29/2017, 10:06:45 PM] Loading 1 platforms...
/usr/local/lib/node_modules/homebridge/lib/api.js:122
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
      ^

Error: The requested platform 'PhillipsHue' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:122:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:284:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:80:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)

**Comment by ebaauw** [comment]
You need to specify `"platform": "Hue"`.

**Comment by marcelowilly92** [comment]
Im extremely new to this, probably should have read up on this a lot more before deciding to attempt this. downloaded Homebridge last night and downloaded 3 plugins i desired to have, wasn't able to exactly get Homebridge to find the plugins and frustrated i decided to go backwards and delete everything (which Im sure i may have missed deleting some files)

plugins i tried to make work on homebridge were;
-hisense-remote
-hisensetv
-home assistant 

restarting fresh attempting to download homebridge, i am able TO run homebridge, and it states i do not have any plug ins nor config.json

upon opening the config-sample.json, and opening in atom text editor
removing the data in accessories and platforms, 
removing -sample portion
moving config.json over to ~/.homebridge

when i now run homebridge, 
i get the same 
"Error: The requested platform 'PhillipsHue' was not registered by any plugin."


my config.json   
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:31",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",
    "accessories": [],
    "platforms": []
}



and here is the error

[12/11/2018, 3:48:12 PM] **Loaded config.json with 1 accessories and 1 platforms.**
[12/11/2018, 3:48:12 PM] ---
[12/11/2018, 3:48:12 PM] **No plugins found. See the README for information on installing plugins.**
[12/11/2018, 3:48:12 PM] **Loading 1 platforms...**
/usr/local/lib/node_modules/homebridge/lib/api.js:122
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
      ^

Error: The requested platform 'PhilipsHue' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:122:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:316:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:86:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)

Please, any help would be greatly appreciated. 
I am still looking up where I may have gone wrong, thank you.

**Comment by ebaauw** [comment]
You’re using a different config.json than the one listed above.  Are you running homebridge as the right user?

Make sure you install homebridge and all plugins globally, using:
```
sudo npm -g i homebridge --unsafe-perm
sudo npm -g i homebridge-xxx
```

**Comment by marcelowilly92** [comment]
i had already attempted to add homebridge to my homekit, to which i got an error saying if i wanted to add an accessory, i had to reset it ... not exactly word for word the error, but on google i saw people saying to change the bridge username and it would work if i tried scanning it to add to my homekit for my iphone.

i used the first homebridge install
   `sudo npm -g i homebridge --unsafe-perm`

**Comment by ebaauw** [comment]
The config.json that homebridge is using is not the config.json you listed.  You have another copy of that file somewhere.

**Comment by marcelowilly92** [comment]
i did download that file several times and used the same name, is there any way i can do a general search or uninstaller to remove every one? or will I have to manually search?
thanks @ebaauw !

**Comment by marcelowilly92** [comment]
![screen shot 2018-12-11 at 5 02 13 pm](https://user-images.githubusercontent.com/45802380/49833280-0b6dbc80-fd67-11e8-82d0-c88682e3b6c2.png)

**Comment by marcelowilly92** [comment]
wow.... i NEVER do this, i (embarrassingly) assumed it wasnt necessary to save in atom anytime i modified a file, I had deleted several times my cached accessory but never hit save. that fixed it. thank you @ebaauw for such a speedy reply!
