### ISSUE TITLE
Error: This callback function has already been called

### ISSUE THREAD

**Issue by MAPEZ1** [ebaauw/homebridge-hue#936]
OK, I’m just starting with your Homebridge-Hue and one Sonoff Door/Window (SNZB-04) and one Eurotronic Thermostat
using deCONZ 2.09.03 on RASPI4, RaspBee2 module and Homebridge 1.2.5 on another RASPI4. Both are connected via ethernet with fixed IP.
Only thing is that I’m still on node.js v12.18.4 and not on your recommended version.
First all looked good - Sensor open/closed and settings temperature as well.
But when the opened sensor should turn off the thermostat (state 3 (auto) to 0(off)) in Homekit,
the Warning showed up (see 8:40 pm).
This happens by Automation and when using Homekit or Homebridge UI X to switch the thermostat state manually.
Temperature setting works without an error.
Also I see from time to time the ‘homekit program command changed to..’ (see at 10:18 pm)
Would be great if you could help me here. I tried to find similar in the issues, but that did not help
(no renaming (#826) and that is solved in v0.12.22)
thanks a lot in advance

#### Hue config.json
       {
            "name": "Zigbee",
            "anyOn": true,
            "effects": true,
            "excludeSensorTypes": [
                "Daylight"
            ],
            "groups": false,
            "hosts": [
                "192.168.2.167"
            ],
            "lights": false,
            "linkButton": false,
            "nativeHomeKitLights": false,
            "nativeHomeKitSensors": false,
            "resource": true,
            "sensors": true,
            "users": {
                “xxxxxxxxx”: “yyyyyyyyyy"
            },
            "platform": "Hue"
        }

#### Log Messages

```
[2/24/2021, 8:38:24 PM] [Zigbee] Window / Door Sensor: set homekit contact from 0 to 1
[2/24/2021, 8:38:30 PM] [Zigbee] Window / Door Sensor: set homekit contact from 1 to 0
[2/24/2021, 8:38:34 PM] [Zigbee] Window / Door Sensor: set homekit contact from 0 to 1
[2/24/2021, 8:40:24 PM] [Zigbee] Thermostat: homekit target temperature changed from 19°C to 22°C
[2/24/2021, 8:40:31 PM] [Zigbee] Thermostat: set homekit current heating cooling state from 0 to 1
[2/24/2021, 8:40:31 PM] [Zigbee] Thermostat: set homekit valve position from 0% to 49%
[2/24/2021, 8:40:40 PM] [Zigbee] Thermostat: homekit target temperature changed from 22°C to 19°C
[2/24/2021, 8:40:47 PM] [Zigbee] Thermostat: set homekit current heating cooling state from 1 to 0
[2/24/2021, 8:40:47 PM] [Zigbee] Thermostat: set homekit valve position from 49% to 0%
[2/24/2021, 8:40:52 PM] [Zigbee] Thermostat: homekit target heating cooling state changed from 3 to 0
(node:18158) UnhandledPromiseRejectionWarning: Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at /usr/local/lib/node_modules/homebridge-hue/lib/HueSensor.js:3169:14
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:18158) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
[2/24/2021, 8:41:03 PM] [Zigbee] Thermostat: homekit target heating cooling state changed from 0 to 3
(node:18158) UnhandledPromiseRejectionWarning: Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at /usr/local/lib/node_modules/homebridge-hue/lib/HueSensor.js:3169:14
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:18158) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
[2/24/2021, 8:41:10 PM] [Zigbee] Thermostat: homekit target temperature changed from 19°C to 22°C
[2/24/2021, 8:41:18 PM] [Zigbee] Thermostat: set homekit current heating cooling state from 0 to 1
[2/24/2021, 8:41:18 PM] [Zigbee] Thermostat: set homekit valve position from 0% to 53%
[2/24/2021, 8:41:24 PM] [Zigbee] Thermostat: homekit target temperature changed from 22°C to 19°C
[2/24/2021, 8:41:29 PM] [Zigbee] Thermostat: set homekit current heating cooling state from 1 to 0
[2/24/2021, 8:41:29 PM] [Zigbee] Thermostat: set homekit valve position from 53% to 0%


[2/24/2021, 10:18:29 PM] [Zigbee] Thermostat: homekit program command changed to FF04F6
[2/24/2021, 10:18:29 PM] [Zigbee] Thermostat:   FF reset
[2/24/2021, 10:18:30 PM] [Zigbee] Thermostat: get homekit program data return 1200130014c01900fff41e1e1e1efc1216180215f6000000faffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1affffffffffffffff
[2/24/2021, 10:18:31 PM] [Zigbee] Thermostat: get homekit program data return 1200130014c01900fff41e1e1e1efc1216180215f6000000faffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1affffffffffffffff

```

#### Debug Files
[homebridge-hue.json.gz](https://github.com/ebaauw/homebridge-hue/files/6039467/homebridge-hue.json.gz)

**Comment by ebaauw** [comment]
Fix in v0.12.23.

**Comment by MAPEZ1** [comment]
Hi, and thanks... very quick - amazing :-)
I installed now v0.12.23 but did not yet update node.js. Maybe on weekend after SD backup.
(pls let me know if you think the below may have something to do with not yet update on node & lib)
So far I can confirm that the 'Callback' error is gone, but after changing manually the thermostat state in HomeKit
from Auto (3) to Off (0), Homebridge throwed again shortly after:
```
[2/25/2021, 11:18:37 PM] [Zigbee] Thermostat: homekit target heating cooling state changed from 3 to 0
[2/25/2021, 11:20:07 PM] [Zigbee] Thermostat: homekit program command changed to FF04F6
[2/25/2021, 11:20:07 PM] [Zigbee] Thermostat:   FF reset
[2/25/2021, 11:20:07 PM] [Zigbee] Thermostat: get homekit program data return 1200130014c01900fff41e1e1e1efc1417190215f6000000faffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1affffffffffffffff
[2/25/2021, 11:20:08 PM] [Zigbee] Thermostat: get homekit program data return 1200130014c01900fff41e1e1e1efc1417190215f6000000faffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1affffffffffffffff
[2/25/2021, 11:34:41 PM] [Zigbee] Thermostat: set homekit target heating cooling state from 0 to 3
[2/25/2021, 11:35:48 PM] [Zigbee] Thermostat: homekit program command changed to FF04F6
[2/25/2021, 11:35:48 PM] [Zigbee] Thermostat:   FF reset
[2/25/2021, 11:35:49 PM] [Zigbee] Thermostat: get homekit program data return 1200130014c01900fff41e1e1e1efc2317190215f6000000faffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1affffffffffffffff
[2/25/2021, 11:35:49 PM] [Zigbee] Thermostat: get homekit program data return 1200130014c01900fff41e1e1e1efc2317190215f6000000faffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1affffffffffffffff
[2/25/2021, 11:35:54 PM] [Zigbee] Thermostat: homekit program command changed to FF04F6
[2/25/2021, 11:35:54 PM] [Zigbee] Thermostat:   FF reset
[2/25/2021, 11:35:54 PM] [Zigbee] Thermostat: get homekit program data return 1200130014c01900fff41e1e1e1efc2317190215f6000000faffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1affffffffffffffff
[2/25/2021, 11:35:56 PM] [Zigbee] Thermostat: get homekit program data return 1200130014c01900fff41e1e1e1efc2317190215f6000000faffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1affffffffffffffff
```
That seem to happen only after an On / Off action on the thermostat, even if it's switching on itself after about 5 minutes
(-> 11:34:41 PM , somewhere I read thats a standard function of the thermostat to avoid freezing - means no manual HomeKit action)
Thanks again

**Comment by ebaauw** [comment]
That's no error, not even a warning: just logging the interaction between Eve and the (assumed Eve Thermo) concerning the on-device schedules.

**Comment by MAPEZ1** [comment]
I monitored and tested further the Thermostat. After beta v0.12.24-0 no messages anymore.
Thanks

**Comment by ebaauw** [comment]
Disabled in v0.12.25.
