### ISSUE TITLE
homebridge-hue v0.13.1 crashes Homebridge v1.3.3

### ISSUE THREAD

**Issue by jsiegenthaler** [ebaauw/homebridge-hue#951]
#### Issue

homebridge-hue v0.13.1 crashes Homebridge v1.3.3
See log
Homebridge then tries to restart, crashes again, and loops forever in this cycle.

#### Log Messages

```
TypeError: configJson.hosts is not iterable
    at HuePlatform.maskConfigJson (/usr/lib/node_modules/homebridge-hue/lib/HuePlatform.js:387:33)
    at HuePlatform.accessories (/usr/lib/node_modules/homebridge-hue/lib/HuePlatform.js:205:40)
    at /usr/lib/node_modules/homebridge/src/bridgeService.ts:529:24
    at new Promise (<anonymous>)
    at BridgeService.loadPlatformAccessories (/usr/lib/node_modules/homebridge/src/bridgeService.ts:523:12)
    at /usr/lib/node_modules/homebridge/src/server.ts:445:42
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/lib/node_modules/homebridge/src/server.ts:372:27)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:159:29)
TypeError: configJson.hosts is not iterable
    at HuePlatform.maskConfigJson (/usr/lib/node_modules/homebridge-hue/lib/HuePlatform.js:387:33)
    at HuePlatform.accessories (/usr/lib/node_modules/homebridge-hue/lib/HuePlatform.js:205:40)
    at /usr/lib/node_modules/homebridge/src/bridgeService.ts:529:24
    at new Promise (<anonymous>)
    at BridgeService.loadPlatformAccessories (/usr/lib/node_modules/homebridge/src/bridgeService.ts:523:12)
    at /usr/lib/node_modules/homebridge/src/server.ts:445:42
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/lib/node_modules/homebridge/src/server.ts:372:27)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:159:29)
```

**Comment by tomsteenbakkers** [comment]
+1

**Comment by ebaauw** [comment]
Are you using automatic discovery for your bridge(s)/gateway(s)?

**Comment by tomsteenbakkers** [comment]
Yes and using a child bridge

**Comment by ebaauw** [comment]
Child bridge shouldn't matter, but fix for #950 introduced this bug.  Sorry.

Could you try beta v0.12.2-0?  Install through _Install Previous Version_ in the UI or through `sudo npm -g i homebridge-hue@beta`.

**Comment by tomsteenbakkers** [comment]
Beta is working.

**Comment by jostrasser** [comment]
@ebaauw do you have pulled v0.13.1 and what is the following version?

Tag: https://github.com/ebaauw/homebridge-hue/tree/v0.32.2-0
Commit: https://github.com/ebaauw/homebridge-hue/commit/f208c2fe9b40b02f9c18f27b7820657f6f1851eb
Released by: https://github.com/ebaauw

**Comment by ebaauw** [comment]
Published v0.13.2.

**Comment by tomsteenbakkers** [comment]
Works like a charm! Get only a warning that I’m not using the right API.

**Comment by ebaauw** [comment]
Are you running the decONZ beta?  Generally shouldn't be a problem, but I test against the latest released version (currently 2.9.3).  Or did Hue release a new firmware?

**Comment by tomsteenbakkers** [comment]
Not running decONZ beta. It’s only a warning.

**Comment by ebaauw** [comment]
What's the warning, then?

**Comment by tomsteenbakkers** [comment]
At startup

![PNG image 2](https://user-images.githubusercontent.com/24613800/111082429-8014a000-8508-11eb-8fea-b4268a43a3d6.png)

**Comment by ebaauw** [comment]
And what version is the Hue bridge running?

**Comment by tomsteenbakkers** [comment]
![Uploading PNG image 3.png…]()

**Comment by pponce** [comment]
v0.13.2 seems to crash my homebridge 1.3.3 instance.
errors from my log below

`[3/14/2021, 1:15:53 PM] [Hue] Phoscon-GW: dresden elektronik deCONZ gateway v2.10.2, api v1.16.0
[3/14/2021, 1:15:53 PM] [Hue] Phoscon-GW: warning: not using recommended deCONZ gateway version 2.9.3
[3/14/2021, 1:15:53 PM] [Hue] Phoscon-GW: request 1: POST / {"devicetype":"homebridge-hue#homebridge"}
[3/14/2021, 1:15:53 PM] [Hue] Phoscon-GW: request 1: http status 403 Forbidden
[3/14/2021, 1:16:08 PM] [Hue] Phoscon-GW: request 2: http status 403 Forbidden
[3/14/2021, 1:16:12 PM] [homebridge-hue] This plugin is taking long time to load and preventing Homebridge from starting. See https://git.io/JtMGR for more info.
[3/14/2021, 1:16:23 PM] [Hue] Phoscon-GW: request 3: POST / {"devicetype":"homebridge-hue#homebridge"}
[3/14/2021, 1:16:23 PM] [Hue] Phoscon-GW: request 3: http status 403 Forbidden
[3/14/2021, 1:16:32 PM] [homebridge-hue] This plugin is taking long time to load and preventing Homebridge from starting. See https://git.io/JtMGR for more info.
[3/14/2021, 1:16:38 PM] [Hue] Phoscon-GW: request 4: POST / {"devicetype":"homebridge-hue#homebridge"}
[3/14/2021, 1:16:38 PM] [Hue] Phoscon-GW: request 4: http status 403 Forbidden
[3/14/2021, 1:16:52 PM] [homebridge-hue] This plugin is taking long time to load and preventing Homebridge from starting. See https://git.io/JtMGR for more info.
[3/14/2021, 1:16:53 PM] [Hue] Phoscon-GW: request 5: POST / {"devicetype":"homebridge-hue#homebridge"}
[3/14/2021, 1:16:53 PM] [Hue] Phoscon-GW: request 5: http status 403 Forbidden
[3/14/2021, 1:17:08 PM] [Hue] Phoscon-GW: request 6: POST / {"devicetype":"homebridge-hue#homebridge"}
[3/14/2021, 1:17:08 PM] [Hue] Phoscon-GW: request 6: http status 403 Forbidden
[3/14/2021, 1:17:12 PM] [homebridge-hue] This plugin is taking long time to load and preventing Homebridge from starting. See https://git.io/JtMGR for more info.
[3/14/2021, 1:17:23 PM] [Hue] Phoscon-GW: request 7: POST / {"devicetype":"homebridge-hue#homebridge"}
[3/14/2021, 1:17:23 PM] [Hue] Phoscon-GW: request 7: http status 403 Forbidden
[3/14/2021, 1:17:32 PM] [homebridge-hue] This plugin is taking long time to load and preventing Homebridge from starting. See https://git.io/JtMGR for more info.
[3/14/2021, 1:17:38 PM] [Hue] Phoscon-GW: request 8: POST / {"devicetype":"homebridge-hue#homebridge"}
[3/14/2021, 1:17:38 PM] [Hue] Phoscon-GW: request 8: http status 403 Forbidden
`

**Comment by ebaauw** [comment]
Homebridge Hue tries to get an API key (username) from deCONZ, but deCONZ isn't giving one.  Typically this happens when you haven't unlocked the gateway; not sure why Homebridge Hue doesn't log the message to instruct you to do so.

Is this a new installation?  If not, did you change the `users` key in config.json?

**Comment by pponce** [comment]
I did just update to latest gateway version released march 4.
I'll try and toll that back and see if that fixes my issue.

This is not a new installation.  same  users key as before.
I had a username issue somewhat recently that you fixed.  You had to allow for lower case users key.

**Comment by ebaauw** [comment]
Please help me remember: which issue was that?  Or Discord?

**Comment by pponce** [comment]
Ok so rolling back to
https://deconz.dresden-elektronik.de/raspbian/beta/deconz-2.09.03-qt5.deb
fixed my homebridge not starting issue with v0,13.2 and homebridge 1.3.3

This was the issue you fixed that was related to my bridge id being lowercase when you were expecting upper case.
https://github.com/ebaauw/homebridge-hue/issues/901

**Comment by pponce** [comment]
i missed your ask to run this command 
Can you run of ph -H x.x.x.x config and check that the reported bridgeid hasn't changed?
do you want me to install latest deconz beta again and run that command?

**Comment by ebaauw** [comment]
Yeah, I think deCONZ might expose a different `bridgeid` after updating.

**Comment by pponce** [comment]
ok i reinstalled the latest deconz beta (2.10.2).
Bidgeid displayed when i run the PH comand is the same as what is in my config.json but it's reported in uppercase.
Would i just need to update my config.json to set my bridge ID to uppercase?
Would making this change mess up any of my settings in homekit?

**Comment by ebaauw** [comment]
Yeah, changing the value in config.json should do the trick.  Homebridge Hue delays Homebridge startup by design in case of issues, so you don’t have to redo the your HomeKit settings.

**Comment by pponce** [comment]
thanks!. I'm running 2.10.2 of deconz and things seem to be working well now.
