### ISSUE TITLE
IKEA TradFri lights state 'not suiteable' ("Niet geschikt") in app after update to v0.13.5

### ISSUE THREAD

**Issue by Richardmarobert** [ebaauw/homebridge-hue#963]
#### Issue

When upgrading to the v0.13.5 version all of the Trädfri lights I have working with the homebridge stopped. After some testing I found that downgrading to V0.12. 26 brought the lights back online again. 

#### Log Messages

```
```

**Comment by ebaauw** [comment]
Could you post a screenshot?  Are there any messages in the Homebridge log?

**Comment by Richardmarobert** [comment]
apr 03 18:58:00 ubuntu_server homebridge[22314]: _getTarget() -> this.status = online
apr 03 18:58:00 ubuntu_server homebridge[22314]: [3-4-2021 18:58:00] [Anna] could not fetch current target temperature
apr 03 18:58:00 ubuntu_server homebridge[22314]: [3-4-2021 18:58:00] [Hue] Philips hue: bridge request 29: post / {"devicetype":"homebridge-hue#ubuntu_server"}
apr 03 18:58:00 ubuntu_server homebridge[22314]: [3-4-2021 18:58:00] [Hue] Philips hue: bridge request 29: error 101 link button not pressed
apr 03 18:58:00 ubuntu_server homebridge[22314]: [3-4-2021 18:58:00] [Hue] Philips hue: press link button on the bridge to create a user - retrying in 15s
apr 03 18:58:01 ubuntu_server homebridge[22314]: [3-4-2021 18:58:01] [Anna] getCurrentTemperature from Anna on: 192.168.2.13
apr 03 18:58:01 ubuntu_server homebridge[22314]: [3-4-2021 18:58:01] [Anna] getCurrentTargetTemperature from Anna on: 192.168.2.13
apr 03 18:58:02 ubuntu_server homebridge[22314]: _getMeasure() -> this.status = wait
apr 03 18:58:03 ubuntu_server homebridge[22314]: _getTarget() -> this.status = online
apr 03 18:58:03 ubuntu_server homebridge[22314]: _getMeasure() -> this.status = online

**Comment by Richardmarobert** [comment]
Appearantly I was too soon to conclude downgrading did the trick. After a while the bridge keeps requiring to push the link. The 'not suitable' doesn't appear anymore,though: It now states: "No reaction". If I check the log then I see that the Hue Bridge requires the link button to be pushed again. This has been quite stable until this afternoon where I updated the Hue Bridge. Before I was able to, a nodejs update was required, too, so this has been updated, too.

**Comment by ebaauw** [comment]
If you managed to reset the Hue bridge during the update, it will lose the API keys (usernames), and Homebridge Hue needs to request a new one.  Make sure to edit config.json with the newly generated key, or you’ll be asked to press the link button on every Homebridge restart.

By design, Homebridge Hue delays the startup of Homebridge, until you’ve pressed the link button, or you’d lose your HomeKit settings.

**Comment by Richardmarobert** [comment]
I am familiar with that. Normally, restarting my Homebridge requires the renewal of the API keys. However; just once. Now it renewal is required without restarting the homebridge.

**Comment by ebaauw** [comment]
I don’t know what’s happening, need to see a debug log file for that.  Sounds like the Hue bridge is choking or Homebridge crashes and restarts.

Are you saying you pressed the link button every time you restarted Homebridge to create a new username?  That doesn’t seem like a good idea.  I suppose the bridge will start removing usernames at some point, if there’s too many of them.

**Comment by Richardmarobert** [comment]
I downgraded the plugin, added the key to the config.json and then updated the plugin. Works fine now. Thanks for the support.

**Comment by Richardmarobert** [comment]
Too soon. Restarted the Homebridge service today and the issue reappears. Log is below; the same error appears for all Trädri lights. I seem to use bridge API v1.43.0 and the bridge warns about usage of 1.42.0 if I read it correctly.  What could be the issue?

`[10-4-2021 11:25:04] [FibaroHC2] didFinishLaunching.
[10-4-2021 11:25:04] [Hue] Philips hue: Signify Netherlands B.V. BSB002 bridge v1943185030, api v1.43.0
[10-4-2021 11:25:04] [Hue] Philips hue: warning: not using recommended Hue bridge api version 1.42.0
[10-4-2021 11:25:04] [Living] Found a playable device at 192.168.2.190 for room 'Woonkamer'
[10-4-2021 11:25:04] [Hue] Philips hue: error: /lights/8: {"state":{"on":false,"bri":69,"ct":367,"alert":"select","colormode":"ct","mode":"homeautomation","reachable":true},"swupdate":{"state":"notupdatable","lastinstall":"2020-03-07T18:04:18"},"type":"Color temperature light","name":"Erker midden","modelid":"TRADFRI bulb GU10 WS 400lm","manufacturername":"IKEA of Sweden","productname":"Color temperature light","capabilities":{"certified":false,"control":{"ct":{"min":250,"max":454}},"streaming":{"renderer":false,"proxy":false}},"config":{"archetype":"recessedceiling","function":"functional","direction":"omnidirectional"},"uniqueid":"68:0a:e2:ff:fe:1c:3b:74-01","swversion":"2.0.022"}
TypeError: Cannot read property 'updateValue' of undefined
    at new HueLight (/usr/lib/node_modules/homebridge-hue/lib/HueLight.js:460:9)
    at HueAccessory.exposeLightResource (/usr/lib/node_modules/homebridge-hue/lib/HueAccessory.js:235:19)
    at HueAccessory.exposeLightResources (/usr/lib/node_modules/homebridge-hue/lib/HueAccessory.js:225:12)
    at HueAccessory.expose (/usr/lib/node_modules/homebridge-hue/lib/HueAccessory.js:123:8)
    at HueBridge.exposeResources (/usr/lib/node_modules/homebridge-hue/lib/HueBridge.js:583:49)
    at HueBridge.accessories (/usr/lib/node_modules/homebridge-hue/lib/HueBridge.js:116:16)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
    at HuePlatform.accessories (/usr/lib/node_modules/homebridge-hue/lib/HuePlatform.js:227:29)
[10-4-2021 11:25:04] [Hue] Philips hue: error: /lights/10: {"state":{"on":false,"bri":23,"ct":454,"alert":"select","colormode":"ct","mode":"homeautomation","reachable":true},"swupdate":{"state":"notupdatable","lastinstall":"2020-03-07T18:20:03"},"type":"Color temperature light","name":"Keuken_rechts 1","modelid":"TRADFRI bulb GU10 WS 400lm","manufacturername":"IKEA of Sweden","productname":"Color temperature light","capabilities":{"certified":false,"control":{"ct":{"min":250,"max":454}},"streaming":{"renderer":false,"proxy":false}},"config":{"archetype":"recessedceiling","function":"functional","direction":"omnidirectional"},"uniqueid":"68:0a:e2:ff:fe:1c:3f:bf-01","swversion":"2.0.022"}
TypeError: Cannot read property 'updateValue' of undefined
    at new HueLight (/usr/lib/node_modules/homebridge-hue/lib/HueLight.js:460:9)
    at HueAccessory.exposeLightResource (/usr/lib/node_modules/homebridge-hue/lib/HueAccessory.js:235:19)
    at HueAccessory.exposeLightResources (/usr/lib/node_modules/homebridge-hue/lib/HueAccessory.js:225:12)
    at HueAccessory.expose (/usr/lib/node_modules/homebridge-hue/lib/HueAccessory.js:123:8)
    at HueBridge.exposeResources (/usr/lib/node_modules/homebridge-hue/lib/HueBridge.js:583:49)
    at HueBridge.accessories (/usr/lib/node_modules/homebridge-hue/lib/HueBridge.js:116:16)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
    at HuePlatform.accessories (/usr/lib/node_modules/homebridge-hue/lib/HuePlatform.js:227:29)
[10-4-2021 11:25:04] [Hue] Philips hue: error: /lights/11: {"state":{"on":false,"bri":69,"ct":367,"alert":"select","colormode":"ct","mode":"homeautomation","reachable":true},"swupdate":{"state":"notupdatable","lastinstall":"2020-03-07T18:23:14"},"type":"Color temperature light","name":"Erker rechts","modelid":"TRADFRI bulb GU10 WS 400lm","manufacturername":"IKEA of Sweden","productname":"Color temperature light","capabilities":{"certified":false,"control":{"ct":{"min":250,"max":454}},"streaming":{"renderer":false,"proxy":false}},"config":{"archetype":"recessedceiling","function":"functional","direction":"omnidirectional"},"uniqueid":"ec:1b:bd:ff:fe:99:3d:b9-01","swversion":"2.0.022"}
TypeError: Cannot read property 'updateValue' of undefined
    at new HueLight (/usr/lib/node_modules/homebridge-hue/lib/HueLight.js:460:9)
    at HueAccessory.exposeLightResource (/usr/lib/node_modules/homebridge-hue/lib/HueAccessory.js:235:19)
    at HueAccessory.exposeLightResources (/usr/lib/node_modules/homebridge-hue/lib/HueAccessory.js:225:12)
    at HueAccessory.expose (/usr/lib/node_modules/homebridge-hue/lib/HueAccessory.js:123:8)
    at HueBridge.exposeResources (/usr/lib/node_modules/homebridge-hue/lib/HueBridge.js:583:49)
    at HueBridge.accessories (/usr/lib/node_modules/homebridge-hue/lib/HueBridge.js:116:16)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
    at HuePlatform.accessories (/usr/lib/node_modules/homebridge-hue/lib/HuePlatform.js:227:29)
[10-4-2021 11:25:04] [Hue] Philips hue: error: /lights/12: {"state":{"on":false,"bri":23,"ct":454,"alert":"select","colormode":"ct","mode":"homeautomation","reachable":true},"swupdate":{"state":"notupdatable","lastinstall":"2020-03-07T18:26:46"},"type":"Color temperature light","name":"Keuken links-1","modelid":"TRADFRI bulb GU10 WS 400lm","manufacturername":"IKEA of Sweden","productname":"Color temperature light","capabilities":{"certified":false,"control":{"ct":{"min":250,"max":454}},"streaming":{"renderer":false,"proxy":false}},"config":{"archetype":"recessedceiling","function":"functional","direction":"omnidirectional"},"uniqueid":"68:0a:e2:ff:fe:1c:54:45-01","swversion":"2.0.022"}
TypeError: Cannot read property 'updateValue' of undefined
    at new HueLight (/usr/lib/node_modules/homebridge-hue/lib/HueLight.js:460:9)
    at HueAccessory.exposeLightResource (/usr/lib/node_modules/homebridge-hue/lib/HueAccessory.js:235:19)
    at HueAccessory.exposeLightResources (/usr/lib/node_modules/homebridge-hue/lib/HueAccessory.js:225:12)
    at HueAccessory.expose (/usr/lib/node_modules/homebridge-hue/lib/HueAccessory.js:123:8)
    at HueBridge.exposeResources (/usr/lib/node_modules/homebridge-hue/lib/HueBridge.js:583:49)
    at HueBridge.accessories (/usr/lib/node_modules/homebridge-hue/lib/HueBridge.js:116:16)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
    at HuePlatform.accessories (/usr/lib/node_modules/homebridge-hue/lib/HuePlatform.js:227:29)
[10-4-2021 11:25:04] [Hue] Philips hue: error: /lights/13: {"state":{"on":false,"bri":24,"ct":454,"alert":"select","colormode":"ct","mode":"homeautomation","reachable":true},"swupdate":{"state":"notupdatable","lastinstall":"2020-03-07T18:31:38"},"type":"Color temperature light","name":"Keuken-links 2","modelid":"TRADFRI bulb GU10 WS 400lm","manufacturername":"IKEA of Sweden","productname":"Color temperature light","capabilities":{"certified":false,"control":{"ct":{"min":250,"max":454}},"streaming":{"renderer":false,"proxy":false}},"config":{"archetype":"recessedceiling","function":"functional","direction":"omnidirectional"},"uniqueid":"68:0a:e2:ff:fe:12:a4:68-01","swversion":"2.0.022"}
TypeError: Cannot read property 'updateValue' of undefined
    at new HueLight (/usr/lib/node_modules/homebridge-hue/lib/HueLight.js:460:9)
    at HueAccessory.exposeLightResource (/usr/lib/node_modules/homebridge-hue/lib/HueAccessory.js:235:19)
    at HueAccessory.exposeLightResources (/usr/lib/node_modules/homebridge-hue/lib/HueAccessory.js:225:12)
    at HueAccessory.expose (/usr/lib/node_modules/homebridge-hue/lib/HueAccessory.js:123:8)
    at HueBridge.exposeResources (/usr/lib/node_modules/homebridge-hue/lib/HueBridge.js:583:49)
    at HueBridge.accessories (/usr/lib/node_modules/homebridge-hue/lib/HueBridge.js:116:16)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
    at HuePlatform.accessories (/usr/lib/node_modules/homebridge-hue/lib/HuePlatform.js:227:29)
[10-4-2021 11:25:04] [Hue] Philips hue: error: /lights/14: {"state":{"on":false,"bri":225,"ct":454,"alert":"select","colormode":"ct","mode":"homeautomation","reachable":true},"swupdate":{"state":"notupdatable","lastinstall":"2020-03-07T18:35:08"},"type":"Color temperature light","name":"Schuifdeur links","modelid":"TRADFRI bulb GU10 WS 400lm","manufacturername":"IKEA of Sweden","productname":"Color temperature light","capabilities":{"certified":false,"control":{"ct":{"min":250,"max":454}},"streaming":{"renderer":false,"proxy":false}},"config":{"archetype":"recessedceiling","function":"functional","direction":"omnidirectional"},"uniqueid":"68:0a:e2:ff:fe:1c:57:57-01","swversion":"2.0.022"}`

**Comment by ebaauw** [comment]
Please capture and **attach** a full debug log file, see the FAQ.

**Comment by Richardmarobert** [comment]
I think Homebridge was outdated. It took me a while to figure out how to see the correct log file as my UI plugin has no option that is descirbed in the FAQ. But, appearantly I haven't updated  'homebridge' since 1.1.1. This is not shown in the GUI so easily forgotten. I updated this version to the latest, and - for now - it runs as expected. Thanks!
