### ISSUE TITLE
Problem with Lutron Aurora Dimmer after plugin upgrade

### ISSUE THREAD

**Issue by banzalik** [ebaauw/homebridge-hue#984]
#### Issue
After updating homebridge-hue v0.13.10 getting error when homebridge is starting   

#### Log Messages

```
[5/12/2021, 2:25:33 PM] [Hue] Philips hue: error: /sensors/18: {"state":{"rotaryevent":2,"expectedrotation":400,"expectedeventduration":400,"lastupdated":"2021-05-12T03:36:23"},"swupdate":{"state":"noupdates","lastinstall":"2021-03-13T05:08:22"},"config":{"on":true,"battery":100,"reachable":true,"pending":[]},"name":"Bedroom Lutron Aurora","type":"ZLLRelativeRotary","modelid":"Z3-1BRL","manufacturername":"Lutron","productname":"Lutron Aurora","diversityid":"2c3a75ff-55c4-4e4d-8c44-82d330b8eb9b","swversion":"3.8","uniqueid":"ff:ff:00:0f:e7:fe:bf:52-01-fc00-0014","capabilities":{"certified":true,"primary":true,"inputs":[{"repeatintervals":[400],"events":[{"rotaryevent":1,"eventtype":"start"},{"rotaryevent":2,"eventtype":"repeat"}]}]}}
TypeError: Cannot set property '2' of undefined
    at HueSensor.createButton (/homebridge/node_modules/homebridge-hue/lib/HueSensor.js:1681:36)
    at new HueSensor (/homebridge/node_modules/homebridge-hue/lib/HueSensor.js:798:14)
    at HueAccessory.exposeSensorResource (/homebridge/node_modules/homebridge-hue/lib/HueAccessory.js:322:20)
    at HueAccessory.exposeSensorResources (/homebridge/node_modules/homebridge-hue/lib/HueAccessory.js:312:12)
    at HueAccessory.expose (/homebridge/node_modules/homebridge-hue/lib/HueAccessory.js:124:8)
    at HueBridge.exposeResources (/homebridge/node_modules/homebridge-hue/lib/HueBridge.js:583:49)
    at HueBridge.accessories (/homebridge/node_modules/homebridge-hue/lib/HueBridge.js:116:16)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Promise.all (index 1)
    at HuePlatform.accessories (/homebridge/node_modules/homebridge-hue/lib/HuePlatform.js:234:29)
```
Device: https://www.amazon.com/Lutron-Aurora-Dimmer-Philips-Z3-1BRL-WH-L0/dp/B07RJ14FBS/

**Comment by ebaauw** [comment]
In v0.13.11.
