### ISSUE TITLE
Hue Heartbeat error

### ISSUE THREAD

**Issue by gilfy** [ebaauw/homebridge-hue#996]
#### Issue

Hue Heartbeat error 

I use the homebridge-notification plugin and after a sensor get triggered the heartbeat of hue throws error logs watch below. I don´t get it why... If these are in the logs i can´t control e.g my ikea lamp which is connected to my hue bridge

#### Log Messages

```
Philips hue: heartbeat error: TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function. Received an instance of Object
    at checkListener (events.js:130:11)
    at ClientRequest.once (events.js:495:3)
    at new ClientRequest (_http_client.js:215:10)
    at Object.request (https.js:333:10)
    at Object.request (/usr/local/lib/node_modules/homebridge-notification/node_modules/agent-base/patch-core.js:25:22)
    at /usr/local/lib/node_modules/homebridge-hue/node_modules/homebridge-lib/lib/HttpClient.js:363:34
    at new Promise (<anonymous>)
    at HueClient.request (/usr/local/lib/node_modules/homebridge-hue/node_modules/homebridge-lib/lib/HttpClient.js:340:12)
    at HueClient.request (/usr/local/lib/node_modules/homebridge-hue/lib/HueClient.js:567:36)
    at HueClient.get (/usr/local/lib/node_modules/homebridge-hue/lib/HueClient.js:331:31)
```
![image](https://user-images.githubusercontent.com/31819039/124245582-68494200-db20-11eb-9d7d-cac885e638a7.png)

**Comment by gilfy** [comment]
Thats my config below / i removed usernames and apikeys ;) 
```
{
    "bridge": {
        "name": "Homebridge 1656",
        "username": "USERNAME",
        "port": 51073,
        "pin": "XXX-XXX-XXX",
        "bind": [
            "eth0"
        ],
        "advertiser": "ciao"
    },
    "accessories": [
        {
            "name": "Security system",
            "default_mode": "Off",
            "arm_seconds": 0,
            "trigger_seconds": 0,
            "reset_minutes": 10,
            "audio": false,
            "audio_language": "en-US",
            "save_state": false,
            "proxy_mode": false,
            "test_mode": false,
            "override_off": false,
            "reset_off_flow": false,
            "siren_sensor": false,
            "siren_sensor_seconds": 5,
            "reset_sensor": false,
            "mode_switches": false,
            "mode_off_switch": true,
            "mode_away_extended_switch": false,
            "mode_pause_switch": false,
            "pause_minutes": 0,
            "siren_switch": false,
            "siren_mode_switches": false,
            "double_knock": false,
            "double_knock_seconds": 90,
            "audio_volume": "100",
            "audio_arming_looped": false,
            "audio_alert_looped": false,
            "accessory": "security-system"
        },
        {
            "accessory": "Weather",
            "apikey": "myapikeay",
            "locationByCoordinates": "lat=52.3758916&lon=9.7320104",
            "name": "Außentemperatur",
            "pollingInterval": 10,
            "enableHistory": true
        },
        {
            "accessory": "Notification",
            "name": "Lüften",
            "ifttt_api_key": "XXXXXXX",
            "ifttt_event": "Lüften",
            "ifttt_message": "Du musst dringend lüften",
            "ifttt_mute_notification_interval_in_sec": 10
        },
        {
            "accessory": "Notification",
            "name": "Luft sauber",
            "ifttt_api_key": "XXXXXX",
            "ifttt_event": "Luft sauber",
            "ifttt_message": "Luft ist wieder sauber",
            "ifttt_mute_notification_interval_in_sec": 10
        },
        {
            "accessory": "Notification",
            "name": "Heiß",
            "ifttt_api_key": "XXXXX",
            "ifttt_event": "Heiß",
            "ifttt_message": "Es ist sehr heiß",
            "ifttt_mute_notification_interval_in_sec": 10
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "Hue",
            "anyOn": true,
            "effects": true,
            "hosts": [
                "IP-ADDREEESS"
            ],
            "lights": true,
            "linkButton": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "resource": true,
            "sensors": false,
            "users": {
                "XXXXXX": "XXXXXXX"
            },
            "platform": "Hue"
        },
        {
            "name": "TplinkSmarthome",
            "addCustomCharacteristics": true,
            "deviceTypes": [
                "plug",
                "bulb"
            ],
            "platform": "TplinkSmarthome"
        },
        {
            "hosts": [
                {
                    "name": "Internet down",
                    "host": "8.8.8.8",
                    "interval": 10,
                    "timeout": 25,
                    "retries": 1,
                    "startup_as_failed": true,
                    "closed_on_success": true
                }
            ],
            "platform": "PingHosts"
        },
        {
            "devices": [
                {
                    "name": "Xbox",
                    "host": "XXXXX",
                    "xboxliveid": "XXXXXX",
                    "refreshInterval": 5,
                    "volumeControl": 0,
                    "switchInfoMenu": true,
                    "inputs": [
                        {
                            "name": "Dashboard",
                            "reference": "Xbox.Dashboard_8wekyb3d8bbwe!Xbox.Dashboard.Application",
                            "type": "HOME_SCREEN"
                        },
                        {
                            "name": "Brawlhalla",
                            "reference": "Brawlhalla_5.3.29.0_neutral_b6krnev7r9sf8",
                            "type": "APPLICATION"
                        },
                        {
                            "name": "Spotify",
                            "reference": "SpotifyAB.SpotifyMusic-forXbox_zpdnekdrzrea0!App",
                            "type": "APPLICATION"
                        }
                    ]
                }
            ],
            "platform": "XboxTv"
        }
    ]
}
```

**Comment by ebaauw** [comment]
>     at Object.request (/usr/local/lib/node_modules/homebridge-notification/node_modules/agent-base/patch-core.js:25:22)

The `agent-base` module in `Homebridge-notification` breaks (“patches”) the `https` module of NodeJS. Remove that plugin (or run it in a different Homebridge instance). See #629.
