### ISSUE TITLE
Updated hoobs from 3.3.5 to 3.3.6 and hue plugin crashes

### ISSUE THREAD

**Issue by MrWGT** [ebaauw/homebridge-hue#997]
Updated hoobs from 3.3.5 to 3.3.6 and hoobs crashes with hue plugin:

**6.7.2021, 18:36:25 [Hue] ConBee II: 38 accessories6.7.2021, 18:36:25 Initializing platform accessory 'ConBee II'...6.7.2021, 18:36:25 [Hue] ConBee II: 2 services6.7.2021, 18:36:25 [Hue] homebridge: error: AssertionError [ERR_ASSERTION]: Services must be created with a valid UUID.
    at new Service (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/src/lib/Service.ts:289:11)
    at parseServiceJSON (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/src/lib/AccessoryLoader.ts:124:19)
    at /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/src/lib/AccessoryLoader.ts:69:21
    at Array.forEach (<anonymous>)
    at Object.parseAccessoryJSON (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/src/lib/AccessoryLoader.ts:68:17)
    at Server.createHAPAccessory (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:402:36)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:376:44
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:370:29
    at /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at HuePlatform.accessories (/home/hoobs/.hoobs/node_modules/@hoobs/hue/lib/HuePlatform.js:312:5)6.7.2021, 18:36:26 [Hue] BM Flurtür: set homekit dark from 0 to 1**

**Comment by ebaauw** [comment]
I'm sorry, I have no idea.  Best contact hoobs support.  If they think the issue is with Homebridge Hue, I need to know which service on which accessory they think has an invalid UUID.

**Comment by MrWGT** [comment]
Solved with hoobs 3.3.7. Tnx
